export interface EpisodeExpression {
  japanese: string
  reading: string
  pronunciation: string
  korean: string
  example?: string
}

export interface Episode {
  id: string
  series_id: string
  series_name_jp: string
  series_name_kr: string
  number: number
  tag: string
  scene_kr: string
  scene_jp: string
  character_name_jp: string
  character_name_kr: string
  character_emoji: string
  dialogue_jp: string
  dialogue_kr: string
  vocab_word: string
  vocab_reading: string
  vocab_meaning: string
  vocab_example_jp: string
  vocab_example_kr: string
  vocab_korea_compare: string
  expressions: EpisodeExpression[]
  deeper_reading: string
}

export const EPISODES: Episode[] = [
  {
    id: 'granny-01',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 1,
    tag: '지역공동체',
    scene_kr: '이사 온 첫 날, 옆집 할머니가 현관 앞에서 기다리고 있었다',
    scene_jp: '引っ越してきた初日、隣のおばあちゃんが玄関の前で待っていた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: 'あら、新しいお隣さんね。よろしくお願いしますね。何かあったら遠慮なく声かけてね。',
    dialogue_kr: '어머, 새 이웃이구나. 잘 부탁해요. 무슨 일 있으면 편하게 불러요.',
    vocab_word: 'お隣さん',
    vocab_reading: 'おとなりさん',
    vocab_meaning: '이웃, 옆집 사람',
    vocab_example_jp: '「お隣さんに塩を借りる」(이웃에게 소금을 빌리다) — 가까운 이웃 관계를 나타내는 표현입니다.',
    vocab_example_kr: '일본에서 \"お隣さん\"는 단순한 옆집이 아니라, 서로 돕고 지내는 지역사회 관계를 의미합니다.',
    vocab_korea_compare: '한국의 \"옆집\"보다 좀 더 따뜻하고 공동체적인 뉘앙스가 있어요. 일본 주택가에서는 이사 시 인사(引越し挨拶)가 중요한 문화입니다.',
    expressions: [
      { japanese: 'よろしくお願いします', reading: 'よろしくおねがいします', pronunciation: '요로시쿠 오네가이시마스', korean: '잘 부탁드립니다', example: '처음 만날 때 필수 표현' },
      { japanese: '遠慮なく', reading: 'えんりょなく', pronunciation: '엔료나쿠', korean: '편하게, 거리낌 없이', example: '「遠慮なく声かけてね」편하게 불러요' },
      { japanese: '声をかける', reading: 'こえをかける', pronunciation: '코에오 카케루', korean: '말을 걸다, 부르다', example: '「何かあったら声かけて」무슨 일 있으면 불러줘' },
    ],
    deeper_reading: '일본의 이사 인사(引越し挨拶, ひっこしあいさつ)는 중요한 문화입니다. 이사 온 날 근처 집에 수건이나 세제 같은 작은 선물을 들고 인사를 다니는 것이 일반적이에요. 이를 통해 첫 인상을 좋게 남기고 이웃 관계의 기초를 쌓습니다.',
  },
  {
    id: 'granny-02',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 2,
    tag: '지역공동체',
    scene_kr: '동네 할머니가 回覧板을 들고 현관 앞에 나타났다',
    scene_jp: '近所のおばあちゃんが回覧板を持って、玄関の前に現れた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: 'あのね、回覧板っていうのはね、昔からずっと続いている習慣でね。ご近所のみんなに回すのよ。',
    dialogue_kr: '있잖아, 回覧板이라는 건 옛날부터 계속 이어온 관습인데, 동네 모두에게 돌리는 거야.',
    vocab_word: '回覧板',
    vocab_reading: 'かいらんばん',
    vocab_meaning: '동네 소식을 이웃집에 순서대로 돌려보는 공지판',
    vocab_example_jp: '「回覧板を次の家に回す」(回覧板을 다음 집으로 돌리다) — 에도 시대부터 이어온 공지 방식으로, 마을 행사나 쓰레기 분리배출 규정 등을 전달합니다.',
    vocab_example_kr: '「한국과 비교」아파트 공지를 이메일이나 앱으로 받는 것과 달리, 일본 주택가에서는 종이 공지판을 이웃집에 직접 전달하는 것이 여전히 일반적입니다.',
    vocab_korea_compare: '한국 아파트의 카카오톡 단체방이나 앱 공지와 달리, 回覧板은 직접 이웃과 마주치게 되어 자연스럽게 커뮤니티를 형성하는 역할을 합니다.',
    expressions: [
      { japanese: '回覧板を回す', reading: 'かいらんばんをまわす', pronunciation: '카이란반오 마와스', korean: '회람판을 돌리다', example: '「次の家に回してください」다음 집에 전달해 주세요' },
      { japanese: 'ご近所', reading: 'ごきんじょ', pronunciation: '고킨죠', korean: '이웃, 근처', example: '「ご近所付き合い」이웃 사람들과의 교제' },
      { japanese: '習慣', reading: 'しゅうかん', pronunciation: '슈-칸', korean: '관습, 습관', example: '「昔からの習慣」옛날부터의 관습' },
    ],
    deeper_reading: '回覧板(かいらんばん)은 에도 시대부터 이어온 일본의 전통적인 공지 방식입니다. 町内会(ちょうないかい, 동네 자치회)가 운영하며, 쓰레기 분리수거 규정, 동네 행사, 방재 훈련 등을 알립니다. 디지털 시대에도 여전히 많은 지역에서 유지되고 있는 이유는, 이웃 간의 실제 접촉을 통해 커뮤니티를 유지하는 기능도 하기 때문입니다.',
  },
  {
    id: 'granny-03',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 3,
    tag: '쓰레기 분리수거',
    scene_kr: '처음으로 쓰레기를 내놓으러 갔다가 할머니한테 혼났다',
    scene_jp: '初めてゴミを出しに行ったら、おばあちゃんに注意された',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: 'あら、そこに出したらダメよ。燃えるゴミは火曜日と金曜日だけね。ちゃんと分別してね。',
    dialogue_kr: '어머, 거기다 버리면 안 돼. 타는 쓰레기는 화요일이랑 금요일만이야. 제대로 분리해야 해.',
    vocab_word: '分別',
    vocab_reading: 'ぶんべつ',
    vocab_meaning: '분리 (쓰레기 분리수거)',
    vocab_example_jp: '「ゴミの分別をしっかりしないと、収集してもらえません」쓰레기를 제대로 분별하지 않으면 수거해 가지 않습니다.',
    vocab_example_kr: '일본의 쓰레기 분별은 지역마다 규칙이 달라서, 이사 후 가장 먼저 파악해야 할 중요한 생활 정보입니다.',
    vocab_korea_compare: '한국은 종량제 봉투를 사용하지만, 일본은 시/구별로 다른 색깔 봉투와 요일제를 사용합니다. 규칙을 어기면 수거를 거부당할 수 있어요.',
    expressions: [
      { japanese: '燃えるゴミ', reading: 'もえるごみ', pronunciation: '모에루 고미', korean: '타는 쓰레기 (가연성 쓰레기)', example: '「燃えるゴミの日」타는 쓰레기 날' },
      { japanese: '分別する', reading: 'ぶんべつする', pronunciation: '분베쓰스루', korean: '분리하다', example: '「きちんと分別してください」제대로 분리해 주세요' },
      { japanese: '収集', reading: 'しゅうしゅう', pronunciation: '슈-슈-', korean: '수거', example: '「ゴミ収集の日」쓰레기 수거일' },
    ],
    deeper_reading: '일본의 ゴミ分別(쓰레기 분리)은 외국인이 가장 어려워하는 생활 규칙 중 하나입니다. 燃えるゴミ(가연성), 燃えないゴミ(불연성), 資源ゴミ(재활용), 粗大ゴミ(대형 폐기물)로 나뉘며, 각 지자체마다 수거 요일과 봉투 색깔이 다릅니다. 이사 후 구청(区役所)에서 쓰레기 분리 가이드를 받는 것이 중요합니다.',
  },
  {
    id: 'granny-04',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 4,
    tag: '자치회',
    scene_kr: '할머니가 봉투 하나를 들고 찾아와 자치회비를 내라고 했다',
    scene_jp: 'おばあちゃんが封筒を持ってきて、自治会費を払うように言った',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: '今月の自治会費なんですけど、よかったら加入してもらえませんか？地域のためになるんですよ。',
    dialogue_kr: '이번 달 자치회비인데요, 가입해주시겠어요? 지역을 위한 거예요.',
    vocab_word: '自治会費',
    vocab_reading: 'じちかいひ',
    vocab_meaning: '자치회비 (동네 자치회에 내는 회비)',
    vocab_example_jp: '「自治会費は月500円です」자치회비는 월 500엔입니다.',
    vocab_example_kr: '일본 주택가의 자치회(自治会)는 쓰레기 수거, 방재, 축제 등을 주민이 함께 운영하는 조직이에요.',
    vocab_korea_compare: '한국 아파트의 관리비에 해당하지만, 강제 가입이 아니라 임의 단체입니다. 그래도 지역 생활을 위해 가입하는 게 관행이에요.',
    expressions: [
      { japanese: '加入する', reading: 'かにゅうする', pronunciation: '카뉴-스루', korean: '가입하다', example: '「自治会に加入する」자치회에 가입하다' },
      { japanese: 'よかったら', reading: 'よかったら', pronunciation: '요캇타라', korean: '괜찮으시다면, 할 수 있으시면', example: '「よかったら一緒にどうぞ」괜찮으시다면 같이 어떠세요' },
      { japanese: '地域のため', reading: 'ちいきのため', pronunciation: '치이키노 타메', korean: '지역을 위해', example: '「地域のために働く」지역을 위해 일하다' },
    ],
    deeper_reading: '일본의 自治会(자치회) 또는 町内会(초나이카이)는 주민이 자발적으로 운영하는 지역 공동체 조직입니다. 쓰레기 수거일 공지, 지역 축제, 방재 훈련, 어린이 등하교 안전 등을 담당합니다. 외국인도 가입 가능하며, 지역에 녹아들고 싶다면 가입을 권장합니다.',
  },
  {
    id: 'granny-05',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 5,
    tag: '계절행사',
    scene_kr: '할머니가 동네 꽃놀이 행사에 초대해줬다',
    scene_jp: 'おばあちゃんが町内のお花見に誘ってくれた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: '来週の土曜日、公園でお花見するんだけど、よかったら一緒にどうぞ。手ぶらで来ていいわよ。',
    dialogue_kr: '다음 주 토요일에 공원에서 꽃놀이 하는데, 괜찮으시면 같이 오세요. 빈손으로 오셔도 돼요.',
    vocab_word: 'お花見',
    vocab_reading: 'おはなみ',
    vocab_meaning: '꽃놀이 (벚꽃을 보며 야외에서 음식을 먹는 행사)',
    vocab_example_jp: '「花見でお弁当を食べる」꽃놀이에서 도시락을 먹다',
    vocab_example_kr: '일본의 꽃놀이는 3~4월 벚꽃 시즌에 공원에서 자리를 깔고 음식을 먹는 국민 행사입니다.',
    vocab_korea_compare: '한국에서도 꽃놀이는 있지만, 일본의 お花見는 회사·동네 단위로도 열리며 자리 확보(場所取り)가 치열한 특별한 문화예요.',
    expressions: [
      { japanese: '手ぶらで来る', reading: 'てぶらでくる', pronunciation: '테부라데 쿠루', korean: '빈손으로 오다', example: '「手ぶらで来ていいよ」빈손으로 와도 돼' },
      { japanese: '一緒にどうぞ', reading: 'いっしょにどうぞ', pronunciation: '잇쇼니 도-조', korean: '같이 어떠세요 (초대 표현)', example: '「よかったら一緒にどうぞ」괜찮으시면 같이 오세요' },
      { japanese: '場所取り', reading: 'ばしょとり', pronunciation: '바쇼토리', korean: '자리 잡기', example: '「朝早く行って場所取りをする」아침 일찍 가서 자리를 잡다' },
    ],
    deeper_reading: 'お花見(꽃놀이)는 일본에서 봄을 알리는 가장 대표적인 행사입니다. 벚꽃 개화 예측(桜前線, さくらぜんせん)을 뉴스에서 매일 보도할 만큼 중요한 문화적 이벤트예요. 회사에서는 신입사원이 꽃놀이 자리 확보를 담당하는 관행도 있습니다.',
  },
  {
    id: 'granny-06',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 6,
    tag: '여름축제',
    scene_kr: '할머니가 여름 마을 축제에서 저를 알아보고 말을 걸었다',
    scene_jp: 'おばあちゃんが夏祭りで私を見つけて声をかけてくれた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: 'あら、浴衣を着てきたの？とっても似合ってるわよ。露店でなにか買った？',
    dialogue_kr: '어머, 유카타 입고 왔어요? 너무 잘 어울려요. 노점에서 뭐 샀어요?',
    vocab_word: '浴衣',
    vocab_reading: 'ゆかた',
    vocab_meaning: '유카타 (여름용 간편 기모노)',
    vocab_example_jp: '「夏祭りに浴衣で行く」여름 축제에 유카타를 입고 가다',
    vocab_example_kr: '유카타는 여름 축제나 불꽃놀이 때 입는 가벼운 기모노예요. 관광지 렌탈도 많습니다.',
    vocab_korea_compare: '한국의 한복을 행사 때 빌려 입는 것처럼, 일본에서도 여름 축제 전에 유카타 렌탈 가게가 붐빕니다.',
    expressions: [
      { japanese: '似合う', reading: 'にあう', pronunciation: '니아우', korean: '어울리다', example: '「とっても似合ってるね」너무 잘 어울려' },
      { japanese: '露店', reading: 'ろてん', pronunciation: '로텐', korean: '노점, 포장마차', example: '「露店でたこ焼きを買う」노점에서 타코야키를 사다' },
      { japanese: '夏祭り', reading: 'なつまつり', pronunciation: '나쓰 마쓰리', korean: '여름 축제', example: '「夏祭りに行く」여름 축제에 가다' },
    ],
    deeper_reading: '일본의 夏祭り(여름 축제)는 7~8월에 각 지역 신사나 공원에서 열립니다. 盆踊り(봉 오도리, 단체 춤), 花火大会(하나비 타이카이, 불꽃놀이), 金魚すくい(금붕어 잡기) 등이 대표 이벤트예요. 유카타를 입고 가족·연인과 함께 하는 여름의 핵심 문화입니다.',
  },
  {
    id: 'granny-07',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 7,
    tag: '방재훈련',
    scene_kr: '할머니가 방재 훈련 날이라며 같이 참가하자고 했다',
    scene_jp: 'おばあちゃんが防災訓練の日だと言って、一緒に参加しようと誘ってくれた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: '今日は防災訓練があるの。避難場所は公民館よ。いざという時のために覚えておいてね。',
    dialogue_kr: '오늘 방재 훈련이 있어요. 대피 장소는 공민관이에요. 만약을 위해 기억해 둬요.',
    vocab_word: '防災訓練',
    vocab_reading: 'ぼうさいくんれん',
    vocab_meaning: '방재 훈련 (재해 대비 훈련)',
    vocab_example_jp: '「年に一度の防災訓練に参加する」연 1회 방재 훈련에 참가하다',
    vocab_example_kr: '일본은 지진 다발 국가라 방재 훈련이 학교·직장·동네 단위로 정기적으로 열립니다.',
    vocab_korea_compare: '한국의 민방위 훈련과 비슷하지만, 일본은 실제 피난 경로 확인과 소화기 사용 실습까지 포함한 경우가 많아요.',
    expressions: [
      { japanese: '避難場所', reading: 'ひなんばしょ', pronunciation: '히난바쇼', korean: '대피 장소', example: '「最寄りの避難場所を確認する」가장 가까운 대피 장소를 확인하다' },
      { japanese: 'いざという時', reading: 'いざというとき', pronunciation: '이자토이우 토키', korean: '만약의 경우, 비상시', example: '「いざという時のために備える」만약의 경우를 위해 대비하다' },
      { japanese: '公民館', reading: 'こうみんかん', pronunciation: '코-민칸', korean: '공민관 (지역 공공 시설)', example: '「公民館で訓練をする」공민관에서 훈련을 하다' },
    ],
    deeper_reading: '일본에서는 9월 1일 関東大震災 기념일에 맞춰 防災の日(방재의 날)를 지정하고 전국적으로 훈련이 열립니다. 각 자치체는 ハザードマップ(재해 위험 지도)를 배포하며, 비상식량·음료·손전등 등 3일치 비상 키트 준비를 권장합니다.',
  },
  {
    id: 'granny-08',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 8,
    tag: '연말대청소',
    scene_kr: '할머니가 연말 대청소 날 복도 청소를 함께 하자고 했다',
    scene_jp: 'おばあちゃんが年末大掃除の日に廊下の掃除を一緒にしようと言ってくれた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: '年末の大掃除、一緒にやりましょうよ。共用部分はみんなで綺麗にするのよ。',
    dialogue_kr: '연말 대청소 같이 합시다. 공용 구역은 다 같이 청소하는 거예요.',
    vocab_word: '大掃除',
    vocab_reading: 'おおそうじ',
    vocab_meaning: '대청소',
    vocab_example_jp: '「年末に大掃除をする」연말에 대청소를 하다',
    vocab_example_kr: '일본의 大掃除는 단순한 청소가 아니라 한 해를 마무리하는 의례적 행위예요. 특히 12월 28일 전후가 피크입니다.',
    vocab_korea_compare: '한국도 연말 대청소 문화가 있지만, 일본은 한 해를 깨끗하게 마무리한다는 의미(年越し)가 강하게 담겨 있습니다.',
    expressions: [
      { japanese: '共用部分', reading: 'きょうようぶぶん', pronunciation: '쿄-요-부분', korean: '공용 구역', example: '「共用部分をきれいにする」공용 구역을 청소하다' },
      { japanese: '年越し', reading: 'としこし', pronunciation: '토시코시', korean: '해를 넘기다, 연말연시', example: '「きれいな家で年越しをする」깨끗한 집에서 해를 넘기다' },
      { japanese: '綺麗にする', reading: 'きれいにする', pronunciation: '키레이니 스루', korean: '깨끗하게 하다, 청소하다', example: '「部屋を綺麗にする」방을 깨끗이 하다' },
    ],
    deeper_reading: '일본에서 大掃除는 12월에 집과 직장을 청소하는 연례 행사입니다. 新年を気持ちよく迎える(기분 좋게 새해를 맞이한다)는 의미가 있어요. 직장에서는 仕事納め(시고토 오사메, 업무 마무리일)에 함께 청소를 하는 관행도 있습니다.',
  },
  {
    id: 'granny-09',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 9,
    tag: '택배·부재',
    scene_kr: '외출 중에 할머니가 내 택배를 대신 받아주셨다',
    scene_jp: '外出中におばあちゃんが宅配便を代わりに受け取ってくれた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: 'さっき宅配便が来たから、代わりに受け取っておいたわよ。玄関に置いてあるから。',
    dialogue_kr: '방금 택배가 왔길래 대신 받아뒀어요. 현관에 놔뒀으니까요.',
    vocab_word: '宅配便',
    vocab_reading: 'たくはいびん',
    vocab_meaning: '택배',
    vocab_example_jp: '「宅配便を受け取る」택배를 받다',
    vocab_example_kr: '일본의 대표 택배는 ヤマト運輸(야마토), 佐川急便(사가와), 日本郵便(일본우편). 부재 시 不在票(후자이효-) 안내서가 우편함에 들어옵니다.',
    vocab_korea_compare: '한국처럼 경비실이 없는 주택가에서는 이웃이 대신 받아주는 문화가 있어요. 이런 관계가 생기면 진정한 ご近所さん입니다.',
    expressions: [
      { japanese: '代わりに', reading: 'かわりに', pronunciation: '카와리니', korean: '대신에', example: '「代わりに受け取る」대신 받다' },
      { japanese: '受け取る', reading: 'うけとる', pronunciation: '우케토루', korean: '수령하다, 받다', example: '「荷物を受け取る」짐을 받다' },
      { japanese: '置いておく', reading: 'おいておく', pronunciation: '오이테오쿠', korean: '두다, 보관해두다', example: '「玄関に置いておきます」현관에 둘게요' },
    ],
    deeper_reading: '일본의 택배 문화에서 再配達(재배달) 신청은 전화나 앱으로 할 수 있습니다. 하지만 환경 부담을 이유로 정부가 再配達削減(재배달 감축) 정책을 추진 중이에요. 택배함(宅配ボックス) 설치가 빠르게 늘고 있는 이유이기도 합니다.',
  },
  {
    id: 'granny-10',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 10,
    tag: '이웃소개',
    scene_kr: '새 이웃이 이사 와서 할머니가 나에게 소개해줬다',
    scene_jp: '新しい隣人が引っ越してきて、おばあちゃんが私に紹介してくれた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: 'こちら、先月引っ越してきた山田さんよ。同じ外国出身なんですって。仲良くしてあげてね。',
    dialogue_kr: '이쪽은 지난 달에 이사 오신 야마다 씨예요. 같은 외국 출신이래요. 잘 지내줘요.',
    vocab_word: '仲良くする',
    vocab_reading: 'なかよくする',
    vocab_meaning: '사이좋게 지내다, 친하게 지내다',
    vocab_example_jp: '「隣の人と仲良くする」옆집 사람과 사이좋게 지내다',
    vocab_example_kr: '일본 문화에서 "仲良くしてあげてね"는 상대방에 대한 배려와 환영의 표현이에요.',
    vocab_korea_compare: '한국의 "잘 챙겨줘"와 비슷한 뉘앙스이지만, 일본은 직접적인 부탁보다는 부드러운 권유 표현을 씁니다.',
    expressions: [
      { japanese: '先月', reading: 'せんげつ', pronunciation: '센게쓰', korean: '지난 달', example: '「先月引っ越してきた」지난 달에 이사 왔다' },
      { japanese: '出身', reading: 'しゅっしん', pronunciation: '슷신', korean: '출신', example: '「どちらのご出身ですか」어디 출신이세요?' },
      { japanese: '仲良くする', reading: 'なかよくする', pronunciation: '나카요쿠 스루', korean: '사이좋게 지내다', example: '「ぜひ仲良くしてください」꼭 친하게 지내주세요' },
    ],
    deeper_reading: '일본에서 이웃 소개는 드문 편이지만, 오랜 주민(특히 할머니)이 중간 역할을 해주는 경우가 있습니다. 외국인 거주자가 늘면서 국제화된 주택가도 많아졌어요. 같은 외국 출신 이웃을 만나는 것은 일본 생활의 든든한 연결망이 됩니다.',
  },
  {
    id: 'granny-11',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 11,
    tag: '설날인사',
    scene_kr: '새해 첫날 아침, 현관에서 할머니가 새해 인사를 건넸다',
    scene_jp: '元旦の朝、玄関でおばあちゃんが新年の挨拶をしてくれた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: 'あけましておめでとうございます。今年もよろしくお願いしますね。良いお年になりますように。',
    dialogue_kr: '새해 복 많이 받으세요. 올해도 잘 부탁드려요. 좋은 한 해가 되길 바랍니다.',
    vocab_word: 'あけましておめでとうございます',
    vocab_reading: 'あけましておめでとうございます',
    vocab_meaning: '새해 복 많이 받으세요 (새해 인사)',
    vocab_example_jp: '「あけましておめでとうございます。今年もよろしくお願いします」새해 복 많이 받으세요. 올해도 잘 부탁드립니다.',
    vocab_example_kr: '일본의 새해 인사는 1월 7일(松の内) 이전까지만 사용하고, 그 이후에는 「今年もよろしくお願いします」만 씁니다.',
    vocab_korea_compare: '한국의 "새해 복 많이 받으세요"와 거의 동일하지만, 일본은 기간이 지나면 쓰지 않는 엄격한 관습이 있습니다.',
    expressions: [
      { japanese: 'あけましておめでとうございます', reading: 'あけましておめでとうございます', pronunciation: '아케마시테 오메데토- 고자이마스', korean: '새해 복 많이 받으세요', example: '1월 7일 이전에만 사용' },
      { japanese: '今年もよろしくお願いします', reading: 'ことしもよろしくおねがいします', pronunciation: '코토시모 요로시쿠 오네가이시마스', korean: '올해도 잘 부탁드립니다', example: '새해 인사의 세트 표현' },
      { japanese: '良いお年を', reading: 'よいおとしを', pronunciation: '요이 오토시오', korean: '좋은 한 해 되세요', example: '연말(12월)에 쓰는 인사, 새해에는 쓰지 않음' },
    ],
    deeper_reading: '일본의 お正月(오쇼가쓰, 설날)는 1월 1~3일이 가장 중요한 명절입니다. 神社(신사)에서 初詣(하쓰모-데, 새해 첫 참배)를 하고, 家族(가족)이 모여 おせち料理(오세치 요리)를 먹습니다. 새해 카드인 年賀状(넨가죠-)를 1월 1일에 맞춰 보내는 문화도 있어요.',
  },
  {
    id: 'granny-12',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 12,
    tag: '음식나누기',
    scene_kr: '할머니가 직접 만든 おはぎ를 너무 많이 만들었다며 가져왔다',
    scene_jp: 'おばあちゃんが手作りのおはぎを多く作りすぎたといって持ってきてくれた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: 'ちょっと多く作りすぎてしまって。よかったらどうぞ。口に合うといいんだけど。',
    dialogue_kr: '좀 많이 만들어버려서요. 괜찮으시면 받으세요. 입에 맞으면 좋겠는데.',
    vocab_word: 'おすそ分け',
    vocab_reading: 'おすそわけ',
    vocab_meaning: '음식·물건을 이웃과 나누는 것',
    vocab_example_jp: '「おすそ分けをする」나누어 드리다 — 일본에서는 선물 받은 것이나 직접 만든 음식을 이웃과 나누는 것이 미덕입니다.',
    vocab_example_kr: '받을 때는 바로 먹어보고 「おいしかったです」라고 감상을 전하는 것이 예의예요.',
    vocab_korea_compare: '한국의 "음식 많이 만들었는데 드세요"와 완전히 같은 문화! 받은 사람은 나중에 お返し(답례)를 하거나 용기를 돌려주는 게 일반적입니다.',
    expressions: [
      { japanese: 'おすそ分け', reading: 'おすそわけ', pronunciation: '오스소와케', korean: '나눔, 이웃과 나누기', example: '「おすそ分けです」나누어 드리는 거예요' },
      { japanese: 'よかったらどうぞ', reading: 'よかったらどうぞ', pronunciation: '요캇타라 도-조', korean: '괜찮으시면 받으세요', example: '물건을 줄 때 가장 자주 쓰는 표현' },
      { japanese: '口に合う', reading: 'くちにあう', pronunciation: '쿠치니 아우', korean: '입에 맞다', example: '「口に合うといいんですが」입에 맞으면 좋겠는데요' },
    ],
    deeper_reading: 'おすそ分け(음식 나눔) 문화는 일본 이웃 관계의 핵심입니다. 여행에서 사온 과자, 직접 키운 채소, 명절 음식 등을 이웃과 나누는 것이 일반적이에요. 받은 뒤에는 반드시 容器(용기)를 깨끗이 씻어 돌려주고, 小さなお返し(작은 답례)를 하는 것이 예의입니다.',
  },
  {
    id: 'granny-13',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 13,
    tag: '언어장벽',
    scene_kr: '할머니 말이 너무 빨라서 알아듣지 못했다',
    scene_jp: 'おばあちゃんの話が早すぎて聞き取れなかった',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: 'あら、ごめんなさいね。もうちょっとゆっくり話せばよかったわね。もう一度言いましょうか？',
    dialogue_kr: '어머, 미안해요. 좀 더 천천히 말할걸 그랬네. 한 번 더 말해줄까요?',
    vocab_word: '聞き取れない',
    vocab_reading: 'ききとれない',
    vocab_meaning: '못 알아듣다 (청취가 안 되다)',
    vocab_example_jp: '「すみません、聞き取れませんでした。もう一度お願いできますか」죄송한데 못 알아들었어요. 한 번 더 부탁드릴 수 있을까요?',
    vocab_example_kr: '일본어를 잘 못 알아들을 때 솔직하게 말하는 것이 오히려 관계를 부드럽게 합니다.',
    vocab_korea_compare: '한국에서 못 알아들으면 그냥 넘어가는 경우도 있지만, 일본에서는 정확한 의사소통을 위해 「もう一度」를 부담없이 요청하는 문화가 있어요.',
    expressions: [
      { japanese: 'もう一度お願いします', reading: 'もういちどおねがいします', pronunciation: '모- 이치도 오네가이시마스', korean: '한 번 더 부탁드립니다', example: '가장 기본적인 재요청 표현' },
      { japanese: 'ゆっくり話してください', reading: 'ゆっくりはなしてください', pronunciation: '윳쿠리 하나시테 쿠다사이', korean: '천천히 말씀해 주세요', example: '「もう少しゆっくり話してもらえますか」조금 더 천천히 말해주실 수 있어요?' },
      { japanese: '日本語があまり得意じゃない', reading: 'にほんごがあまりとくいじゃない', pronunciation: '니혼고가 아마리 토쿠이쟈나이', korean: '일본어가 그다지 잘 못 한다', example: '「まだ日本語が得意じゃないので」아직 일본어가 잘 안 돼서요' },
    ],
    deeper_reading: '일본어는 방언(方言)이 매우 다양해서 도쿄 표준어 외에 칸사이벤(関西弁), 도호쿠벤(東北弁) 등을 처음 들으면 알아듣기 어렵습니다. 외국인임을 밝히면 대부분의 일본인은 친절하게 쉬운 말로 바꿔 말해줍니다. 「外国人なので」(외국인이라서)라고 한 마디 하는 것만으로도 큰 도움이 됩니다.',
  },
  {
    id: 'granny-14',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 14,
    tag: '날씨인사',
    scene_kr: '우체통 앞에서 할머니를 만났는데 날씨 이야기로 대화가 시작됐다',
    scene_jp: '郵便受けの前でおばあちゃんに会い、天気の話から会話が始まった',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: '今日は本当に蒸し暑いわね。夕方には雨が降るそうよ。洗濯物、取り込んだほうがいいかもね。',
    dialogue_kr: '오늘은 진짜 무덥네요. 저녁에 비가 온대요. 빨래 거둬들이는 게 좋을 것 같아요.',
    vocab_word: '蒸し暑い',
    vocab_reading: 'むしあつい',
    vocab_meaning: '무덥다, 후텁지근하다',
    vocab_example_jp: '「今日は蒸し暑くて大変ですね」오늘은 무더워서 힘드네요',
    vocab_example_kr: '일본의 여름은 습도가 매우 높아서 蒸し暑い(무더운) 표현을 자주 씁니다. 한국보다 체감 온도가 훨씬 높아요.',
    vocab_korea_compare: '한국의 "찜통더위"와 비슷한 뜻! 일본에서 날씨 이야기는 가장 쉬운 소통의 첫 걸음이에요. 한국과 마찬가지로 날씨 인사가 대화의 물꼬를 틉니다.',
    expressions: [
      { japanese: '蒸し暑い', reading: 'むしあつい', pronunciation: '무시아쓰이', korean: '무덥다, 후텁지근하다', example: '「今日は蒸し暑いですね」오늘은 무덥네요' },
      { japanese: '洗濯物を取り込む', reading: 'せんたくものをとりこむ', pronunciation: '센타쿠모노오 토리코무', korean: '빨래를 거둬들이다', example: '「雨が降る前に洗濯物を取り込む」비 오기 전에 빨래 거둬들이다' },
      { japanese: '夕立', reading: 'ゆうだち', pronunciation: '유-다치', korean: '소나기 (저녁 무렵 갑자기 내리는 비)', example: '「夕立が来そうだ」소나기가 올 것 같다' },
    ],
    deeper_reading: '일본에서 날씨 인사(天気の挨拶)는 가장 일반적인 소통 방식입니다. 「いいお天気ですね」(좋은 날씨네요), 「暑いですね」(덥네요), 「寒くなりましたね」(추워졌네요) 같은 표현으로 대화를 시작하는 것은 한국과 매우 유사합니다. 일본은 四季(사계절)가 뚜렷해서 계절마다 날씨 관련 인사가 다양합니다.',
  },
  {
    id: 'granny-15',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 15,
    tag: '겸손표현',
    scene_kr: '할머니가 내 아이를 보고 예쁘다고 칭찬했다',
    scene_jp: 'おばあちゃんが私の子どもを見てかわいいと褒めてくれた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: 'まあ、お子さんかわいいわね。利発そうで。きっとお母さん似ね。',
    dialogue_kr: '어머, 아이가 너무 귀엽네요. 영리해 보이고. 분명 엄마 닮았을 거예요.',
    vocab_word: '謙遜',
    vocab_reading: 'けんそん',
    vocab_meaning: '겸손 (칭찬을 받았을 때 낮추는 일본 문화)',
    vocab_example_jp: '「いいえ、まだまだです」(아직 멀었어요) — 칭찬받을 때 겸손하게 부정하는 것이 일본 예의입니다.',
    vocab_example_kr: '"감사합니다"라고 직접 받으면 실례가 될 수 있어요. 「おかげさまで」(덕분에요) 같은 겸손한 표현을 쓰세요.',
    vocab_korea_compare: '한국에서는 칭찬에 "감사합니다"가 자연스럽지만, 일본에서는 「とんでもないです」(별말씀을요) 같이 겸손하게 받는 것이 더 자연스럽습니다.',
    expressions: [
      { japanese: 'とんでもないです', reading: 'とんでもないです', pronunciation: '톤데모나이데스', korean: '별말씀을요, 천만에요', example: '칭찬받을 때 겸손한 답변으로 사용' },
      { japanese: 'おかげさまで', reading: 'おかげさまで', pronunciation: '오카게사마데', korean: '덕분에 (겸손한 감사 표현)', example: '「おかげさまで元気にしています」덕분에 잘 지내고 있어요' },
      { japanese: 'まだまだです', reading: 'まだまだです', pronunciation: '마다마다데스', korean: '아직 멀었어요, 부족해요', example: '기술이나 능력을 칭찬받았을 때' },
    ],
    deeper_reading: '일본의 謙遜(겸손) 문화는 외국인에게 가장 적응하기 어려운 문화 중 하나입니다. 자녀 칭찬에 「うちの子なんて全然ダメで」(우리 아이는 아직 많이 부족해서)라고 답하는 것이 일반적이에요. 이것은 솔직함이 아니라 문화적 예의입니다. 상대방의 칭찬을 그대로 받으면 자만한다는 인상을 줄 수 있어요.',
  },
  {
    id: 'granny-16',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 16,
    tag: '반상회',
    scene_kr: '할머니(반장)가 이번 달 반상회 날짜를 알려주러 왔다',
    scene_jp: '班長のおばあちゃんが今月の班会議の日程を知らせに来た',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: '来週の水曜日、夜7時から班会議があります。なるべく参加してもらえると助かります。',
    dialogue_kr: '다음 주 수요일 저녁 7시부터 반상회가 있어요. 가능하면 참석해 주시면 좋겠어요.',
    vocab_word: '班長',
    vocab_reading: 'はんちょう',
    vocab_meaning: '반장 (동네 자치 단위의 대표)',
    vocab_example_jp: '「班長さんが回覧板を持ってきた」반장님이 회람판을 가지고 왔다',
    vocab_example_kr: '자치회의 소규모 단위인 班(반)을 이끄는 役割(역할)로, 주로 오래 거주한 주민이 맡습니다.',
    vocab_korea_compare: '한국 아파트의 동대표·통장과 비슷한 역할이에요. 참석하면 지역 정보를 얻고 이웃과 친해지는 좋은 기회가 됩니다.',
    expressions: [
      { japanese: 'なるべく', reading: 'なるべく', pronunciation: '나루베쿠', korean: '가능한 한, 되도록', example: '「なるべく参加してください」가능한 한 참석해 주세요' },
      { japanese: '参加する', reading: 'さんかする', pronunciation: '산카스루', korean: '참가하다', example: '「会議に参加する」회의에 참가하다' },
      { japanese: '欠席する', reading: 'けっせきする', pronunciation: '켓세키스루', korean: '결석하다, 불참하다', example: '「今回は欠席します」이번에는 불참합니다' },
    ],
    deeper_reading: '日本の班会議(반상회)는 쓰레기 배출 규칙, 마을 행사 준비, 방범 등을 주민이 직접 논의하는 자리입니다. 외국인은 참석이 부담스러울 수 있지만, 적극적으로 참여하면 지역 정보를 가장 빨리 얻을 수 있고 이웃과의 신뢰도 쌓입니다. 언어가 부족해도 참석 자체가 성의 표시가 됩니다.',
  },
  {
    id: 'granny-17',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 17,
    tag: '여름문안',
    scene_kr: '할머니가 暑中見舞いのはがき를 쓰다가 일본의 안부 엽서 문화를 설명해줬다',
    scene_jp: 'おばあちゃんが暑中見舞いのはがきを書きながら、日本の挨拶状文化を説明してくれた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: '日本では夏と年末に、知り合いへはがきを出す習慣があるのよ。暑中見舞いと年賀状っていうんだけど。',
    dialogue_kr: '일본에서는 여름이랑 연말에 아는 사람한테 엽서를 보내는 관습이 있어요. 暑中見舞い랑 年賀状이라고 해요.',
    vocab_word: '暑中見舞い',
    vocab_reading: 'しょちゅうみまい',
    vocab_meaning: '여름 안부 엽서 (7월 초~8월 초)',
    vocab_example_jp: '「暑中見舞いを出す」여름 안부 엽서를 보내다',
    vocab_example_kr: '입추(8월 7일경) 이후에는 残暑見舞い(잔더위 안부)라고 이름이 바뀝니다.',
    vocab_korea_compare: '한국에는 없는 문화지만, 일본에서 비즈니스 관계를 유지하려면 챙기면 좋습니다. 요즘은 디지털 카드로 대체하는 경우도 많아졌어요.',
    expressions: [
      { japanese: '暑中見舞い', reading: 'しょちゅうみまい', pronunciation: '쇼츄- 미마이', korean: '여름 안부 (인사)', example: '7월 초~입추 전까지 보내는 안부 엽서' },
      { japanese: '年賀状', reading: 'ねんがじょう', pronunciation: '넨가죠-', korean: '연하장 (새해 엽서)', example: '1월 1일 도착하도록 12월 중순에 보냄' },
      { japanese: 'はがき', reading: 'はがき', pronunciation: '하가키', korean: '엽서, 우편엽서', example: '「はがきを出す」엽서를 보내다' },
    ],
    deeper_reading: '일본의 안부 엽서 문화는 이미 쇠퇴하고 있지만, 비즈니스와 장년층 사이에서는 여전히 중요합니다. 年賀状(넨가죠-)는 일본우편이 특별히 지정일에 배달해주는 서비스가 있을 만큼 국민적 행사예요. 요즘은 LINE이나 SNS로 대체되는 추세이지만, 어른 세대에게는 여전히 소중한 소통 방식입니다.',
  },
  {
    id: 'granny-18',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 18,
    tag: '집수리문의',
    scene_kr: '수도꼭지에서 이상한 소리가 나서 할머니에게 상담했다',
    scene_jp: '蛇口から変な音がして、おばあちゃんに相談した',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: 'それは管理会社に連絡したほうがいいわよ。緊急の場合は夜でも電話できるから、遠慮しないで。',
    dialogue_kr: '그건 관리 회사에 연락하는 게 좋아요. 급한 경우에는 밤에도 전화할 수 있으니까, 망설이지 말고요.',
    vocab_word: '管理会社',
    vocab_reading: 'かんりがいしゃ',
    vocab_meaning: '관리 회사 (부동산 관리업체)',
    vocab_example_jp: '「管理会社に修理を依頼する」관리 회사에 수리를 의뢰하다',
    vocab_example_kr: '일본에서는 집에 문제가 생기면 집주인(大家さん, 오야상)이 아닌 管理会社에 연락하는 것이 일반적입니다.',
    vocab_korea_compare: '한국의 부동산 관리 사무소와 비슷한 역할. 일본은 집 수리 책임이 계약서에 명확히 규정되어 있어, 무엇을 누구에게 연락해야 하는지 파악해 두는 것이 중요합니다.',
    expressions: [
      { japanese: '修理を依頼する', reading: 'しゅうりをいらいする', pronunciation: '슈-리오 이라이스루', korean: '수리를 의뢰하다', example: '「管理会社に修理を依頼する」관리 회사에 수리 의뢰하다' },
      { japanese: '水漏れ', reading: 'みずもれ', pronunciation: '미즈모레', korean: '물 누수', example: '「水漏れが起きた」누수가 생겼다' },
      { japanese: '故障', reading: 'こしょう', pronunciation: '코쇼-', korean: '고장', example: '「エアコンが故障した」에어컨이 고장났다' },
    ],
    deeper_reading: '일본에서 집에 문제가 생겼을 때 연락처를 미리 파악해 두는 것이 중요합니다. 賃貸契約書(임대차 계약서)에 緊急連絡先(긴급 연락처)가 기재되어 있습니다. 水道(수도)·ガス(가스)·電気(전기) 각각 별도의 회사에 연락해야 하는 경우도 있으니, 입주 시 정리해 두면 좋습니다.',
  },
  {
    id: 'granny-19',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 19,
    tag: '자전거규칙',
    scene_kr: '자전거를 세워뒀다가 할머니한테 여기는 주차 금지 구역이라고 들었다',
    scene_jp: '自転車を止めたら、おばあちゃんにここは駐輪禁止だと教えてもらった',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: 'あのね、ここは駐輪禁止なのよ。ちゃんと駐輪場に止めないと撤去されちゃうから気をつけてね。',
    dialogue_kr: '있잖아, 여기는 자전거 주차 금지야. 제대로 자전거 주차장에 세워야 해, 안 그러면 견인당하니까 조심해요.',
    vocab_word: '駐輪禁止',
    vocab_reading: 'ちゅうりんきんし',
    vocab_meaning: '자전거 주차 금지',
    vocab_example_jp: '「駐輪禁止の場所に止めると撤去される」자전거 주차 금지 장소에 세우면 견인됩니다.',
    vocab_example_kr: '일본에서 자전거는 매우 엄격하게 관리됩니다. 방치 자전거(放置自転車)는 정기적으로 撤去(견인)되어, 찾으러 가면 수수료를 내야 합니다.',
    vocab_korea_compare: '한국보다 자전거 주차 규제가 훨씬 엄격합니다. 역 주변이나 상점가 앞은 특히 주의! 지정 駐輪場(주차장)을 확인하는 습관이 필요합니다.',
    expressions: [
      { japanese: '撤去される', reading: 'てっきょされる', pronunciation: '텟쿄 사레루', korean: '견인되다, 철거되다', example: '「自転車が撤去された」자전거가 견인됐다' },
      { japanese: '駐輪場', reading: 'ちゅうりんじょう', pronunciation: '추-린죠-', korean: '자전거 주차장', example: '「駐輪場に止める」자전거 주차장에 세우다' },
      { japanese: '放置自転車', reading: 'ほうちじてんしゃ', pronunciation: '호-치 지텐샤', korean: '방치 자전거', example: '「放置自転車は撤去の対象」방치 자전거는 견인 대상' },
    ],
    deeper_reading: '일본에서 자전거(自転車)는 매우 편리한 이동 수단이지만, 규칙이 엄격합니다. 인도에서 자전거를 타는 것도 일정 조건에서만 허용되고, 스마트폰을 보면서 타거나 우산을 펼치고 타는 것은 違反(위반)입니다. 또한 자동차와 마찬가지로 음주 운전도 처벌 대상이에요.',
  },
  {
    id: 'granny-20',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 20,
    tag: '동네운동회',
    scene_kr: '할머니가 동네 운동회에 초대했다. 외국인도 환영이라고 했다',
    scene_jp: 'おばあちゃんが地域の運動会に誘ってくれた。外国の人も大歓迎だと言っていた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: '来月、地域の運動会があるのよ。お子さん連れで来てね。外国の方も大歓迎よ。',
    dialogue_kr: '다음 달에 지역 운동회가 있어요. 아이 데리고 오세요. 외국 분들도 대환영이에요.',
    vocab_word: '運動会',
    vocab_reading: 'うんどうかい',
    vocab_meaning: '운동회',
    vocab_example_jp: '「地域の運動会に参加する」지역 운동회에 참가하다',
    vocab_example_kr: '일본의 지역 운동회는 학교 운동회와 별도로, 자치회가 주최하는 주민 참여형 행사입니다.',
    vocab_korea_compare: '한국의 동네 체육대회와 비슷! 가족 단위로 참가하며, 이웃과 친해지는 가장 좋은 기회 중 하나입니다. 외국인 가족도 적극 환영하는 분위기예요.',
    expressions: [
      { japanese: '大歓迎', reading: 'だいかんげい', pronunciation: '다이칸게이', korean: '대환영', example: '「どなたでも大歓迎です」누구든지 대환영입니다' },
      { japanese: '子ども連れ', reading: 'こどもづれ', pronunciation: '코도모즈레', korean: '아이를 데리고', example: '「子ども連れで参加する」아이를 데리고 참가하다' },
      { japanese: '地域の行事', reading: 'ちいきのぎょうじ', pronunciation: '치이키노 교-지', korean: '지역 행사', example: '「地域の行事に積極的に参加する」지역 행사에 적극적으로 참가하다' },
    ],
    deeper_reading: '일본의 地域行事(지역 행사)는 주민 간의 絆(키즈나, 유대감)를 강화하는 중요한 문화입니다. 運動会 외에도 盆踊り(봉오도리), 文化祭(문화제), 餅つき(모치쓰키, 떡 찧기) 등 다양한 행사가 있어요. 외국인이라서 소극적으로 있으면 지역에 녹아들기 어렵습니다. 한 번 용기 내어 참가하면 이웃과의 관계가 크게 달라집니다.',
  },
  {
    id: 'granny-21',
    series_id: 'granny',
    series_name_jp: '隣のおばあちゃんトーク',
    series_name_kr: '이웃 할머니 토크',
    number: 21,
    tag: '이사작별',
    scene_kr: '드디어 이사를 가게 됐다. 할머니가 소식을 듣고 작별 인사를 하러 왔다',
    scene_jp: 'とうとう引っ越すことになった。おばあちゃんが知らせを聞いてお別れの挨拶に来てくれた',
    character_name_jp: 'おばあちゃん',
    character_name_kr: '이웃 할머니',
    character_emoji: '👵',
    dialogue_jp: 'お引越しされるって聞いて、寂しくなるわね。新しい場所でも元気でいてね。どうかお体に気をつけて。',
    dialogue_kr: '이사 가신다고 들었어요. 섭섭해지겠네요. 새로운 곳에서도 건강하게 지내요. 부디 몸 조심하고요.',
    vocab_word: '名残惜しい',
    vocab_reading: 'なごりおしい',
    vocab_meaning: '아쉽다, 헤어지기 섭섭하다',
    vocab_example_jp: '「名残惜しいですが、お元気で」아쉽지만, 건강하세요',
    vocab_example_kr: '이사할 때 이웃에게 인사를 잘 하는 것도 일본 문화의 중요한 부분입니다.',
    vocab_korea_compare: '한국의 "섭섭해요"와 비슷한 뉘앙스. 일본에서는 이사 갈 때도 이웃에게 작은 선물을 들고 인사를 다니는 문화가 있어요.',
    expressions: [
      { japanese: 'お元気で', reading: 'おげんきで', pronunciation: '오겐키데', korean: '건강하세요 (작별 인사)', example: '「どうかお元気で」부디 건강하세요' },
      { japanese: 'お世話になりました', reading: 'おせわになりました', pronunciation: '오세와니 나리마시타', korean: '신세 많이 졌습니다', example: '「長い間お世話になりました」오랫동안 신세 많이 졌습니다' },
      { japanese: 'またいつか', reading: 'またいつか', pronunciation: '마타 이쓰카', korean: '언젠가 또 (만나요)', example: '「またいつか会いましょう」언젠가 또 만나요' },
    ],
    deeper_reading: '이사할 때의 挨拶(이사 인사)는 일본에서 매우 중요합니다. 引っ越し当日(이사 당일)이나 전날, 근처 집들에 타월이나 과자 등 작은 선물을 들고 인사하는 것이 예의입니다. 「お世話になりました。お引越しします」(신세 많이 졌습니다. 이사 가게 됐습니다)라는 한 마디가 이웃과의 마지막 인상을 좋게 남깁니다.',
  },
]

export const SERIES_LIST = [
  {
    id: 'granny',
    name_jp: '隣のおばあちゃんトーク',
    name_kr: '이웃 할머니 토크',
    description: '일본 주택가의 이웃 할머니에게 배우는 진짜 생활 일본어',
    emoji: '👵',
    total: 21,
    available: 21,
    tag: '지역공동체',
  },
  {
    id: 'office',
    name_jp: 'オフィスの日本語',
    name_kr: '직장 일본어',
    description: '일본 직장에서 살아남는 경어·보고·사과 표현 총정리',
    emoji: '💼',
    total: 10,
    available: 10,
    tag: '직장',
  },
  {
    id: 'hospital',
    name_jp: '病院の日本語',
    name_kr: '병원 일본어',
    description: '증상 설명부터 처방전까지, 일본 병원에서 필요한 표현',
    emoji: '🏥',
    total: 5,
    available: 5,
    tag: '병원',
  },
  {
    id: 'shopping',
    name_jp: 'お買い物の日本語',
    name_kr: '쇼핑 일본어',
    description: '슈퍼·편의점·드럭스토어에서 쓰는 진짜 쇼핑 표현',
    emoji: '🛒',
    total: 5,
    available: 5,
    tag: '쇼핑',
  },
  {
    id: 'nursery',
    name_jp: '保育園の日本語',
    name_kr: '육아·보육 일본어',
    description: '등원부터 연락장·운동회까지, 어린이집에서 꼭 필요한 표현',
    emoji: '🧒',
    total: 5,
    available: 5,
    tag: '육아',
  },
  {
    id: 'nativelike',
    name_jp: '現地人みたいに話そう',
    name_kr: '현지인처럼 말하기',
    description: '문법은 맞는데 왠지 어색한 표현들, 일본인이 실제로 쓰는 자연스러운 말투로 교정',
    emoji: '🗣️',
    total: 10,
    available: 10,
    tag: '자연스러운 표현',
  },
]

export const OFFICE_EPISODES: Episode[] = [
  {
    id: 'office-01',
    series_id: 'office',
    series_name_jp: 'オフィスの日本語',
    series_name_kr: '직장 일본어',
    number: 1,
    tag: '첫출근인사',
    scene_kr: '입사 첫날, 팀 앞에서 자기소개를 해야 한다',
    scene_jp: '入社初日、チームの前で自己紹介をしなければならない',
    character_name_jp: '田中課長',
    character_name_kr: '다나카 과장',
    character_emoji: '👔',
    dialogue_jp: 'では、新しく入られた方に自己紹介をしていただきましょう。',
    dialogue_kr: '그럼, 새로 입사하신 분께 자기소개를 부탁드리겠습니다.',
    vocab_word: '自己紹介',
    vocab_reading: 'じこしょうかい',
    vocab_meaning: '자기소개',
    vocab_example_jp: '「本日入社いたしました○○と申します。どうぞよろしくお願いいたします。」오늘 입사한 ○○라고 합니다. 잘 부탁드립니다.',
    vocab_example_kr: '첫 인사에서는 출신지나 취미보다 "열심히 하겠습니다"는 의지 표현이 중요합니다.',
    vocab_korea_compare: '한국의 "잘 부탁드립니다"와 같지만, 일본은 「よろしくお願いいたします」라는 격식체를 반드시 씁니다.',
    expressions: [
      { japanese: '本日よりお世話になります', reading: 'ほんじつよりおせわになります', pronunciation: '혼지쓰 요리 오세와니 나리마스', korean: '오늘부터 신세 지겠습니다', example: '입사 첫날 인사의 시작 문구' },
      { japanese: '○○と申します', reading: '○○ともうします', pronunciation: '○○토 모-시마스', korean: '○○라고 합니다 (겸손한 자기소개)', example: '이름을 말할 때 "申す"는 가장 격식체' },
      { japanese: 'ご指導のほどよろしくお願いいたします', reading: 'ごしどうのほどよろしくおねがいいたします', pronunciation: '고시도-노 호도 요로시쿠 오네가이이타시마스', korean: '지도 편달 부탁드립니다', example: '직장 첫인사의 마무리 표현' },
    ],
    deeper_reading: '일본 직장 문화에서 첫인사는 매우 중요합니다. 「本日よりお世話になります」로 시작해 이름, 전 직장 또는 출신, 의욕을 간단히 말한 뒤 「ご指導のほどよろしくお願いいたします」로 마무리하는 것이 기본 형식입니다. 너무 길면 오히려 인상이 좋지 않으니 30초 이내로 간결하게 하세요.',
  },
  {
    id: 'office-02',
    series_id: 'office',
    series_name_jp: 'オフィスの日本語',
    series_name_kr: '직장 일본어',
    number: 2,
    tag: '경어기초',
    scene_kr: '선배가 "그거 존댓말이 아닌 것 같은데"라고 조용히 알려줬다',
    scene_jp: '先輩が「それは敬語じゃないと思うけど」と静かに教えてくれた',
    character_name_jp: '鈴木先輩',
    character_name_kr: '스즈키 선배',
    character_emoji: '🧑‍💼',
    dialogue_jp: '「了解です」より「承知いたしました」の方がいいよ。上司には特に気をつけてね。',
    dialogue_kr: '"알겠습니다"보다 "承知いたしました"가 좋아. 상사한테는 특히 조심해.',
    vocab_word: '承知いたしました',
    vocab_reading: 'しょうちいたしました',
    vocab_meaning: '알겠습니다 (가장 정중한 표현)',
    vocab_example_jp: '上司から指示を受けたとき→「承知いたしました。すぐに対応いたします。」상사 지시 후 → "알겠습니다. 바로 처리하겠습니다."',
    vocab_example_kr: '「了解です」는 동료나 후배에게, 「承知いたしました」는 상사·고객에게 씁니다. 혼용하면 실례가 될 수 있어요.',
    vocab_korea_compare: '한국에서 "알겠습니다"는 상하 모두 쓰지만, 일본은 상대에 따라 표현이 완전히 달라집니다. 직장 일본어에서 가장 먼저 익혀야 할 포인트입니다.',
    expressions: [
      { japanese: '承知いたしました', reading: 'しょうちいたしました', pronunciation: '쇼-치 이타시마시타', korean: '알겠습니다 (상사·고객께)', example: '가장 격식 있는 "알겠다" 표현' },
      { japanese: '了解です', reading: 'りょうかいです', pronunciation: '료-카이 데스', korean: '알겠어요 (동료·후배에게)', example: '상사에게 쓰면 실례가 될 수 있음' },
      { japanese: 'かしこまりました', reading: 'かしこまりました', pronunciation: '카시코마리마시타', korean: '알겠습니다 (접객·격식 장면)', example: '호텔·식당 등 서비스업에서 주로 사용' },
    ],
    deeper_reading: '일본 직장에서 敬語(경어)는 3종류입니다: 尊敬語(상대를 높이는 표현), 謙譲語(자신을 낮추는 표현), 丁寧語(정중한 표현). 외국인에게 가장 헷갈리는 것은 謙譲語예요. "먹다"가 상사의 행동이면 「召し上がる」, 내 행동이면 「いただく」로 다르게 씁니다.',
  },
  {
    id: 'office-03',
    series_id: 'office',
    series_name_jp: 'オフィスの日本語',
    series_name_kr: '직장 일본어',
    number: 3,
    tag: '보고연락상담',
    scene_kr: '상사가 "일은 항상 보고-연락-상담이 중요해"라고 말했다',
    scene_jp: '上司が「仕事は常に報告・連絡・相談が大事だよ」と言っていた',
    character_name_jp: '田中課長',
    character_name_kr: '다나카 과장',
    character_emoji: '👔',
    dialogue_jp: '仕事の基本は「ホウレンソウ」だよ。報告・連絡・相談、忘れないようにね。',
    dialogue_kr: '일의 기본은 "호렌소(호우렌소)"야. 보고·연락·상담, 잊지 말도록.',
    vocab_word: 'ホウレンソウ',
    vocab_reading: 'ほうれんそう',
    vocab_meaning: '報告(보고)·連絡(연락)·相談(상담)의 줄임말',
    vocab_example_jp: '「何か問題が起きたらすぐホウレンソウをするように」뭔가 문제가 생기면 바로 보고-연락-상담을 하도록.',
    vocab_example_kr: '"ほうれん草"(시금치)와 발음이 같아서 기억하기 쉬워요. 일본 직장 문화의 핵심 원칙입니다.',
    vocab_korea_compare: '한국 직장의 "보고 문화"와 비슷하지만, 일본은 이것을 아예 공식 약어로 만들어 교육할 만큼 철저히 강조합니다.',
    expressions: [
      { japanese: '報告いたします', reading: 'ほうこくいたします', pronunciation: '호-코쿠 이타시마스', korean: '보고드립니다', example: '「進捗を報告いたします」진행 상황을 보고드립니다' },
      { japanese: 'ご相談があります', reading: 'ごそうだんがあります', pronunciation: '고소-단가 아리마스', korean: '상담드릴 게 있습니다', example: '「少しご相談があるのですが」잠깐 상담드릴 게 있는데요' },
      { japanese: 'お時間よろしいでしょうか', reading: 'おじかんよろしいでしょうか', pronunciation: '오지칸 요로시이 데쇼-카', korean: '지금 시간 괜찮으신가요?', example: '보고/상담 전 먼저 묻는 표현' },
    ],
    deeper_reading: 'ホウレンソウ(보고·연락·상담)는 일본 직장 문화의 근간입니다. 특히 문제가 생겼을 때 혼자 해결하려다가 늦게 보고하면 크게 질책받습니다. "나쁜 소식일수록 빨리 報告"하는 것이 일본 직장 원칙이에요. 상사와 소통이 원활할수록 신뢰가 쌓입니다.',
  },
  {
    id: 'office-04',
    series_id: 'office',
    series_name_jp: 'オフィスの日本語',
    series_name_kr: '직장 일본어',
    number: 4,
    tag: '사과표현',
    scene_kr: '실수로 중요한 파일을 잘못 보냈다. 빠르게 사과해야 한다',
    scene_jp: 'ミスで重要なファイルを誤送信してしまった。素早く謝罪しなければならない',
    character_name_jp: '田中課長',
    character_name_kr: '다나카 과장',
    character_emoji: '👔',
    dialogue_jp: '誤送信をしてしまいました。大変申し訳ございません。すぐに対応いたします。',
    dialogue_kr: '잘못 보내버렸습니다. 정말 죄송합니다. 바로 처리하겠습니다.',
    vocab_word: '申し訳ございません',
    vocab_reading: 'もうしわけございません',
    vocab_meaning: '대단히 죄송합니다 (가장 격식 있는 사과)',
    vocab_example_jp: '「この度はご迷惑をおかけし、大変申し訳ございませんでした」이번에 불편을 드려서 대단히 죄송했습니다.',
    vocab_example_kr: '「すみません」→ 「申し訳ありません」→ 「申し訳ございません」순으로 정중도가 올라갑니다.',
    vocab_korea_compare: '한국의 "정말 죄송합니다"에 해당하지만, 일본은 사과의 격식 단계가 더 세분화되어 있어요. 공식 사과 시 반드시 「申し訳ございません」을 써야 합니다.',
    expressions: [
      { japanese: '申し訳ございません', reading: 'もうしわけございません', pronunciation: '모-시와케 고자이마센', korean: '대단히 죄송합니다 (격식)', example: '업무 실수·민원 대응 시 필수 표현' },
      { japanese: 'ご迷惑をおかけして', reading: 'ごめいわくをおかけして', pronunciation: '고메이와쿠오 오카케시테', korean: '폐를 끼쳐서', example: '「ご迷惑をおかけして大変失礼いたしました」' },
      { japanese: '早急に対応いたします', reading: 'さっきゅうにたいおういたします', pronunciation: '삭큐-니 타이오- 이타시마스', korean: '즉시 대응하겠습니다', example: '사과 후 반드시 대처 방안을 함께 말해야 함' },
    ],
    deeper_reading: '일본 직장에서 사과할 때는 반드시 3단계를 지켜야 합니다: ①즉시 사과 ②원인·경위 설명 ③재발 방지 대책 제시. 이 순서를 지키지 않으면 "성의 없다"는 인상을 줍니다. 특히 고객 앞에서는 「誠に申し訳ございません」(진심으로 대단히 죄송합니다)라는 표현을 씁니다.',
  },
  {
    id: 'office-05',
    series_id: 'office',
    series_name_jp: 'オフィスの日本語',
    series_name_kr: '직장 일본어',
    number: 5,
    tag: '전화응대',
    scene_kr: '처음으로 회사 전화를 받았다. 뭐라고 해야 할지 몰랐다',
    scene_jp: '初めて会社の電話を取った。何と言えばいいか分からなかった',
    character_name_jp: '鈴木先輩',
    character_name_kr: '스즈키 선배',
    character_emoji: '🧑‍💼',
    dialogue_jp: '電話は「お電話ありがとうございます、○○株式会社でございます」から始めるのよ。',
    dialogue_kr: '전화는 "전화 감사합니다, ○○주식회사입니다"로 시작하는 거야.',
    vocab_word: 'でございます',
    vocab_reading: 'でございます',
    vocab_meaning: '입니다 (「です」의 최고 격식체)',
    vocab_example_jp: '「○○株式会社でございます」○○주식회사입니다 — 전화 응대의 기본 문구.',
    vocab_example_kr: '「です」보다 훨씬 격식 있는 표현으로, 전화 응대·접객·공식 서한에 사용합니다.',
    vocab_korea_compare: '한국의 "○○입니다"보다 한 단계 더 격식체. 일본 비즈니스 전화는 이 표현 없이는 불완전합니다.',
    expressions: [
      { japanese: 'お電話ありがとうございます', reading: 'おでんわありがとうございます', pronunciation: '오뎅와 아리가토- 고자이마스', korean: '전화 감사합니다', example: '전화 수신 첫 마디' },
      { japanese: '少々お待ちください', reading: 'しょうしょうおまちください', pronunciation: '쇼-쇼- 오마치 쿠다사이', korean: '잠시만 기다려 주세요', example: '담당자를 연결할 때 필수 표현' },
      { japanese: '折り返しお電話いたします', reading: 'おりかえしおでんわいたします', pronunciation: '오리카에시 오뎅와 이타시마스', korean: '다시 전화드리겠습니다', example: '담당자 부재 시 사용' },
    ],
    deeper_reading: '일본 비즈니스 전화 응대는 스크립트가 매우 정형화되어 있습니다. 「お名前をお聞きしてもよろしいでしょうか」(성함을 여쭤봐도 될까요), 「○○は只今席を外しております」(○○는 지금 자리를 비웠습니다) 등의 표현을 미리 익혀두면 당황하지 않고 응대할 수 있습니다.',
  },
  {
    id: 'office-06',
    series_id: 'office',
    series_name_jp: 'オフィスの日本語',
    series_name_kr: '직장 일본어',
    number: 6,
    tag: '메일작성',
    scene_kr: '처음 업무 메일을 쓰는데, 시작과 끝 문구를 몰랐다',
    scene_jp: '初めてビジネスメールを書くとき、書き出しと締めの言葉が分からなかった',
    character_name_jp: '鈴木先輩',
    character_name_kr: '스즈키 선배',
    character_emoji: '🧑‍💼',
    dialogue_jp: 'メールは「お世話になっております」で始めて「よろしくお願いいたします」で終わるのが基本よ。',
    dialogue_kr: '메일은 "お世話になっております"로 시작해서 "よろしくお願いいたします"로 끝내는 게 기본이야.',
    vocab_word: 'お世話になっております',
    vocab_reading: 'おせわになっております',
    vocab_meaning: '평소 신세지고 있습니다 (비즈니스 메일 인사)',
    vocab_example_jp: '「いつもお世話になっております。○○株式会社の○○です。」항상 신세 지고 있습니다. ○○주식회사의 ○○입니다.',
    vocab_example_kr: '처음 연락하는 상대에게는 「初めてご連絡いたします」(처음 연락드립니다)를 씁니다.',
    vocab_korea_compare: '한국의 업무 메일 시작 "안녕하세요"에 해당하지만, 일본은 이 한 문장이 없으면 불완전한 메일로 인식됩니다.',
    expressions: [
      { japanese: 'お世話になっております', reading: 'おせわになっております', pronunciation: '오세와니 낫테 오리마스', korean: '평소 신세 지고 있습니다', example: '사내외 메일 모두 기본 첫 인사' },
      { japanese: 'ご確認のほどよろしくお願いいたします', reading: 'ごかくにんのほどよろしくおねがいいたします', pronunciation: '고카쿠닌노 호도 요로시쿠 오네가이이타시마스', korean: '확인 부탁드립니다', example: '파일 첨부나 내용 검토 요청 시' },
      { japanese: '取り急ぎご連絡まで', reading: 'とりいそぎごれんらくまで', pronunciation: '토리이소기 고렌라쿠 마데', korean: '우선 연락드립니다 (긴급 메일 마무리)', example: '「取り急ぎご連絡まで」급히 연락드리는 메일 마무리' },
    ],
    deeper_reading: '일본 비즈니스 메일은 구조가 정형화되어 있습니다: ①인사(お世話になっております) ②자기소개 ③용건 ④마무리(よろしくお願いいたします). 제목은 「【○○の件】」처럼 꺽쇠로 건명을 표시하는 것이 일반적이에요. 메일 하나로도 사회인으로서의 인상이 결정되는 만큼 형식을 철저히 지키는 것이 중요합니다.',
  },
  {
    id: 'office-07',
    series_id: 'office',
    series_name_jp: 'オフィスの日本語',
    series_name_kr: '직장 일본어',
    number: 7,
    tag: '회의표현',
    scene_kr: '첫 회의에 참가했다. 발언 타이밍을 잡지 못하고 있었다',
    scene_jp: '初めての会議に参加した。発言のタイミングがつかめなかった',
    character_name_jp: '田中課長',
    character_name_kr: '다나카 과장',
    character_emoji: '👔',
    dialogue_jp: '意見がある方は「よろしいでしょうか」と一声かけてから話してください。',
    dialogue_kr: '의견 있으신 분은 "실례합니다"라고 한 마디 하고 말씀해 주세요.',
    vocab_word: 'よろしいでしょうか',
    vocab_reading: 'よろしいでしょうか',
    vocab_meaning: '괜찮을까요? (발언 전 양해 요청)',
    vocab_example_jp: '「一点確認させてください」한 가지 확인하겠습니다 — 회의에서 질문할 때 자주 씁니다.',
    vocab_example_kr: '일본 회의는 순서와 형식을 중시합니다. 갑자기 끼어들기보다 발언 신호를 먼저 보내는 것이 기본 예의입니다.',
    vocab_korea_compare: '한국 회의에서는 바로 말하는 경우가 많지만, 일본 회의는 발언 전 "よろしいでしょうか"로 자리를 요청하는 것이 일반적입니다.',
    expressions: [
      { japanese: 'よろしいでしょうか', reading: 'よろしいでしょうか', pronunciation: '요로시이 데쇼-카', korean: '괜찮을까요? (발언 전 양해)', example: '회의 발언 타이밍을 잡는 기본 표현' },
      { japanese: '一点確認させてください', reading: 'いってんかくにんさせてください', pronunciation: '잇텐 카쿠닌 사세테 쿠다사이', korean: '한 가지 확인하겠습니다', example: '회의 중 질문이나 반론을 제기할 때' },
      { japanese: 'おっしゃる通りです', reading: 'おっしゃるとおりです', pronunciation: '옷샤루 토-리 데스', korean: '말씀하신 대로입니다 (동의 표현)', example: '상사나 선배 의견에 동의할 때' },
    ],
    deeper_reading: '일본 회의(会議)는 의사결정보다 의견 조율(根回し, ねまわし)이 목적인 경우가 많습니다. 회의 전에 관계자들과 개별적으로 미리 의견을 맞춰두는 "根回し" 문화가 있어요. 회의에서 갑작스러운 반대나 새로운 제안을 꺼내면 오히려 불편함을 줄 수 있으니 주의하세요.',
  },
  {
    id: 'office-08',
    series_id: 'office',
    series_name_jp: 'オフィスの日本語',
    series_name_kr: '직장 일본어',
    number: 8,
    tag: '퇴근인사',
    scene_kr: '먼저 퇴근하려고 했는데 어떻게 인사해야 할지 몰랐다',
    scene_jp: '先に帰ろうとしたが、どのように挨拶すればいいか分からなかった',
    character_name_jp: '鈴木先輩',
    character_name_kr: '스즈키 선배',
    character_emoji: '🧑‍💼',
    dialogue_jp: '帰るときは「お先に失礼します」って言うのよ。残ってる人に「お疲れ様でした」も忘れずに。',
    dialogue_kr: '먼저 나갈 때는 "먼저 실례합니다"라고 해. 남아 있는 사람한테 "수고하셨습니다"도 잊지 말고.',
    vocab_word: 'お先に失礼します',
    vocab_reading: 'おさきにしつれいします',
    vocab_meaning: '먼저 실례하겠습니다 (먼저 퇴근 시)',
    vocab_example_jp: '「お先に失礼します。お疲れ様でした。」먼저 실례하겠습니다. 수고하셨습니다.',
    vocab_example_kr: '자리를 먼저 떠날 때 쓰는 표현입니다. 상사보다 먼저 퇴근하는 것이 실례라는 인식이 있는 직장도 많아요.',
    vocab_korea_compare: '한국의 "먼저 가겠습니다"와 같은 의미지만, 일본은 「失礼します」를 붙여 더 정중하게 표현합니다.',
    expressions: [
      { japanese: 'お先に失礼します', reading: 'おさきにしつれいします', pronunciation: '오사키니 시쓰레이시마스', korean: '먼저 실례하겠습니다', example: '퇴근·자리 이탈 시 기본 인사' },
      { japanese: 'お疲れ様でした', reading: 'おつかれさまでした', pronunciation: '오쓰카레사마 데시타', korean: '수고하셨습니다', example: '퇴근하는 동료나 업무 마친 후 인사' },
      { japanese: 'ご苦労様でした', reading: 'ごくろうさまでした', pronunciation: '고쿠로-사마 데시타', korean: '수고하셨습니다 (윗사람이 아랫사람에게)', example: '상사가 부하직원에게 쓰는 표현 — 반대로 쓰면 실례' },
    ],
    deeper_reading: '「お疲れ様」와 「ご苦労様」은 비슷해 보이지만 방향이 다릅니다. 「お疲れ様」는 상하·동료 모두 가능하고, 「ご苦労様」는 윗사람이 아랫사람에게만 씁니다. 부하직원이 상사에게 「ご苦労様でした」라고 하면 큰 실례가 됩니다. 직장 일본어에서 자주 생기는 실수 1위입니다.',
  },
  {
    id: 'office-09',
    series_id: 'office',
    series_name_jp: 'オフィスの日本語',
    series_name_kr: '직장 일본어',
    number: 9,
    tag: '음식주문',
    scene_kr: '점심 회식에서 대표로 주문을 해야 하는 상황이 됐다',
    scene_jp: '昼の会食で代表して注文しなければならない状況になった',
    character_name_jp: '田中課長',
    character_name_kr: '다나카 과장',
    character_emoji: '👔',
    dialogue_jp: 'じゃあ、注文お願いできる？全員分まとめて頼んでね。',
    dialogue_kr: '그럼, 주문 부탁해도 될까? 다 같이 한꺼번에 주문해줘.',
    vocab_word: 'まとめて',
    vocab_reading: 'まとめて',
    vocab_meaning: '한꺼번에, 모아서',
    vocab_example_jp: '「全員分まとめてお願いします」전원 것 한꺼번에 부탁드립니다.',
    vocab_example_kr: '식당 주문 외에도 업무에서 "여러 건을 한꺼번에" 처리할 때 자주 씁니다.',
    vocab_korea_compare: '한국의 "다 같이"와 비슷하지만, 주문 시 「まとめて」를 쓰면 직원에게 효율적으로 의사를 전달할 수 있습니다.',
    expressions: [
      { japanese: 'すみません、注文をお願いします', reading: 'すみません、ちゅうもんをおねがいします', pronunciation: '스미마센, 추-몬오 오네가이시마스', korean: '저기요, 주문할게요', example: '직원을 부를 때 기본 표현' },
      { japanese: '同じものを人数分お願いします', reading: 'おなじものをにんずうぶんおねがいします', pronunciation: '오나지 모노오 닌즈-분 오네가이시마스', korean: '같은 것으로 인원수만큼 부탁드립니다', example: '회식에서 같은 메뉴를 여러 개 주문할 때' },
      { japanese: 'お会計をお願いします', reading: 'おかいけいをおねがいします', pronunciation: '오카이케이오 오네가이시마스', korean: '계산 부탁드립니다', example: '식사 후 계산 요청' },
    ],
    deeper_reading: '일본의 회식(飲み会, 노미카이)은 직장 문화의 중요한 부분입니다. 자리 배치는 상석(上座)에 상사가 앉고, 입구 쪽이 말석(下座)입니다. 건배 제안(乾杯の挨拶)은 보통 상사가 하며, 따를 때는 상대방 잔이 비기 전에 채워주는 것이 예의입니다.',
  },
  {
    id: 'office-10',
    series_id: 'office',
    series_name_jp: 'オフィスの日本語',
    series_name_kr: '직장 일본어',
    number: 10,
    tag: '연차휴가',
    scene_kr: '처음 연차 신청을 하려고 상사에게 말을 꺼냈다',
    scene_jp: '初めて有給申請をしようとして、上司に話しかけた',
    character_name_jp: '田中課長',
    character_name_kr: '다나카 과장',
    character_emoji: '👔',
    dialogue_jp: '有休を取りたいときは、なるべく早めに申請してね。理由は「私用のため」でいいよ。',
    dialogue_kr: '연차 쓰고 싶으면 가능하면 일찍 신청해줘. 이유는 "개인 사정"이라고 해도 돼.',
    vocab_word: '有給休暇',
    vocab_reading: 'ゆうきゅうきゅうか',
    vocab_meaning: '유급 휴가 (연차)',
    vocab_example_jp: '「来週の月曜日、有給をいただきたいのですが、よろしいでしょうか」다음 주 월요일 연차를 쓰고 싶은데 괜찮을까요?',
    vocab_example_kr: '일본은 연차 사용률이 낮은 편이지만, 법적으로 보장된 권리입니다. 당당하게 신청하세요.',
    vocab_korea_compare: '한국과 마찬가지로 연차는 법적 권리이지만, 일본 직장에서는 취득 전 상사에게 미리 양해를 구하는 문화가 강합니다.',
    expressions: [
      { japanese: '有給をいただきたいのですが', reading: 'ゆうきゅうをいただきたいのですが', pronunciation: '유-큐-오 이타다키타이노데스가', korean: '연차를 쓰고 싶은데요', example: '연차 신청 시 기본 표현' },
      { japanese: '私用のため', reading: 'しようのため', pronunciation: '시요-노 타메', korean: '개인 사정으로', example: '「私用のためお休みをいただけますか」개인 사정으로 쉴 수 있을까요?' },
      { japanese: 'ご迷惑をおかけします', reading: 'ごめいわくをおかけします', pronunciation: '고메이와쿠오 오카케시마스', korean: '폐를 끼치겠습니다', example: '자리 비울 때 동료에게 하는 인사' },
    ],
    deeper_reading: '일본의 有給休暇(유급 휴가)는 입사 6개월 후 10일이 부여되고, 이후 근속 연수에 따라 증가합니다. 2019년부터 5일 이상 의무 소진이 법제화됐습니다. 연차 신청 시 「私用のため」(개인 사정)라고만 해도 이유 없이 거부할 수 없지만, 실제 직장 분위기에서는 눈치가 필요한 경우도 있습니다.',
  },
]

export const HOSPITAL_EPISODES: Episode[] = [
  {
    id: 'hospital-01',
    series_id: 'hospital',
    series_name_jp: '病院の日本語',
    series_name_kr: '병원 일본어',
    number: 1,
    tag: '접수',
    scene_kr: '처음 가는 병원 접수 창구에서 진료를 신청해야 한다',
    scene_jp: '初めて行く病院の受付で診察の申し込みをしなければならない',
    character_name_jp: '受付の方',
    character_name_kr: '접수 담당자',
    character_emoji: '👩‍⚕️',
    dialogue_jp: 'いらっしゃいませ。本日はどうされましたか？保険証はお持ちですか？',
    dialogue_kr: '어서 오세요. 오늘은 어떻게 오셨나요? 보험증은 가지고 계신가요?',
    vocab_word: '保険証',
    vocab_reading: 'ほけんしょう',
    vocab_meaning: '건강보험증',
    vocab_example_jp: '「保険証をお持ちでない場合は、全額自己負担になります。」보험증이 없으시면 전액 자부담이 됩니다.',
    vocab_example_kr: '일본에 거주하면 건강보험 가입이 의무입니다. 회사 재직자는 사회보험(社会保険), 그 외는 국민건강보험(国民健康保険)에 가입합니다.',
    vocab_korea_compare: '한국의 건강보험증과 유사하지만, 일본은 매번 병원 방문 시 提示(제시)하는 것이 관례입니다.',
    expressions: [
      { japanese: '初診なんですが', reading: 'しょしんなんですが', pronunciation: '쇼신난데스가', korean: '처음 오는 건데요 (초진입니다)', example: '처음 방문하는 병원에서 접수할 때' },
      { japanese: '保険証を持参しました', reading: 'ほけんしょうをじさんしました', pronunciation: '호켄쇼-오 지산시마시타', korean: '보험증을 가져왔습니다', example: '「こちら保険証です」이쪽이 보험증입니다' },
      { japanese: '問診票を記入してください', reading: 'もんしんひょうをきにゅうしてください', pronunciation: '몬신효-오 키뉴-시테 쿠다사이', korean: '문진표를 작성해 주세요', example: '접수 시 접수 담당자가 하는 말' },
    ],
    deeper_reading: '일본 병원은 크게 診療所(진료소/클리닉)와 病院(병원, 20병상 이상)으로 나뉩니다. 처음 방문하면 초진료(初診料)가 추가됩니다. 병원마다 診察受付時間(진찰 접수 시간)이 있으니 미리 확인하세요. 예약 없이 가는 경우 待ち時間(대기 시간)이 길 수 있어요.',
  },
  {
    id: 'hospital-02',
    series_id: 'hospital',
    series_name_jp: '病院の日本語',
    series_name_kr: '병원 일본어',
    number: 2,
    tag: '증상설명',
    scene_kr: '의사 앞에서 내 증상을 설명해야 하는데 말이 잘 안 나온다',
    scene_jp: '医師の前で症状を説明しなければならないが、言葉がうまく出てこない',
    character_name_jp: '田中先生',
    character_name_kr: '다나카 의사',
    character_emoji: '👨‍⚕️',
    dialogue_jp: 'どうされましたか？いつ頃からですか？',
    dialogue_kr: '어디가 불편하세요? 언제부터인가요?',
    vocab_word: '症状',
    vocab_reading: 'しょうじょう',
    vocab_meaning: '증상',
    vocab_example_jp: '「どんな症状がありますか？」어떤 증상이 있으신가요?',
    vocab_example_kr: '의사에게 증상을 설명할 때는 "いつから"(언제부터), "どこが"(어디가), "どのように"(어떻게)의 3가지를 말하면 됩니다.',
    vocab_korea_compare: '한국에서는 "배가 아파요"처럼 직접적으로 말하지만, 일본도 유사합니다. 단, 경어를 써야 해서 어려울 수 있어요.',
    expressions: [
      { japanese: '頭が痛いです', reading: 'あたまがいたいです', pronunciation: '아타마가 이타이데스', korean: '머리가 아파요', example: '두통이 있을 때' },
      { japanese: 'お腹が痛いです', reading: 'おなかがいたいです', pronunciation: '오나카가 이타이데스', korean: '배가 아파요', example: '복통이 있을 때' },
      { japanese: '熱があります', reading: 'ねつがあります', pronunciation: '네쓰가 아리마스', korean: '열이 있어요', example: '「38度の熱があります」38도 열이 있어요' },
    ],
    deeper_reading: '일본에서 증상을 말할 때 「〜が痛い」(~가 아프다) 패턴이 가장 기본입니다. 痛み(이타미)=통증, 吐き気(하키케)=메스꺼움, 下痢(게리)=설사, 便秘(벤피)=변비, 咳(세키)=기침, 鼻水(하나미즈)=콧물 같은 단어들도 알아두면 좋아요.',
  },
  {
    id: 'hospital-03',
    series_id: 'hospital',
    series_name_jp: '病院の日本語',
    series_name_kr: '병원 일본어',
    number: 3,
    tag: '처방전',
    scene_kr: '처방전을 들고 약국에 갔는데 약사가 뭔가를 설명해준다',
    scene_jp: '処方箋を持って薬局へ行ったら、薬剤師が何かを説明してくれた',
    character_name_jp: '薬剤師さん',
    character_name_kr: '약사',
    character_emoji: '💊',
    dialogue_jp: '1日3回、毎食後に飲んでください。アルコールは控えてくださいね。',
    dialogue_kr: '하루 3번, 매 식후에 드세요. 알코올은 삼가 주세요.',
    vocab_word: '処方箋',
    vocab_reading: 'しょほうせん',
    vocab_meaning: '처방전',
    vocab_example_jp: '「処方箋薬局」처방전 약국 (処方箋が必要な薬を扱う薬局)',
    vocab_example_kr: '일본 약국은 処方箋薬局(처방전 약국)과 일반 드럭스토어로 나뉩니다. 처방전이 필요한 약은 처방전 약국에서만 받을 수 있어요.',
    vocab_korea_compare: '한국과 마찬가지로 의사 처방 없이는 특정 약을 살 수 없습니다. 드럭스토어(ドラッグストア)에서는 처방전 없이 살 수 있는 약만 취급합니다.',
    expressions: [
      { japanese: '1日3回食後に飲んでください', reading: 'いちにちさんかいしょくごにのんでください', pronunciation: '이치니치 산카이 쇼쿠고니 논데 쿠다사이', korean: '하루 3번 식후에 드세요', example: '약 복용법 기본 표현' },
      { japanese: '副作用はありますか', reading: 'ふくさようはありますか', pronunciation: '후쿠사요-와 아리마스카', korean: '부작용이 있나요?', example: '약 받을 때 물어볼 수 있는 질문' },
      { japanese: 'この薬は何日分ですか', reading: 'このくすりはなんにちぶんですか', pronunciation: '코노 쿠스리와 난니치분 데스카', korean: '이 약은 며칠 치인가요?', example: '처방받은 약의 양을 확인할 때' },
    ],
    deeper_reading: '일본 약 복용 지시 표현: 食前(쇼쿠젠)=식전, 食後(쇼쿠고)=식후, 食間(쇼쿠칸)=식간(食事から2時間後), 就寝前(슈-신마에)=취침 전. 1日1回(이치니치 잇카이)=1일 1회, 1日2回(이치니치 니카이)=1일 2회, 1日3回(이치니치 산카이)=1일 3회입니다.',
  },
  {
    id: 'hospital-04',
    series_id: 'hospital',
    series_name_jp: '病院の日本語',
    series_name_kr: '병원 일본어',
    number: 4,
    tag: '치과',
    scene_kr: '치통이 심해서 동네 치과에 처음 갔다',
    scene_jp: '歯が痛くて、近所の歯医者に初めて行った',
    character_name_jp: '歯科医の先生',
    character_name_kr: '치과 의사',
    character_emoji: '🦷',
    dialogue_jp: 'どの歯が痛みますか？いつ頃から痛みますか？',
    dialogue_kr: '어느 치아가 아프신가요? 언제부터 아프신가요?',
    vocab_word: '虫歯',
    vocab_reading: 'むしば',
    vocab_meaning: '충치',
    vocab_example_jp: '「虫歯が3本あります。今日は一番痛い歯を治療しましょう。」충치가 3개 있습니다. 오늘은 가장 아픈 치아를 치료하겠습니다.',
    vocab_example_kr: '일본도 치과 치료는 건강보험 적용이 됩니다. 단, 미용 목적(미백, 라미네이트 등)은 자유 진료로 비용이 높습니다.',
    vocab_korea_compare: '한국과 마찬가지로 충치 치료는 保険適用(보험 적용)이 됩니다. 保険内治療(보험 내 치료)와 自由診療(자유 진료) 중 선택할 수 있는 경우도 있어요.',
    expressions: [
      { japanese: '歯が痛いです', reading: 'はがいたいです', pronunciation: '하가 이타이데스', korean: '치아가 아파요', example: '치통을 호소할 때' },
      { japanese: '冷たいものが染みます', reading: 'つめたいものがしみます', pronunciation: '쓰메타이 모노가 시미마스', korean: '차가운 것이 시려요', example: '시린 증상을 설명할 때' },
      { japanese: '歯を抜かないといけませんか', reading: 'はをぬかないといけませんか', pronunciation: '하오 누카나이토 이케마센카', korean: '이를 뽑아야 하나요?', example: '발치 여부를 확인할 때' },
    ],
    deeper_reading: '일본 치과는 歯科(시카) 또는 歯医者(하이샤)라고 합니다. 가장 가까운 치과를 찾을 때는 「近くの歯医者を教えてください」(근처 치과를 알려주세요)라고 해보세요. 예약(予約=요야쿠)이 필요한 경우가 많습니다.',
  },
  {
    id: 'hospital-05',
    series_id: 'hospital',
    series_name_jp: '病院の日本語',
    series_name_kr: '병원 일본어',
    number: 5,
    tag: '구급',
    scene_kr: '친구가 갑자기 쓰러져서 구급차를 불러야 한다',
    scene_jp: '友人が突然倒れて、救急車を呼ばなければならない',
    character_name_jp: '救急隊員',
    character_name_kr: '구급대원',
    character_emoji: '🚑',
    dialogue_jp: '119番です。現在地と状況を教えてください。',
    dialogue_kr: '119입니다. 현재 위치와 상황을 알려주세요.',
    vocab_word: '救急車',
    vocab_reading: 'きゅうきゅうしゃ',
    vocab_meaning: '구급차',
    vocab_example_jp: '「119番に電話して救急車を呼んでください」119에 전화해서 구급차를 불러주세요.',
    vocab_example_kr: '일본 응급 번호는 119(구급·화재), 110(경찰)입니다. 한국과 달리 구급(救急)과 화재(火事) 모두 119입니다.',
    vocab_korea_compare: '한국은 119=소방/구급, 112=경찰이지만, 일본은 119=소방/구급, 110=경찰입니다. 외국인의 경우 #9110(경찰 생활 안전 다이얼)도 이용할 수 있어요.',
    expressions: [
      { japanese: '救急車を呼んでください', reading: 'きゅうきゅうしゃをよんでください', pronunciation: '큐-큐-샤오 욘데 쿠다사이', korean: '구급차를 불러주세요', example: '응급상황에서 주변에 도움을 요청할 때' },
      { japanese: '意識がありません', reading: 'いしきがありません', pronunciation: '이시키가 아리마센', korean: '의식이 없어요', example: '119에 신고할 때 상태를 설명하는 표현' },
      { japanese: '急いでください', reading: 'いそいでください', pronunciation: '이소이데 쿠다사이', korean: '서둘러 주세요', example: '빨리 와달라고 부탁할 때' },
    ],
    deeper_reading: '일본에서 구급차(救急車)는 원칙적으로 무료입니다. 하지만 가볍게 택시 대용으로 이용하는 것은 민폐로 여겨집니다. 「救急安心センター」(#7119)에 전화하면 구급차가 필요한지 상담받을 수 있어요. 긴급하지 않은 경우 병원 야간창구(夜間窓口)나 休日急患センター(휴일 응급 센터)를 이용하는 것이 좋습니다.',
  },
]

export const SHOPPING_EPISODES: Episode[] = [
  {
    id: 'shopping-01',
    series_id: 'shopping',
    series_name_jp: 'お買い物の日本語',
    series_name_kr: '쇼핑 일본어',
    number: 1,
    tag: '편의점',
    scene_kr: '편의점에서 계산할 때 직원이 여러 가지를 물어온다',
    scene_jp: 'コンビニで会計するとき、店員がいろいろ聞いてくる',
    character_name_jp: '店員さん',
    character_name_kr: '편의점 직원',
    character_emoji: '🏪',
    dialogue_jp: 'ポイントカードはお持ちですか？袋はよろしいですか？温めますか？',
    dialogue_kr: '포인트 카드 있으신가요? 봉투는 괜찮으신가요? 데워드릴까요?',
    vocab_word: 'レジ袋',
    vocab_reading: 'レジぶくろ',
    vocab_meaning: '비닐봉투 (계산대 봉투)',
    vocab_example_jp: '「レジ袋はご利用ですか？3円になります。」비닐봉투 사용하시겠어요? 3엔입니다.',
    vocab_example_kr: '2020년부터 일본도 편의점·슈퍼의 비닐봉투가 유료화됐습니다. 에코백(エコバッグ)을 지참하면 봉투 값을 절약할 수 있어요.',
    vocab_korea_compare: '한국도 2019년부터 마트 비닐봉투가 유료화됐습니다. 일본은 "袋はよろしいですか?"로 물어보는 게 표준 대응입니다.',
    expressions: [
      { japanese: '袋はいりません', reading: 'ふくろはいりません', pronunciation: '후쿠로와 이리마센', korean: '봉투는 필요 없어요', example: '에코백을 가져왔을 때' },
      { japanese: '温めてください', reading: 'あたためてください', pronunciation: '아타타메테 쿠다사이', korean: '데워주세요', example: '도시락·만두 등을 데울 때' },
      { japanese: '現金で払います', reading: 'げんきんではらいます', pronunciation: '겐킨데 하라이마스', korean: '현금으로 낼게요', example: '카드 대신 현금으로 결제할 때' },
    ],
    deeper_reading: '일본 편의점 계산대에서 자주 듣는 말 5선: ①「ポイントカードはお持ちですか」(포인트 카드), ②「袋はよろしいですか」(봉투), ③「温めますか」(데우기), ④「お箸はおつけしますか」(젓가락 필요?), ⑤「こちらレシートです」(영수증). 이 5가지만 알면 편의점이 편해집니다!',
  },
  {
    id: 'shopping-02',
    series_id: 'shopping',
    series_name_jp: 'お買い物の日本語',
    series_name_kr: '쇼핑 일본어',
    number: 2,
    tag: '슈퍼',
    scene_kr: '슈퍼마켓에서 특정 물건을 찾지 못해 점원에게 물어봐야 한다',
    scene_jp: 'スーパーで特定の商品が見つからず、店員に聞かなければならない',
    character_name_jp: '店員さん',
    character_name_kr: '슈퍼 직원',
    character_emoji: '🛒',
    dialogue_jp: 'いらっしゃいませ。何かお探しですか？',
    dialogue_kr: '어서 오세요. 찾으시는 것이 있으신가요?',
    vocab_word: '特売',
    vocab_reading: 'とくばい',
    vocab_meaning: '특매, 세일',
    vocab_example_jp: '「今日はお肉が特売です。100gあたり198円です。」오늘은 고기 특매입니다. 100g당 198엔입니다.',
    vocab_example_kr: '일본 슈퍼는 요일별 특매(特売)가 많습니다. 水曜日はお肉が安い(수요일은 고기가 싸다)처럼 요일별 할인이 있는 경우가 많아요.',
    vocab_korea_compare: '한국 마트의 "1+1"처럼 일본은 「2個で○○円」(2개에 ○○엔) 등의 묶음 할인이 많습니다. 「お値打ち品」(오네우치-힌)=가성비 상품이라는 표현도 자주 보입니다.',
    expressions: [
      { japanese: 'すみません、○○はどこですか', reading: 'すみません、○○はどこですか', pronunciation: '스미마센, ○○와 도코데스카', korean: '저기요, ○○은 어디 있나요?', example: '물건 위치를 물어볼 때 가장 기본 표현' },
      { japanese: '試食してもいいですか', reading: 'ししょくしてもいいですか', pronunciation: '시쇼쿠시테모 이이데스카', korean: '시식해도 될까요?', example: '시식 코너에서 먹기 전에' },
      { japanese: 'ポイントカードを作りたいのですが', reading: 'ポイントカードをつくりたいのですが', pronunciation: '포인토 카-도오 쓰쿠리타이노데스가', korean: '포인트 카드를 만들고 싶은데요', example: '첫 방문 시 포인트 카드 신청할 때' },
    ],
    deeper_reading: '일본 슈퍼에서는 대부분의 체인이 독자적인 ポイントカード(포인트 카드)를 운영합니다. マックスバリュ, イトーヨーカドー, ライフ, アオキ 등 각자 카드가 있어요. PayPay, d払い 같은 스마트폰 결제도 보편화됐습니다. 영수증(レシート)을 꼭 받아두면 환불·교환 시 편합니다.',
  },
  {
    id: 'shopping-03',
    series_id: 'shopping',
    series_name_jp: 'お買い物の日本語',
    series_name_kr: '쇼핑 일본어',
    number: 3,
    tag: '드럭스토어',
    scene_kr: '드럭스토어에서 감기약을 찾는데 종류가 너무 많아서 점원에게 추천을 부탁한다',
    scene_jp: 'ドラッグストアで風邪薬を探しているが種類が多すぎて、店員に推薦を頼む',
    character_name_jp: '薬局スタッフ',
    character_name_kr: '드럭스토어 직원',
    character_emoji: '💊',
    dialogue_jp: 'どのような症状でお困りですか？鼻水ですか、熱ですか？',
    dialogue_kr: '어떤 증상으로 불편하신가요? 콧물인가요, 열인가요?',
    vocab_word: 'ドラッグストア',
    vocab_reading: 'ドラッグストア',
    vocab_meaning: '드럭스토어 (약국 겸 잡화점)',
    vocab_example_jp: '「マツキヨ(マツモトキヨシ)はドラッグストアの代表的なチェーンです。」마쓰키요는 드럭스토어의 대표적인 체인입니다.',
    vocab_example_kr: '일본의 ドラッグストア는 약·화장품·생활용품·식품까지 파는 종합 잡화점입니다. 마쓰모토키요시(マツモトキヨシ), 코스모스(コスモス), 웰시아(ウエルシア) 등이 대표적입니다.',
    vocab_korea_compare: '한국의 올리브영 같은 역할이지만, 일본 드럭스토어는 처방전 없이 살 수 있는 약(市販薬=시판약)의 종류가 훨씬 많습니다.',
    expressions: [
      { japanese: 'この薬を推薦していただけますか', reading: 'このくすりをすいせんしていただけますか', pronunciation: '코노 쿠스리오 스이센시테 이타다케마스카', korean: '이 약을 추천해 주실 수 있나요?', example: '직원에게 약 추천을 부탁할 때' },
      { japanese: '日本語の説明書しかありませんが大丈夫ですか', reading: 'にほんごのせつめいしょしかありませんがだいじょうぶですか', pronunciation: '니혼고노 세쓰메이쇼 시카 아리마센가 다이죠-부데스카', korean: '일본어 설명서밖에 없는데 괜찮으신가요?', example: '외국인에게 직원이 확인할 때' },
      { japanese: 'レシートをください', reading: 'レシートをください', pronunciation: '레시-토오 쿠다사이', korean: '영수증 주세요', example: '영수증이 필요할 때' },
    ],
    deeper_reading: '일본 드럭스토어의 인기 상품은 관광객에게도 인기입니다. 龍角散(류카쿠산)=목약, バファリン(바파린)=두통약, ロキソニン(로키소닌)=진통소염제, パブロン(파부론)=감기약 등. 外国語対応(외국어 대응) 직원이 있는 점포도 늘고 있습니다.',
  },
  {
    id: 'shopping-04',
    series_id: 'shopping',
    series_name_jp: 'お買い物の日本語',
    series_name_kr: '쇼핑 일본어',
    number: 4,
    tag: '옷가게',
    scene_kr: '옷 가게에서 마음에 드는 옷을 발견했는데 다른 사이즈가 있는지 물어봐야 한다',
    scene_jp: '洋服店で気に入った服を見つけたが、別のサイズがあるか聞かなければならない',
    character_name_jp: '店員さん',
    character_name_kr: '옷가게 직원',
    character_emoji: '👗',
    dialogue_jp: 'いらっしゃいませ。何かお探しですか？サイズはご存知ですか？',
    dialogue_kr: '어서 오세요. 찾으시는 것 있으신가요? 사이즈는 아시나요?',
    vocab_word: '試着',
    vocab_reading: 'しちゃく',
    vocab_meaning: '시착, 피팅룸에서 입어보기',
    vocab_example_jp: '「試着室はこちらになります。どうぞごゆっくり。」피팅룸은 이쪽입니다. 천천히 입어보세요.',
    vocab_example_kr: '일본 옷가게에서는 試着(시착=옷 입어보기)이 가능합니다. 「試着してもいいですか」(입어봐도 될까요?)라고 물어보면 됩니다.',
    vocab_korea_compare: '한국에서는 사이즈를 S/M/L로 표기하는 경우가 많지만, 일본은 S/M/L 외에 숫자 사이즈(38=9호, 40=11호)도 함께 씁니다.',
    expressions: [
      { japanese: 'これのLサイズはありますか', reading: 'これのエルサイズはありますか', pronunciation: '코레노 에루 사이즈와 아리마스카', korean: '이것 L 사이즈 있나요?', example: '다른 사이즈를 물어볼 때' },
      { japanese: '試着してもいいですか', reading: 'しちゃくしてもいいですか', pronunciation: '시챠쿠시테모 이이데스카', korean: '입어봐도 될까요?', example: '피팅룸 이용 전에 허락 구하기' },
      { japanese: 'これを別の色で見せてもらえますか', reading: 'これをべつのいろでみせてもらえますか', pronunciation: '코레오 베쓰노 이로데 미세테 모라에마스카', korean: '이것 다른 색으로 보여주실 수 있나요?', example: '색상 변경을 요청할 때' },
    ],
    deeper_reading: '일본 옷가게에서는 入店時(입점 시) 점원이 「いらっしゃいませ」로 맞이하고, 부담스러운 경우 「見ているだけです」(그냥 보는 거예요)라고 해도 됩니다. 세일 시즌은 1월과 7월이며, 新年福袋(후쿠부쿠로=복주머니)도 일본의 연초 쇼핑 문화입니다.',
  },
  {
    id: 'shopping-05',
    series_id: 'shopping',
    series_name_jp: 'お買い物の日本語',
    series_name_kr: '쇼핑 일본어',
    number: 5,
    tag: '환불',
    scene_kr: '구입한 상품에 결함이 있어 환불이나 교환을 요청하러 왔다',
    scene_jp: '購入した商品に欠陥があり、返品か交換を依頼しに来た',
    character_name_jp: '店員さん',
    character_name_kr: '매장 직원',
    character_emoji: '🏬',
    dialogue_jp: 'レシートはお持ちですか？商品の状態を確認させていただいてよろしいでしょうか。',
    dialogue_kr: '영수증은 가지고 계신가요? 상품 상태를 확인해도 될까요?',
    vocab_word: '返品・交換',
    vocab_reading: 'へんぴん・こうかん',
    vocab_meaning: '반품·교환',
    vocab_example_jp: '「レシートをお持ちであれば、1週間以内は返品・交換できます。」영수증이 있으시면 1주일 이내 반품·교환 가능합니다.',
    vocab_example_kr: '일본은 한국보다 반품·교환 조건이 까다로운 편입니다. 불량품(不良品=후료-힌)이 아닌 단순 변심은 拒否(거절)되는 경우가 많습니다.',
    vocab_korea_compare: '한국에서는 변심 반품도 어느 정도 허용되는 편이지만, 일본에서는 "開封済み"(개봉 완료)이면 반품이 어려운 경우가 많습니다. 불량품이면 당당하게 요구할 수 있습니다.',
    expressions: [
      { japanese: 'これ、返品したいんですが', reading: 'これ、へんぴんしたいんですが', pronunciation: '코레, 헨핀시타이 데스가', korean: '이것 반품하고 싶은데요', example: '반품 의사를 밝힐 때' },
      { japanese: '商品に不具合があります', reading: 'しょうひんにふぐあいがあります', pronunciation: '쇼-힌니 후구아이가 아리마스', korean: '상품에 결함이 있어요', example: '불량품이라는 것을 설명할 때' },
      { japanese: '同じ商品と交換してもらえますか', reading: 'おなじしょうひんとこうかんしてもらえますか', pronunciation: '오나지 쇼-힌토 코-칸시테 모라에마스카', korean: '같은 상품으로 교환해 주실 수 있나요?', example: '반품 대신 교환을 원할 때' },
    ],
    deeper_reading: '일본의 반품·교환 정책은 가게마다 다릅니다. 불량품(不良品)이라면 법적으로 교환·환불이 가능합니다. 단순 변심 반품은 가게의 返品ポリシー(반품 정책)에 따릅니다. 영수증(レシート)을 반드시 챙겨두세요. 온라인 쇌핑의 경우 クーリング・オフ(쿨링오프) 제도를 이용할 수 있습니다.',
  },
]

export const NURSERY_EPISODES: Episode[] = [
  {
    id: 'nursery-01',
    series_id: 'nursery',
    series_name_jp: '保育園の日本語',
    series_name_kr: '육아·보육 일본어',
    number: 1,
    tag: '등원',
    scene_kr: '아침에 아이를 어린이집에 맡기러 갔다. 담임 선생님에게 오늘 아이 상태를 전달해야 한다',
    scene_jp: '朝、子どもを保育園に預けに来た。担任の先生に今日の子どもの状態を伝えなければならない',
    character_name_jp: '先生',
    character_name_kr: '담임 선생님',
    character_emoji: '👩‍🏫',
    dialogue_jp: 'おはようございます！今日の体調はいかがですか？昨夜はよく眠れましたか？',
    dialogue_kr: '안녕하세요! 오늘 컨디션은 어때요? 어제 밤은 잘 잤나요?',
    vocab_word: '預ける',
    vocab_reading: 'あずける',
    vocab_meaning: '맡기다, 보관하다',
    vocab_example_jp: '「子どもを保育園に預ける」(아이를 어린이집에 맡기다)',
    vocab_example_kr: '預ける는 "잠시 맡기다"는 뉘앙스입니다. 보관함에 짐을 맡길 때도 씁니다.',
    vocab_korea_compare: '한국의 "맡기다"와 동일한 의미입니다. 일본 보육원 등원 시 선생님께 아이 상태를 간단히 보고하는 것이 일반적인 문화입니다.',
    expressions: [
      { japanese: 'お願いします', reading: 'おねがいします', pronunciation: '오네가이시마스', korean: '잘 부탁드립니다 (맡깁니다)', example: '아이를 건네며 하는 인사' },
      { japanese: '昨夜少し熱がありましたが、今は下がっています', reading: 'さくやすこしねつがありましたが、いまはさがっています', pronunciation: '사쿠야 스코시 네쓰가 아리마시타가, 이마와 사갓테 이마스', korean: '어제 밤에 열이 조금 있었는데 지금은 내렸어요', example: '아이 건강 상태 전달할 때' },
      { japanese: '食欲はありますか', reading: 'しょくよくはありますか', pronunciation: '쇼쿠요쿠와 아리마스카', korean: '식욕은 있나요?', example: '선생님이 아이 상태를 확인할 때' },
    ],
    deeper_reading: '일본 보육원(保育園)에서는 매일 아침 아이의 컨디션, 수면 상태, 식사 여부를 선생님에게 보고하는 것이 일반적입니다. 연락장(連絡帳=れんらくちょう)에도 적어야 해서, 기본적인 건강 관련 표현을 익혀두면 큰 도움이 됩니다.',
  },
  {
    id: 'nursery-02',
    series_id: 'nursery',
    series_name_jp: '保育園の日本語',
    series_name_kr: '육아·보육 일본어',
    number: 2,
    tag: '결석연락',
    scene_kr: '아이가 열이 나서 오늘 어린이집을 쉬게 해야 한다. 전화로 결석을 알려야 한다',
    scene_jp: '子どもが熱を出したので、今日は保育園を休ませる。電話で欠席を連絡しなければならない',
    character_name_jp: '先生',
    character_name_kr: '담임 선생님',
    character_emoji: '👩‍🏫',
    dialogue_jp: 'はい、○○保育園でございます。どうされましたか？',
    dialogue_kr: '네, ○○어린이집입니다. 어떻게 되셨나요?',
    vocab_word: '熱を出す',
    vocab_reading: 'ねつをだす',
    vocab_meaning: '열이 나다',
    vocab_example_jp: '「子どもが熱を出したので、保育園をお休みさせてください。」아이가 열이 나서 어린이집을 쉬게 해주세요.',
    vocab_example_kr: '熱を出す는 "열이 나다"의 일본식 표현입니다. 열이 있으면(熱がある)와 구별해서 알아두세요.',
    vocab_korea_compare: '한국에서는 보통 카톡 등으로 결석을 알리지만, 일본 보육원은 전화 연락이 일반적입니다. 어느 반인지, 이름, 이유를 순서대로 말하는 것이 예의입니다.',
    expressions: [
      { japanese: '○○組の○○の母です', reading: '○○くみの○○のははです', pronunciation: '○○구미노 ○○노 하하데스', korean: '○○반 ○○의 엄마입니다', example: '전화할 때 첫 마디로 소개' },
      { japanese: '今日は熱があるのでお休みさせていただきます', reading: 'きょうはねつがあるのでおやすみさせていただきます', pronunciation: '쿄-와 네쓰가 아루노데 오야스미사세테 이타다키마스', korean: '오늘은 열이 있어서 쉬게 하겠습니다', example: '결석 이유와 함께 알릴 때' },
      { japanese: 'ご迷惑をおかけします', reading: 'ごめいわくをおかけします', pronunciation: '고메이와쿠오 오카케시마스', korean: '폐를 끼쳐서 죄송합니다', example: '결석 연락 마무리 표현' },
    ],
    deeper_reading: '일본 보육원은 체온이 37.5도 이상이면 등원 거부가 일반적입니다. 결석 연락은 가능한 일찍, 등원 시간 전에 하는 것이 예의입니다. 열이 내린 뒤에도 보통 24시간은 집에서 쉬게 하는 것이 관례입니다.',
  },
  {
    id: 'nursery-03',
    series_id: 'nursery',
    series_name_jp: '保育園の日本語',
    series_name_kr: '육아·보육 일본어',
    number: 3,
    tag: '연락장',
    scene_kr: '어린이집 연락장(알림장)에 오늘 아이의 상태와 특이사항을 적어야 한다',
    scene_jp: '保育園の連絡帳に今日の子どもの状態と特記事項を書かなければならない',
    character_name_jp: '連絡帳',
    character_name_kr: '연락장',
    character_emoji: '📓',
    dialogue_jp: '昨夜は10時間ほどよく眠れました。朝ごはんもしっかり食べました。機嫌も良いです。',
    dialogue_kr: '어제 밤은 10시간 정도 잘 잤어요. 아침밥도 잘 먹었어요. 기분도 좋아요.',
    vocab_word: '連絡帳',
    vocab_reading: 'れんらくちょう',
    vocab_meaning: '연락장, 알림장',
    vocab_example_jp: '「連絡帳に睡眠時間と食事の記録を書く」(연락장에 수면 시간과 식사 기록을 적다)',
    vocab_example_kr: '保育園의 연락장은 하루에 한 번 아이의 수면·식사·기분·특이사항을 기록하는 노트입니다. 선생님도 원에서의 모습을 적어 돌려줍니다.',
    vocab_korea_compare: '한국 어린이집의 알림장과 같습니다. 다만 일본은 손으로 직접 쓰는 경우가 많고, 아직 앱 연락장으로 전환이 느린 편입니다.',
    expressions: [
      { japanese: 'よく眠れました', reading: 'よくねむれました', pronunciation: '요쿠 네무레마시타', korean: '잘 잤어요', example: '수면 상태 보고할 때' },
      { japanese: '食欲があります／ありません', reading: 'しょくよくがあります／ありません', pronunciation: '쇼쿠요쿠가 아리마스/아리마센', korean: '식욕이 있어요/없어요', example: '식사 상태 보고할 때' },
      { japanese: '機嫌が良いです／ぐずっています', reading: 'きげんがよいです／ぐずっています', pronunciation: '키겐가 요이데스/구쥿테이마스', korean: '기분이 좋아요/보채고 있어요', example: '아이 기분 상태 표현' },
    ],
    deeper_reading: '연락장은 선생님과의 비공식 소통 창구입니다. 짧게라도 매일 쓰는 것이 좋고, 모르는 한자가 있으면 히라가나로 써도 됩니다. 선생님도 원에서 있었던 일(お友達と仲良く遊んでいました 친구와 사이좋게 놀았습니다 등)을 적어줍니다.',
  },
  {
    id: 'nursery-04',
    series_id: 'nursery',
    series_name_jp: '保育園の日本語',
    series_name_kr: '육아·보육 일본어',
    number: 4,
    tag: '알레르기',
    scene_kr: '아이에게 달걀 알레르기가 있어서 입원 시 선생님에게 미리 알려야 한다',
    scene_jp: '子どもに卵アレルギーがあり、入園時に先生に事前に伝えなければならない',
    character_name_jp: '先生',
    character_name_kr: '담임 선생님',
    character_emoji: '👩‍🏫',
    dialogue_jp: 'アレルギーについて、今一度確認させてください。除去食の対応もしておりますので、ご安心ください。',
    dialogue_kr: '알레르기에 대해 다시 한번 확인할게요. 제거식 대응도 하고 있으니 안심하세요.',
    vocab_word: 'アレルギー',
    vocab_reading: 'アレルギー',
    vocab_meaning: '알레르기',
    vocab_example_jp: '「卵アレルギーがあるので、卵が入っている食品は食べられません。」달걀 알레르기가 있어서 달걀이 들어간 식품은 먹을 수 없어요.',
    vocab_example_kr: 'アレルギー는 독일어 Allergie에서 온 외래어입니다. 일본 보육원에서는 알레르기 정보를 가장 중요하게 관리하며, 연간 알레르기 면담이 있는 곳도 많습니다.',
    vocab_korea_compare: '한국과 마찬가지로 학교·어린이집에서 알레르기 조사를 합니다. 다만 일본은 「アレルギー対応食」(알레르기 대응식)을 원에서 별도로 제공하는 제도가 잘 갖춰져 있습니다.',
    expressions: [
      { japanese: '卵アレルギーがあります', reading: 'たまごアレルギーがあります', pronunciation: '타마고 아레루기-가 아리마스', korean: '달걀 알레르기가 있어요', example: '알레르기 종류 전달할 때' },
      { japanese: '○○を食べると蕁麻疹が出ます', reading: '○○をたべるとじんましんがでます', pronunciation: '○○오 타베루토 진마신가 데마스', korean: '○○을 먹으면 두드러기가 나요', example: '증상을 구체적으로 설명할 때' },
      { japanese: 'エピペンを持っています', reading: 'エピペンをもっています', pronunciation: '에피펜오 못테이마스', korean: '에피펜을 가지고 있어요', example: '중증 알레르기의 경우' },
    ],
    deeper_reading: '일본 보육원의 알레르기 대응은 법적으로 의무화되어 있습니다. 입원 시 「生活管理指導表」(생활 관리 지도표)를 의사에게 받아 제출해야 합니다. 주요 알레르기 식품(特定原材料)은 7가지: 달걀·우유·밀·새우·게·땅콩·메밀입니다.',
  },
  {
    id: 'nursery-05',
    series_id: 'nursery',
    series_name_jp: '保育園の日本語',
    series_name_kr: '육아·보육 일본어',
    number: 5,
    tag: '행사참여',
    scene_kr: '어린이집 운동회에 참가하러 왔다. 다른 학부모들과 인사하고 행사를 즐긴다',
    scene_jp: '保育園の運動会に参加しに来た。他の保護者たちと挨拶して行事を楽しむ',
    character_name_jp: '保護者',
    character_name_kr: '다른 학부모',
    character_emoji: '👨‍👩‍👧',
    dialogue_jp: 'うちの子、すごく楽しみにしていたんですよ。お子さんはどのクラスですか？',
    dialogue_kr: '우리 아이가 엄청 기대하고 있었어요. 자녀분은 어느 반이에요?',
    vocab_word: '運動会',
    vocab_reading: 'うんどうかい',
    vocab_meaning: '운동회, 체육대회',
    vocab_example_jp: '「今年の運動会は雨天中止になりました。」올해 운동회는 우천 취소가 됐어요.',
    vocab_example_kr: '일본 보육원·초등학교의 운동회는 주로 가을(10월)에 열립니다. 학부모도 함께 참여하는 종목이 있어서, 아이들뿐 아니라 가족 행사로 즐깁니다.',
    vocab_korea_compare: '한국의 운동회와 비슷하지만, 일본은 장소를 선점하기 위해 아침 일찍부터 줄을 서는(場所取り=바쇼토리) 문화가 있습니다. 도시락(お弁当)을 싸 오는 것도 중요한 부분입니다.',
    expressions: [
      { japanese: 'うちの子、○○組です', reading: 'うちのこ、○○くみです', pronunciation: '우치노 코, ○○구미데스', korean: '저희 애는 ○○반이에요', example: '다른 학부모와 대화할 때 소개' },
      { japanese: '一緒に応援しましょう', reading: 'いっしょにおうえんしましょう', pronunciation: '잇쇼니 오-엔시마쇼', korean: '같이 응원해요', example: '학부모끼리 친해질 때' },
      { japanese: 'お疲れさまでした', reading: 'おつかれさまでした', pronunciation: '오쓰카레사마데시타', korean: '수고하셨어요', example: '행사가 끝나고 선생님·학부모께' },
    ],
    deeper_reading: '일본 어린이집 행사에 참여하면 다른 학부모와 知り合い(지인)가 될 기회입니다. 「よろしくお願いします」와 함께 자녀의 이름·반을 소개하는 것이 기본입니다. 행사 후 先生への感謝(선생님께 감사)도 잊지 마세요.',
  },
]

export const NATIVELIKE_EPISODES: Episode[] = [
  {
    id: 'nativelike-01',
    series_id: 'nativelike',
    series_name_jp: '現地人みたいに話そう',
    series_name_kr: '현지인처럼 말하기',
    number: 1,
    tag: '일상',
    scene_kr: '편의점 계산대에서 점원이 "봉투 필요하세요?"라고 물어본다. "괜찮아요"를 大丈夫です로 번역하면 생기는 혼선',
    scene_jp: 'コンビニのレジで店員さんに「袋はご入用ですか？」と聞かれた。「괜찮아요(大丈夫です)」と答えると…',
    character_name_jp: '店員さん',
    character_name_kr: '편의점 점원',
    character_emoji: '🏪',
    dialogue_jp: '袋はご入用ですか？ — 大丈夫です。（？） → よりクリアに「結構です」「いただきます」と言えると◎',
    dialogue_kr: '봉투 필요하세요? — 大丈夫です라고 하면 점원이 잠깐 멈칫합니다. 필요 없을 땐 「結構です」, 필요할 땐 「お願いします」가 훨씬 명확해요.',
    vocab_word: '大丈夫',
    vocab_reading: 'だいじょうぶ',
    vocab_meaning: '괜찮다 / 문제없다',
    vocab_example_jp: '「大丈夫ですか？」は相手を心配して聞く表現。断りの意味では「結構です」が自然。',
    vocab_example_kr: '大丈夫です는 "괜찮다"는 뜻이지만, 거절할 때는 結構です가 더 명확합니다. 大丈夫です만으로 거절 의사를 전하면 점원이 "받겠다는 건지 아닌지" 헷갈릴 수 있어요.',
    vocab_korea_compare: '한국에서 "괜찮아요"는 수락·거절 양쪽으로 쓰지만, 일본어에서는 목적에 맞게 다른 표현을 씁니다. 거절: 結構です / 수락: お願いします·いただきます.',
    expressions: [
      { japanese: '結構です', reading: 'けっこうです', pronunciation: '켓코-데스', korean: '됐어요 / 필요 없어요 (정중한 거절)', example: '봉투·영수증·추가 소스 등 거절할 때' },
      { japanese: 'お願いします', reading: 'おねがいします', pronunciation: '오네가이시마스', korean: '부탁드려요 / 주세요 (수락)', example: '봉투·서비스를 원할 때' },
      { japanese: '大丈夫です', reading: 'だいじょうぶです', pronunciation: '다이죠-부데스', korean: '괜찮아요 (걱정 마세요·수락 양쪽)', example: '걱정해주는 상대에게 "문제없어요" 할 때' },
    ],
    deeper_reading: '大丈夫 자체는 틀린 표현이 아닙니다. 다만 거절 맥락에서는 불명확해서 점원을 당황시킬 수 있어요. 일본 서비스업에서는 손님이 명확히 의사를 전달할수록 대화가 부드럽게 흘러갑니다. 結構です는 완곡하지만 명확한 거절이라 가장 많이 쓰입니다.',
  },
  {
    id: 'nativelike-02',
    series_id: 'nativelike',
    series_name_jp: '現地人みたいに話そう',
    series_name_kr: '현지인처럼 말하기',
    number: 2,
    tag: '직장',
    scene_kr: '회사에서 상사가 프로젝트 방향을 설명해준다. 공감을 표시하려고 なるほど를 반복했더니 왠지 분위기가 이상해졌다',
    scene_jp: '上司がプロジェクトの方向性を説明してくれる。「なるほど」を繰り返したら、なんか空気がおかしくなった…',
    character_name_jp: '田中部長',
    character_name_kr: '다나카 부장',
    character_emoji: '👔',
    dialogue_jp: '…というわけで、この方向で進めてほしいんだが。 — 「なるほど」（上司の眉がピクリと動く）',
    dialogue_kr: '…그런 방향으로 진행해줘. — なるほど（부장의 눈썹이 살짝 올라감） なるほど는 손아랫사람에게 쓰는 표현. 상사에게는 おっしゃる通りです가 안전해요.',
    vocab_word: 'なるほど',
    vocab_reading: 'なるほど',
    vocab_meaning: '그렇군요, 아하',
    vocab_example_jp: '「なるほど」は自分が評価・納得する際に使う表現。目上の人に使うと「自分が判断してあげてる」ニュアンスになる場合がある。',
    vocab_example_kr: 'なるほど는 "내가 상대방의 말을 평가·납득했다"는 뉘앙스가 있어서, 상사나 어른에게 쓰면 실례처럼 들릴 수 있습니다. 비즈니스 자리에서는 조심해야 해요.',
    vocab_korea_compare: '한국에서는 "그렇군요" "맞아요"를 윗사람에게도 자연스럽게 씁니다. 일본은 경어 체계가 복잡해서 공감 표현도 위아래에 따라 다르게 씁니다.',
    expressions: [
      { japanese: 'おっしゃる通りです', reading: 'おっしゃるとおりです', pronunciation: '옷샤루 토오-리데스', korean: '말씀하신 대로예요 (상사에게 공감)', example: '상사·어른의 의견에 동의할 때' },
      { japanese: '確かにそうですね', reading: 'たしかにそうですね', pronunciation: '타시카니 소-데스네', korean: '정말 그렇네요 (동료에게 공감)', example: '동료와 대화에서 동의' },
      { japanese: 'よくわかりました', reading: 'よくわかりました', pronunciation: '요쿠 와카리마시타', korean: '잘 이해했습니다', example: '설명을 듣고 납득했을 때' },
    ],
    deeper_reading: '2012년 NHK 방송문화연구소 조사에서 なるほど를 비즈니스 자리에서 쓰는 건 실례라는 견해가 많았습니다. 시대에 따라 의식은 변하지만, 상사와의 첫 대면에서는 おっしゃる通りです를 쓰는 것이 무난합니다. 친한 동료 사이에서는 なるほど도 자연스럽습니다.',
  },
  {
    id: 'nativelike-03',
    series_id: 'nativelike',
    series_name_jp: '現地人みたいに話そう',
    series_name_kr: '현지인처럼 말하기',
    number: 3,
    tag: '식당·카페',
    scene_kr: '레스토랑에서 물을 요청한다. 「水をください」라고 했더니 통하긴 했지만, 뭔가 딱딱한 느낌이 들었다',
    scene_jp: 'レストランで水をお願いしたい。「水をください」で通じたけど、なんか固い感じ…',
    character_name_jp: 'ウェイター',
    character_name_kr: '웨이터',
    character_emoji: '🍽️',
    dialogue_jp: '（ウェイターが来た）お水いただけますか？ — かしこまりました。少々お待ちください。',
    dialogue_kr: '（웨이터가 왔다）お水いただけますか？ — 알겠습니다. 잠시 기다려 주세요. ください보다 いただけますか가 부드럽고 세련된 인상을 줍니다.',
    vocab_word: 'いただく',
    vocab_reading: 'いただく',
    vocab_meaning: '받다 (謙譲語・겸양어)',
    vocab_example_jp: '「～をいただけますか？」は「～をもらえますか？」の丁寧な形。レストランや職場でよく使う。',
    vocab_example_kr: 'いただけますか는 "받을 수 있을까요?"의 겸양 형태입니다. ください(주세요)보다 한 단계 부드러운 요청으로, 레스토랑·직장에서 세련된 인상을 줍니다.',
    vocab_korea_compare: '한국어 "주세요"는 위아래 없이 쓰지만, 일본어는 요청 강도에 따라 ください / もらえますか / いただけますか로 나뉩니다. 서비스업에서는 いただけますか가 가장 자연스럽습니다.',
    expressions: [
      { japanese: 'お水いただけますか', reading: 'おみずいただけますか', pronunciation: '오미즈 이타다케마스카', korean: '물 주시겠어요? (레스토랑에서 가장 자연스러운 요청)', example: '음식점에서 물·서비스 요청' },
      { japanese: '～をお願いできますか', reading: '～をおねがいできますか', pronunciation: '～오 오네가이 데키마스카', korean: '～을 부탁드릴 수 있을까요?', example: '직장에서 업무 요청' },
      { japanese: '～をください', reading: '～をください', pronunciation: '～오 쿠다사이', korean: '～주세요 (직접적)', example: '가게에서 상품 요청, 다소 직접적' },
    ],
    deeper_reading: '일본어 요청 표현은 층위가 있습니다: ください(보통) → もらえますか(부드러움) → いただけますか(공손) → いただけますでしょうか(매우 공손). 레스토랑과 서비스 상황에서는 いただけますか가 세련되고 자연스럽습니다. 직접 ください라고 해도 무례하지는 않지만, 일본인에게는 약간 단도직입적으로 들릴 수 있습니다.',
  },
  {
    id: 'nativelike-04',
    series_id: 'nativelike',
    series_name_jp: '現地人みたいに話そう',
    series_name_kr: '현지인처럼 말하기',
    number: 4,
    tag: '일상',
    scene_kr: '지하철에서 실수로 옆 사람의 발을 밟았다. 반사적으로 「ごめんなさい」라고 했는데, 가볍게 부딪혔을 땐 すみません이 더 자연스럽다고 한다',
    scene_jp: '電車で隣の人の足を踏んでしまった。「ごめんなさい」と言ったが、軽い場合は「すみません」の方が自然らしい…',
    character_name_jp: '乗客',
    character_name_kr: '다른 승객',
    character_emoji: '🚇',
    dialogue_jp: '（足を踏む）あ、すみません！ — あ、大丈夫ですよ。',
    dialogue_kr: '（발을 밟음）아, すみません! — 아, 괜찮아요. 가볍게 부딪혔을 땐 すみません, 진심으로 사과할 때는 ごめんなさい, 공식적인 자리에서는 申し訳ありません을 씁니다.',
    vocab_word: 'すみません',
    vocab_reading: 'すみません',
    vocab_meaning: '실례합니다 / 가벼운 사과',
    vocab_example_jp: '「すみません」は軽い謝罪・呼びかけ両方に使える万能表現。「ごめんなさい」は心からの謝罪。',
    vocab_example_kr: 'すみません은 사과뿐 아니라 "저기요"(주의 환기)에도 씁니다. ごめんなさい는 개인적이고 진심 어린 사과, 申し訳ありません은 공식적이고 무거운 사과입니다.',
    vocab_korea_compare: '한국에서는 "미안해요" 하나로 다 해결되지만, 일본은 상황 무게에 따라 사과 표현이 달라집니다. すみません(가벼움) → ごめんなさい(진지함) → 申し訳ありません(공식).',
    expressions: [
      { japanese: 'すみません', reading: 'すみません', pronunciation: '스미마센', korean: '실례합니다 / 죄송합니다 (가벼운 사과·주의 환기)', example: '가볍게 부딪히거나 점원 부를 때' },
      { japanese: 'ごめんなさい', reading: 'ごめんなさい', pronunciation: '고멘나사이', korean: '미안해요 (개인적이고 진지한 사과)', example: '친한 관계에서 진심으로 사과할 때' },
      { japanese: '申し訳ありません', reading: 'もうしわけありません', pronunciation: '모-시와케 아리마센', korean: '진심으로 죄송합니다 (가장 격식 있는 사과)', example: '직장·공식 자리에서 사과' },
    ],
    deeper_reading: 'すみません은 원래 "해소되지 않는다"는 뜻으로, 폐를 끼쳐 마음의 빚이 생겼다는 뉘앙스입니다. ごめんなさい는 "용서해주세요"의 의미로 더 감정적입니다. 비즈니스 자리에서 실수했을 때 ごめんなさい를 쓰면 다소 유아적으로 들릴 수 있으니, 申し訳ありません 또는 失礼しました를 씁니다.',
  },
  {
    id: 'nativelike-05',
    series_id: 'nativelike',
    series_name_jp: '現地人みたいに話そう',
    series_name_kr: '현지인처럼 말하기',
    number: 5,
    tag: '직장',
    scene_kr: '퇴근하는 부장님을 만났다. "수고하세요"를 일본어로 하려고 ご苦労様です라고 했더니 선배가 황급히 말렸다',
    scene_jp: '帰る部長に会った。「수고하세요」を「ご苦労様です」と言ったら先輩に止められた…',
    character_name_jp: '先輩社員',
    character_name_kr: '선배 직원',
    character_emoji: '👩‍💼',
    dialogue_jp: '（帰る部長に）お疲れ様でございます。— いや～ようやく帰れるよ（と部長が笑う）',
    dialogue_kr: '（퇴근하는 부장에게）お疲れ様でございます. — 이야~ 드디어 퇴근이네（부장이 웃음）. ご苦労様は 상위→하위 방향의 표현이라, 부하가 상사에게 쓰면 실례입니다.',
    vocab_word: 'お疲れ様',
    vocab_reading: 'おつかれさま',
    vocab_meaning: '수고하셨어요',
    vocab_example_jp: '「お疲れ様です」は上下どちらにも使える。「ご苦労様」は上が下に言う表現なので要注意。',
    vocab_example_kr: 'お疲れ様です는 위아래 모두에게 쓸 수 있는 안전한 표현입니다. ご苦労様는 상사가 부하에게 쓰는 표현이어서, 부하가 상사에게 쓰면 실례입니다.',
    vocab_korea_compare: '한국에서 "수고하세요/수고하셨어요"는 누구에게나 쓸 수 있습니다. 일본은 ご苦労様(위→아래)와 お疲れ様(어디든 OK)의 방향이 다릅니다. 모르면 항상 お疲れ様를 쓰세요.',
    expressions: [
      { japanese: 'お疲れ様です', reading: 'おつかれさまです', pronunciation: '오쓰카레사마데스', korean: '수고하세요 (동료·상사 모두에게 OK)', example: '출퇴근·업무 중 마주칠 때' },
      { japanese: 'お疲れ様でございます', reading: 'おつかれさまでございます', pronunciation: '오쓰카레사마 데고자이마스', korean: '수고하셨습니다 (더 공손한 형태)', example: '임원·중요 인물에게' },
      { japanese: 'ご苦労様です', reading: 'ごくろうさまです', pronunciation: '고쿠로-사마데스', korean: '수고했어요 (상사→부하에게만)', example: '자기보다 아래인 사람에게만 사용' },
    ],
    deeper_reading: 'ご苦労様의 실례 여부는 세대에 따라 의견이 갈립니다. 젊은 세대 중에는 크게 신경 쓰지 않는 분도 있지만, 보수적인 직장이나 연배 있는 상사에게는 반드시 お疲れ様を써야 합니다. 모를 때는 항상 お疲れ様를 선택하세요.',
  },
  {
    id: 'nativelike-06',
    series_id: 'nativelike',
    series_name_jp: '現地人みたいに話そう',
    series_name_kr: '현지인처럼 말하기',
    number: 6,
    tag: '일상',
    scene_kr: '친구가 선물을 줬다. 감사 인사를 하며 「受け取ります」라고 했더니 친구가 웃었다. 뭐가 이상한 걸까?',
    scene_jp: '友達がプレゼントをくれた。「受け取ります」と言ったら笑われた。何がおかしいの？',
    character_name_jp: '友達',
    character_name_kr: '친구',
    character_emoji: '🎁',
    dialogue_jp: 'はい、これ！ — わあ、ありがとう！いただきます（と受け取る）',
    dialogue_kr: '자, 이거! — 와, 고마워! いただきます（받으면서）. 물건이나 호의를 받을 때는 いただきます가 자연스럽습니다. 受け取ります는 "수령합니다"라는 사무적인 뉘앙스.',
    vocab_word: 'いただく',
    vocab_reading: 'いただく',
    vocab_meaning: '받다 / 먹다 (겸양어)',
    vocab_example_jp: '「いただきます」は食事の前だけでなく、物を受け取る時にも使える謙譲表現。',
    vocab_example_kr: 'いただきます는 밥 먹기 전 인사로만 알고 있지만, 선물이나 호의를 받을 때도 자연스럽게 쓸 수 있는 겸양 표현입니다. 受け取ります는 사무적·법적 맥락에서 쓰는 표현.',
    vocab_korea_compare: '한국어 "받겠습니다"는 무난하지만 일본어 受け取ります는 다소 딱딱합니다. 선물·호의를 받을 때는 いただきます, 고마운 마음을 담아 ありがとうございます를 함께 쓰는 게 자연스럽습니다.',
    expressions: [
      { japanese: 'いただきます', reading: 'いただきます', pronunciation: '이타다키마스', korean: '잘 받겠습니다 / 잘 먹겠습니다 (겸양)', example: '선물·음식·호의를 받을 때' },
      { japanese: 'ありがとうございます', reading: 'ありがとうございます', pronunciation: '아리가토-고자이마스', korean: '감사합니다', example: '뭐든 받았을 때 함께 쓰기' },
      { japanese: '受け取ります', reading: 'うけとります', pronunciation: '우케토리마스', korean: '수령하겠습니다 (사무적)', example: '서류·택배 수령 등 공식 맥락에서' },
    ],
    deeper_reading: 'いただく는 원래 "머리 위에 올린다"는 뜻으로, 받는 행위를 높임말로 표현합니다. 食事の前の「いただきます」도 같은 어원으로, 음식을 주신 존재(자연·동물·농부)에 대한 경의를 담은 표현입니다. 일본 문화의 겸양 의식이 담긴 아름다운 표현입니다.',
  },
  {
    id: 'nativelike-07',
    series_id: 'nativelike',
    series_name_jp: '現地人みたいに話そう',
    series_name_kr: '현지인처럼 말하기',
    number: 7,
    tag: '일상',
    scene_kr: '일본인 동료에게 "알겠습니다"를 전하고 싶어서 「わかります」라고 했다. 근데 상대방이 의아한 표정을 지었다',
    scene_jp: '日本人の同僚に「わかりました」を伝えたくて「わかります」と言ってしまった。相手が怪訝な顔を…',
    character_name_jp: '同僚',
    character_name_kr: '동료',
    character_emoji: '🤝',
    dialogue_jp: 'この作業、お願いできる？ — わかりました、やっておきます。',
    dialogue_kr: '이 작업, 부탁해도 될까? — わかりました, 해둘게요. 이해·납득했을 때는 わかりました(과거형). わかります는 "이해할 수 있다(능력)"의 뜻입니다.',
    vocab_word: 'わかりました',
    vocab_reading: 'わかりました',
    vocab_meaning: '알겠습니다 (납득·수락)',
    vocab_example_jp: '「わかりました」は理解・納得を示す。「わかります」は「理解できる能力がある」という意味になる。',
    vocab_example_kr: 'わかりました는 "방금 이해했다"는 완료의 의미입니다. 반면 わかります는 "이해할 수 있다"는 능력 표현으로, "알겠습니다"의 의미로 쓰면 어색합니다. 한국어 "알겠어요"는 항상 わかりました로 번역하세요.',
    vocab_korea_compare: '한국어 "알아요"와 "알겠어요"는 모두 "알다"이지만 뉘앙스가 다르듯, 일본어도 知っています(이미 알고 있음) / わかりました(방금 이해함) / 承知しました(공식 수락)을 구분합니다.',
    expressions: [
      { japanese: 'わかりました', reading: 'わかりました', pronunciation: '와카리마시타', korean: '알겠습니다 (방금 이해·수락)', example: '지시·설명을 듣고 납득했을 때' },
      { japanese: '承知しました', reading: 'しょうちしました', pronunciation: '쇼-치시마시타', korean: '알겠습니다 (공식·직장에서 더 격식 있는 수락)', example: '상사 지시 수락, 업무 메일' },
      { japanese: '了解しました', reading: 'りょうかいしました', pronunciation: '료-카이시마시타', korean: '이해했습니다 (동료 수준에서)', example: '동료 간 소통, 일부 비즈니스 자리에서' },
    ],
    deeper_reading: '承知しました와 了解しました의 차이도 미묘합니다. 엄격한 비즈니스 에티켓에서는 了解しました가 동급·하급에게 쓰는 표현이라 상사에게는 承知しました를 권장합니다. 일상적인 직장에서는 わかりました로 충분합니다.',
  },
  {
    id: 'nativelike-08',
    series_id: 'nativelike',
    series_name_jp: '現地人みたいに話そう',
    series_name_kr: '현지인처럼 말하기',
    number: 8,
    tag: '일상',
    scene_kr: '친구에게 남자친구 이야기를 할 때, 「うちの彼氏はとても優しいです」라고 했다. 자랑스럽게 말했는데 친구가 살짝 웃었다',
    scene_jp: '友達に彼氏の話をする時、「うちの彼氏はとても優しいです」と言ったら友達が少し笑った…',
    character_name_jp: '友達',
    character_name_kr: '친구',
    character_emoji: '😊',
    dialogue_jp: '彼氏、すごく優しくてさあ、いつも気を遣ってくれるんだよね。',
    dialogue_kr: '남자친구가 정말 다정해서, 항상 배려해줘. 일본어 회화에서는 とても보다 すごく, 문장 끝은 丁寧体(데스마스)보다 普通体(반말체)가 친구 사이에서 자연스럽습니다.',
    vocab_word: 'すごく',
    vocab_reading: 'すごく',
    vocab_meaning: '엄청, 굉장히 (회화체)',
    vocab_example_jp: '「とても」は書き言葉的。会話では「すごく」「めちゃくちゃ」がより自然に聞こえる。',
    vocab_example_kr: 'とても는 교과서·문어체에서 많이 나와서 한국인이 많이 씁니다. 실제 회화에서는 すごく, めちゃ(くちゃ), かなり가 훨씬 자연스럽습니다.',
    vocab_korea_compare: '한국어도 "매우"보다 "엄청" "되게"가 일상 대화에서 자연스럽듯, 일본어도 とても(매우)보다 すごく(엄청)가 회화에서 더 자주 쓰입니다.',
    expressions: [
      { japanese: 'すごく～', reading: 'すごく～', pronunciation: '스고쿠~', korean: '엄청 ~ (일상 회화 강조)', example: 'すごく嬉しい, すごく美味しい 등' },
      { japanese: 'めちゃ（くちゃ）～', reading: 'めちゃ（くちゃ）～', pronunciation: '메차(쿠챠)~', korean: '진짜 ~ (캐주얼 강조)', example: '친한 친구 사이에서 강한 감탄' },
      { japanese: 'かなり～', reading: 'かなり～', pronunciation: '카나리~', korean: '상당히 ~ (약간 격식 있는 강조)', example: 'かなり難しい, かなり大変 등' },
    ],
    deeper_reading: '구어체(話し言葉)와 문어체(書き言葉)의 차이는 자연스러운 일본어의 핵심입니다. とても·非常に는 문어·격식 자리에서 쓰고, 일상 대화에서는 すごく·めちゃ가 자연스럽습니다. 또한 친구 사이에서 모든 문장을 です·ます로 끝내면 거리감이 느껴질 수 있습니다.',
  },
  {
    id: 'nativelike-09',
    series_id: 'nativelike',
    series_name_jp: '現地人みたいに話そう',
    series_name_kr: '현지인처럼 말하기',
    number: 9,
    tag: '일상',
    scene_kr: '친구에게 선물을 줬다. 「これ、あなたにあげます」라고 했더니 뭔가 어색한 반응이 왔다. あなた 사용이 문제였을까?',
    scene_jp: '友達にプレゼントを渡した。「これ、あなたにあげます」と言ったら何か変な反応が…「あなた」の使い方が問題？',
    character_name_jp: '友達',
    character_name_kr: '친구',
    character_emoji: '👫',
    dialogue_jp: 'はい、これ！よかったら使って。 — え、くれるの？ありがとう！',
    dialogue_kr: '자, 이거! 마음에 들면 써봐. — 어, 나한테 주는 거야? 고마워! 일본어에서 あなた는 낯선 사람·가사 가사에서나 쓰고, 친구에게는 이름+さん이나 아예 생략하는 게 자연스럽습니다.',
    vocab_word: 'あなた',
    vocab_reading: 'あなた',
    vocab_meaning: '당신 (실제 대화에서는 잘 안 씀)',
    vocab_example_jp: '「あなた」は書き言葉・歌詞では普通。でも日常会話では名前や「君」「お前」を使うか省略が自然。',
    vocab_example_kr: 'あなた는 한국어 "당신"과 달리, 일본어 일상 대화에서 쓰면 다소 딱딱하거나 냉랭하게 들립니다. 친한 사이에서는 이름을 부르거나 아예 생략하는 게 자연스럽습니다.',
    vocab_korea_compare: '한국어 "당신"도 실제로 잘 안 쓰듯, 일본어 あなた도 마찬가지입니다. 일본인은 상대방의 이름·직함을 호칭으로 쓰거나(山田さん、先生), 주어 자체를 생략합니다.',
    expressions: [
      { japanese: '（名前）さん', reading: '（なまえ）さん', pronunciation: '(이름)상', korean: '(이름)씨 / 상대방 이름으로 호칭', example: '친한 정도에 따라 さん·ちゃん·くん 조절' },
      { japanese: '（主語省略）', reading: '', pronunciation: '', korean: '주어 생략이 가장 자연스러움', example: 'これ、よかったら使って（あなたに、는 생략）' },
      { japanese: 'あなた', reading: 'あなた', pronunciation: '아나타', korean: '당신 (부부 사이·가사·낯선 상대에게)', example: '아내→남편 호칭, 노래 가사, 공식 문서' },
    ],
    deeper_reading: '일본어는 주어 생략이 매우 자연스러운 언어입니다. 「これ、使って」(이거 써)처럼 주어 없이 말해도 문맥으로 충분히 전달됩니다. 오히려 모든 문장에 주어를 넣으면 번역체처럼 들릴 수 있습니다. 자연스러운 일본어의 첫걸음은 "안 써도 되는 주어는 생략하기"입니다.',
  },
  {
    id: 'nativelike-10',
    series_id: 'nativelike',
    series_name_jp: '現地人みたいに話そう',
    series_name_kr: '현지인처럼 말하기',
    number: 10,
    tag: '일상',
    scene_kr: '친구에게 "저는 김치가 좋아요"를 일본어로 말하려다 「私はキムチがが好きです」라고 실수했다. は와 が를 어떻게 구분할까?',
    scene_jp: '友達に「私はキムチが好きです」と言おうとして、は와 が의 구분で混乱してしまった…',
    character_name_jp: '友達',
    character_name_kr: '친구',
    character_emoji: '🥬',
    dialogue_jp: '何か好きな韓国料理ある？ — キムチが好き！あとビビンバも。',
    dialogue_kr: '좋아하는 한국 음식 있어? — キムチが好き! 비빔밥도. は는 "주제 설정"이고, が는 "바로 이것"의 강조·대비입니다. 好き·嫌い·上手·下手 앞에는 が가 오는 게 기본.',
    vocab_word: 'は / が',
    vocab_reading: 'は（wa）/ が',
    vocab_meaning: '은/는 (주제) / 이/가 (주어·강조)',
    vocab_example_jp: '「私はキムチが好きです」→ 私はは主題マーカー、キムチがは好きの対象を示すが。',
    vocab_example_kr: 'は는 "~에 대해 말하자면"의 주제 표시이고, が는 특정 대상을 부각시키는 주어입니다. 好きです(좋아하다)·できます(할 수 있다) 앞에는 が가 옵니다.',
    vocab_korea_compare: '한국어 은/는과 이/가가 동일하게 は와 が로 대응되지 않습니다. 한국어는 강조·대비에서 이/가를 쓰지만, 일본어는 が를 "처음 등장하는 정보" "질문의 답" "감정·능력의 대상"에도 씁니다.',
    expressions: [
      { japanese: 'キムチが好きです', reading: 'キムチがすきです', pronunciation: '김치가 스키데스', korean: '김치를 좋아해요 (好き·嫌い 앞은 が)', example: '好き·嫌い·上手·下手 앞은 항상 が' },
      { japanese: '私は学生です', reading: 'わたしはがくせいです', pronunciation: '와타시와 각세이데스', korean: '저는 학생입니다 (주제 は)', example: '자기 소개, 상태 설명에 は' },
      { japanese: '誰が来ましたか', reading: 'だれがきましたか', pronunciation: '다레가 키마시타카', korean: '누가 왔어요? (의문·초점은 が)', example: '모르는 정보를 묻는 의문문에 が' },
    ],
    deeper_reading: 'は와 が는 일본어 학습자가 가장 오래 고민하는 주제입니다. 핵심 원칙: は는 "이미 알고 있는 주제"를, が는 "새로운 정보·강조·감정·능력의 대상"을 표시합니다. 好きです·できます·あります처럼 감정·존재·능력을 나타내는 표현 앞에는 が가 기본입니다. 완벽히 이해하려면 시간이 필요하지만, 이 패턴부터 익히면 절반은 해결됩니다.',
  },
]

export function getEpisodesBySeriesId(seriesId: string) {
  return [...EPISODES, ...OFFICE_EPISODES, ...HOSPITAL_EPISODES, ...SHOPPING_EPISODES, ...NURSERY_EPISODES, ...NATIVELIKE_EPISODES].filter((e) => e.series_id === seriesId).sort((a, b) => a.number - b.number)
}

export function getEpisodeById(id: string) {
  return [...EPISODES, ...OFFICE_EPISODES, ...HOSPITAL_EPISODES, ...SHOPPING_EPISODES, ...NURSERY_EPISODES, ...NATIVELIKE_EPISODES].find((e) => e.id === id)
}
