export type KanjiCategory = '자연' | '사람' | '숫자' | '시간' | '일상' | '방향'
export type JLPTLevel = 'N5' | 'N4'

export interface RelatedWord {
  word: string
  reading: string
  pronunciation: string
  meaning: string
}

export interface KanjiEntry {
  id: string
  kanji: string
  reading_on: string
  reading_kun: string
  pronunciation_on: string
  pronunciation_kun: string
  meaning_kr: string
  stroke_count: number
  jlpt: JLPTLevel
  category: KanjiCategory
  origin_story: string
  visual_hint: string
  mnemonic: string
  related_words: RelatedWord[]
}

export const KANJI_CATEGORIES: KanjiCategory[] = ['자연', '사람', '숫자', '시간', '일상', '방향']

export const CATEGORY_COLORS: Record<KanjiCategory, string> = {
  자연: '#27ae60',
  사람: '#2980b9',
  숫자: '#e74c3c',
  시간: '#8e44ad',
  일상: '#e67e22',
  방향: '#16a085',
}

export const KANJI_LIST: KanjiEntry[] = [
  // ── 자연 ──────────────────────────────────────────────────────────────
  {
    id: 'k-001',
    kanji: '山',
    reading_on: 'サン',
    reading_kun: 'やま',
    pronunciation_on: '산',
    pronunciation_kun: '야마',
    meaning_kr: '산',
    stroke_count: 3,
    jlpt: 'N5',
    category: '자연',
    origin_story: '세 개의 봉우리가 솟아오른 산의 스카이라인을 그대로 본뜬 상형문자입니다. 약 3,000년 전 갑골문(甲骨文)에서도 지금과 거의 같은 모습이었어요. 가운데 봉우리가 가장 높고, 양쪽이 조금 낮은 전형적인 산의 실루엣입니다.',
    visual_hint: '위로 뾰족뾰족 솟아오른 세 개의 봉우리 ⛰️ — 그냥 산 모양 그대로!',
    mnemonic: '한국어 "산"과 음독 "サン"이 완전히 같아요! 보이는 모습도 산, 읽는 것도 산!',
    related_words: [
      { word: '山道', reading: 'やまみち', pronunciation: '야마미치', meaning: '산길' },
      { word: '火山', reading: 'かざん', pronunciation: '카잔', meaning: '화산' },
      { word: '富士山', reading: 'ふじさん', pronunciation: '후지산', meaning: '후지산' },
    ],
  },
  {
    id: 'k-002',
    kanji: '川',
    reading_on: 'セン',
    reading_kun: 'かわ',
    pronunciation_on: '센',
    pronunciation_kun: '카와',
    meaning_kr: '강, 내',
    stroke_count: 3,
    jlpt: 'N5',
    category: '자연',
    origin_story: '강물이 흐르는 세 줄기를 위에서 내려다본 모습입니다. 가운데 주류와 양옆으로 흐르는 물줄기를 세 개의 세로선으로 표현했어요. 고대인들이 강을 하늘에서 내려다보며 그대로 그린 직관적인 그림입니다.',
    visual_hint: '세 개의 세로선 | | | — 강물이 나란히 흘러 내려가는 모습!',
    mnemonic: '"카와"는 강줄기 세 개. 川崎(카와사키)·品川(시나가와)처럼 지명에도 자주 나와요!',
    related_words: [
      { word: '川岸', reading: 'かわぎし', pronunciation: '카와기시', meaning: '강기슭' },
      { word: '小川', reading: 'おがわ', pronunciation: '오가와', meaning: '실개천' },
      { word: '品川', reading: 'しながわ', pronunciation: '시나가와', meaning: '시나가와(역 이름)' },
    ],
  },
  {
    id: 'k-003',
    kanji: '日',
    reading_on: 'ニチ・ジツ',
    reading_kun: 'ひ・か',
    pronunciation_on: '니치·지쓰',
    pronunciation_kun: '히·카',
    meaning_kr: '해, 날',
    stroke_count: 4,
    jlpt: 'N5',
    category: '자연',
    origin_story: '고대에는 동그란 원 안에 점 하나(☉)를 그려 태양을 표현했습니다. 대나무나 점토에 새기기 쉽도록 원이 사각형으로, 점이 가로선으로 변해 지금의 모습이 됐어요. 가운데 선은 태양 흑점 혹은 빛나는 핵을 상징합니다.',
    visual_hint: '창문 같은 사각형 안에 가로선 — 창문 너머로 햇빛이 쏟아지는 장면!',
    mnemonic: '"일(日)요일"의 일! 한국어 한자 그대로예요. 日本의 日도 바로 이 글자, "해(태양)의 나라"!',
    related_words: [
      { word: '今日', reading: 'きょう', pronunciation: '쿄-', meaning: '오늘' },
      { word: '毎日', reading: 'まいにち', pronunciation: '마이니치', meaning: '매일' },
      { word: '日本', reading: 'にほん', pronunciation: '니혼', meaning: '일본' },
    ],
  },
  {
    id: 'k-004',
    kanji: '月',
    reading_on: 'ゲツ・ガツ',
    reading_kun: 'つき',
    pronunciation_on: '게쓰·가쓰',
    pronunciation_kun: '쓰키',
    meaning_kr: '달, 월(月)',
    stroke_count: 4,
    jlpt: 'N5',
    category: '자연',
    origin_story: '초승달의 모양을 본뜬 상형문자입니다. 원래는 더 구부러진 달 모양이었는데, 쓰기 편하도록 약간 세워진 형태로 변했어요. 달이 차고 기우는 한 주기(약 29.5일)가 "한 달(月)"의 기원이 됩니다.',
    visual_hint: '한쪽으로 기울어진 네모 — 옆으로 세워진 반달 🌙 같은 모습!',
    mnemonic: '"월(月)요일"의 월! 一月=1월, 二月=2월… 숫자+月로 모든 달을 나타낼 수 있어요.',
    related_words: [
      { word: '今月', reading: 'こんげつ', pronunciation: '콘게쓰', meaning: '이번 달' },
      { word: '来月', reading: 'らいげつ', pronunciation: '라이게쓰', meaning: '다음 달' },
      { word: '月曜日', reading: 'げつようび', pronunciation: '게쓰요-비', meaning: '월요일' },
    ],
  },
  {
    id: 'k-005',
    kanji: '火',
    reading_on: 'カ',
    reading_kun: 'ひ',
    pronunciation_on: '카',
    pronunciation_kun: '히',
    meaning_kr: '불',
    stroke_count: 4,
    jlpt: 'N5',
    category: '자연',
    origin_story: '불꽃이 활활 타오르는 모습을 그린 상형문자입니다. 가운데 큰 불꽃 위로 작은 불씨들이 튀는 모습이 위쪽의 두 획으로 표현됩니다. 花火(불꽃놀이)는 "꽃 불"이라는 아름다운 이름이에요.',
    visual_hint: '위로 두 획이 튀어나온 모양 — 사람이 팔을 들고 불꽃을 흉내내는 모습 🔥!',
    mnemonic: '"화(火)재"의 화! 한국어 한자와 같아요. 火曜日=화요일, 花火=불꽃놀이!',
    related_words: [
      { word: '火曜日', reading: 'かようび', pronunciation: '카요-비', meaning: '화요일' },
      { word: '花火', reading: 'はなび', pronunciation: '하나비', meaning: '불꽃놀이' },
      { word: '火山', reading: 'かざん', pronunciation: '카잔', meaning: '화산' },
    ],
  },
  {
    id: 'k-006',
    kanji: '水',
    reading_on: 'スイ',
    reading_kun: 'みず',
    pronunciation_on: '스이',
    pronunciation_kun: '미즈',
    meaning_kr: '물',
    stroke_count: 4,
    jlpt: 'N5',
    category: '자연',
    origin_story: '강물이 중앙으로 흐르고 좌우로 물방울이 튀는 모습을 그린 상형문자입니다. 川(강)이 장소라면 水는 물 자체의 본질을 나타냅니다. 氵(삼수변)으로 다른 한자에 붙으면 "물과 관련 있다"는 의미를 더해줍니다.',
    visual_hint: '가운데 세로선에서 물방울이 좌우로 튀는 모습 💧',
    mnemonic: '"수(水)영장"의 수! 水曜日=수요일, 水泳(수이에이)=수영 — 한국어와 발음도 비슷해요!',
    related_words: [
      { word: '水曜日', reading: 'すいようび', pronunciation: '스이요-비', meaning: '수요일' },
      { word: '水泳', reading: 'すいえい', pronunciation: '스이에이', meaning: '수영' },
      { word: 'お水', reading: 'おみず', pronunciation: '오미즈', meaning: '물(정중한 표현)' },
    ],
  },
  {
    id: 'k-007',
    kanji: '木',
    reading_on: 'モク・ボク',
    reading_kun: 'き',
    pronunciation_on: '모쿠·보쿠',
    pronunciation_kun: '키',
    meaning_kr: '나무',
    stroke_count: 4,
    jlpt: 'N5',
    category: '자연',
    origin_story: '나무를 정면에서 본 모습입니다. 가운데 세로선은 줄기, 가로선은 가지, 아래 두 획은 땅속 뿌리를 표현해요. 木에서 뿌리를 강조하면 本(근본·책), 가지 끝을 강조하면 末(끝)이 됩니다.',
    visual_hint: '十자형 줄기에 두 다리 뿌리 — 나무가 두 발 굳건히 땅에 서 있는 모습!',
    mnemonic: '"목(木)요일"의 목! 木曜日=목요일. 木에서 뿌리 강조 = 本(근본), 나뭇가지 강조 = 末(끝)!',
    related_words: [
      { word: '木曜日', reading: 'もくようび', pronunciation: '모쿠요-비', meaning: '목요일' },
      { word: '木材', reading: 'もくざい', pronunciation: '모쿠자이', meaning: '목재' },
      { word: '並木道', reading: 'なみきみち', pronunciation: '나미키미치', meaning: '가로수길' },
    ],
  },

  // ── 사람 ──────────────────────────────────────────────────────────────
  {
    id: 'k-008',
    kanji: '人',
    reading_on: 'ジン・ニン',
    reading_kun: 'ひと',
    pronunciation_on: '진·닌',
    pronunciation_kun: '히토',
    meaning_kr: '사람',
    stroke_count: 2,
    jlpt: 'N5',
    category: '사람',
    origin_story: '두 다리로 걷는 사람의 모습을 옆에서 본 상형문자입니다. 갑골문에서는 더욱 생생하게 걷는 사람을 그렸는데, 점차 두 획으로 단순화됐어요. 外国人(외국인), 日本人(일본인)처럼 나라 이름 뒤에 붙어 "~사람"을 뜻합니다.',
    visual_hint: '두 획으로 그린 걷는 사람 🚶 — 한국어 자음 "ㅅ"처럼 다리 두 개!',
    mnemonic: '"인(人)간"의 인! 韓国人(칸코쿠진)=한국인, 外国人(가이코쿠진)=외국인으로 바로 쓸 수 있어요.',
    related_words: [
      { word: '日本人', reading: 'にほんじん', pronunciation: '니혼진', meaning: '일본인' },
      { word: '外国人', reading: 'がいこくじん', pronunciation: '가이코쿠진', meaning: '외국인' },
      { word: '人口', reading: 'じんこう', pronunciation: '진코-', meaning: '인구' },
    ],
  },
  {
    id: 'k-009',
    kanji: '口',
    reading_on: 'コウ・ク',
    reading_kun: 'くち',
    pronunciation_on: '코-·쿠',
    pronunciation_kun: '쿠치',
    meaning_kr: '입',
    stroke_count: 3,
    jlpt: 'N5',
    category: '사람',
    origin_story: '입을 크게 벌린 정면 모양을 그린 상형문자입니다. 사각형 하나가 열린 입의 윤곽을 나타냅니다. 말하기, 먹기, 노래하기 — 모든 것이 口에서 시작됩니다. 入口(입구)·出口(출구)처럼 통로를 나타낼 때도 씁니다.',
    visual_hint: '작은 사각형 □ — 그냥 입 모양 그대로!',
    mnemonic: '"구(口)강"의 구! 入口(이리구치)=입구, 出口(데구치)=출구 — 전철역에서 매일 보는 글자!',
    related_words: [
      { word: '入口', reading: 'いりぐち', pronunciation: '이리구치', meaning: '입구' },
      { word: '出口', reading: 'でぐち', pronunciation: '데구치', meaning: '출구' },
      { word: '人口', reading: 'じんこう', pronunciation: '진코-', meaning: '인구' },
    ],
  },
  {
    id: 'k-010',
    kanji: '手',
    reading_on: 'シュ',
    reading_kun: 'て',
    pronunciation_on: '슈',
    pronunciation_kun: '테',
    meaning_kr: '손',
    stroke_count: 4,
    jlpt: 'N5',
    category: '사람',
    origin_story: '손가락을 편 손을 위에서 바라본 모습입니다. 위의 세 획이 손가락들을, 아래 구부러진 선이 손목을 표현합니다. 日本語에서 "te"는 손뿐 아니라 기술·솜씨(上手=잘함, 下手=못함)도 의미해요.',
    visual_hint: '손가락 세 개와 손목이 달린 손 ✋ — 위에서 내려다본 모습!',
    mnemonic: '"수(手)화"의 수! 上手(조-즈)=잘함, 下手(헤타)=못함 — 칭찬할 때 바로 쓰는 표현!',
    related_words: [
      { word: '上手', reading: 'じょうず', pronunciation: '조-즈', meaning: '잘함, 능숙함' },
      { word: '下手', reading: 'へた', pronunciation: '헤타', meaning: '못함, 서툶' },
      { word: '手紙', reading: 'てがみ', pronunciation: '테가미', meaning: '편지' },
    ],
  },
  {
    id: 'k-011',
    kanji: '目',
    reading_on: 'モク・ボク',
    reading_kun: 'め',
    pronunciation_on: '모쿠·보쿠',
    pronunciation_kun: '메',
    meaning_kr: '눈',
    stroke_count: 5,
    jlpt: 'N5',
    category: '사람',
    origin_story: '눈을 정면에서 그린 상형문자입니다. 원래는 타원형으로 눈을 그렸는데, 서사 편의를 위해 90도 세워진 사각형으로 변했어요. 가운데 두 개의 가로선은 눈동자(흑백)와 눈꺼풀입니다.',
    visual_hint: '세로로 세워진 사각형에 가로선 두 개 — 눈을 세로로 세워놓은 모습 👁️!',
    mnemonic: '"목(目)격"의 목! 目上(메우에)=윗사람, 目下(메시타)=아랫사람 — 일본 직장에서 바로 쓰는 표현!',
    related_words: [
      { word: '目上', reading: 'めうえ', pronunciation: '메우에', meaning: '윗사람, 상급자' },
      { word: '目的', reading: 'もくてき', pronunciation: '모쿠테키', meaning: '목적' },
      { word: '注目', reading: 'ちゅうもく', pronunciation: '추-모쿠', meaning: '주목' },
    ],
  },
  {
    id: 'k-012',
    kanji: '大',
    reading_on: 'ダイ・タイ',
    reading_kun: 'おおきい',
    pronunciation_on: '다이·타이',
    pronunciation_kun: '오-키이',
    meaning_kr: '크다',
    stroke_count: 3,
    jlpt: 'N5',
    category: '사람',
    origin_story: '사람(人)이 두 팔을 크게 벌린 모습입니다. "이렇게 크다!"고 몸으로 직접 표현하는 제스처를 그림으로 그렸어요. 大丈夫(괜찮아요)는 "큰 어른 남자라면 걱정 없다"는 뜻에서 나온 표현입니다.',
    visual_hint: '팔다리 벌린 사람 🙆 — 大자가 바로 사람이 "크다!"고 표현하는 포즈!',
    mnemonic: '"대(大)학교"의 대! 大丈夫(다이죠-부)=괜찮아요 — 일본어에서 가장 자주 쓰는 표현 중 하나!',
    related_words: [
      { word: '大丈夫', reading: 'だいじょうぶ', pronunciation: '다이죠-부', meaning: '괜찮아요' },
      { word: '大学', reading: 'だいがく', pronunciation: '다이가쿠', meaning: '대학교' },
      { word: '大人', reading: 'おとな', pronunciation: '오토나', meaning: '어른' },
    ],
  },

  // ── 숫자 ──────────────────────────────────────────────────────────────
  {
    id: 'k-013',
    kanji: '一',
    reading_on: 'イチ・イツ',
    reading_kun: 'ひと',
    pronunciation_on: '이치·이쓰',
    pronunciation_kun: '히토',
    meaning_kr: '하나, 일(1)',
    stroke_count: 1,
    jlpt: 'N5',
    category: '숫자',
    origin_story: '가장 단순한 한자이자 가장 오래된 숫자 표현입니다. 고대 수메르, 이집트, 중국 모두 "하나"를 막대기 하나로 표현했어요. 인류 공통의 직관! 一番(이치반)은 "1등, 가장"이라는 의미로 매우 자주 씁니다.',
    visual_hint: '가로선 하나 — 더 설명이 필요 없는 막대기 1개!',
    mnemonic: '"일(一)요일"의 일! 一番(이치반)=제일, 一緒(잇쇼)=함께 — 가장 자주 쓰는 숫자!',
    related_words: [
      { word: '一番', reading: 'いちばん', pronunciation: '이치반', meaning: '제일, 1등' },
      { word: '一緒に', reading: 'いっしょに', pronunciation: '잇쇼니', meaning: '함께' },
      { word: '一つ', reading: 'ひとつ', pronunciation: '히토쓰', meaning: '한 개' },
    ],
  },
  {
    id: 'k-014',
    kanji: '二',
    reading_on: 'ニ',
    reading_kun: 'ふた',
    pronunciation_on: '니',
    pronunciation_kun: '후타',
    meaning_kr: '둘, 이(2)',
    stroke_count: 2,
    jlpt: 'N5',
    category: '숫자',
    origin_story: '막대기 두 개로 둘을 표현한 지사문자(指事文字)입니다. 一(하나)에 선 하나를 더한 형태. 위아래 두 선의 길이가 다르면 三과 헷갈리지 않도록, 二는 위아래 길이가 같습니다.',
    visual_hint: '가로선 두 개 = = — 막대기 두 개 뿐!',
    mnemonic: '"이(二)월"의 이! 二階(니카이)=2층 — 길을 물어볼 때 가장 먼저 쓰는 숫자!',
    related_words: [
      { word: '二階', reading: 'にかい', pronunciation: '니카이', meaning: '2층' },
      { word: '二つ', reading: 'ふたつ', pronunciation: '후타쓰', meaning: '두 개' },
      { word: '二人', reading: 'ふたり', pronunciation: '후타리', meaning: '두 사람' },
    ],
  },
  {
    id: 'k-015',
    kanji: '三',
    reading_on: 'サン',
    reading_kun: 'み・みっ',
    pronunciation_on: '산',
    pronunciation_kun: '미·밋',
    meaning_kr: '셋, 삼(3)',
    stroke_count: 3,
    jlpt: 'N5',
    category: '숫자',
    origin_story: '막대기 세 개로 셋을 표현한 지사문자입니다. 一, 二, 三은 선의 개수로 숫자를 나타냅니다. 四부터는 선이 많아져 헷갈리기 때문에 다른 방식으로 표현하게 됐어요.',
    visual_hint: '가로선 세 개 === — 삼성(三星)의 三!',
    mnemonic: '"삼(三)성"의 삼! 한국어 발음 "산"과 음독 "サン"이 완전히 같아요!',
    related_words: [
      { word: '三角', reading: 'さんかく', pronunciation: '산카쿠', meaning: '삼각형' },
      { word: '三つ', reading: 'みっつ', pronunciation: '밋쓰', meaning: '세 개' },
      { word: '三月', reading: 'さんがつ', pronunciation: '산가쓰', meaning: '3월' },
    ],
  },
  {
    id: 'k-016',
    kanji: '百',
    reading_on: 'ヒャク',
    reading_kun: 'もも',
    pronunciation_on: '햐쿠',
    pronunciation_kun: '모모',
    meaning_kr: '백(100)',
    stroke_count: 6,
    jlpt: 'N5',
    category: '숫자',
    origin_story: '白(흰 백)의 위에 一(일)을 더한 형태입니다. "흰 것(白)이 하나(一)가 완성되면 100"이라는 의미에서 유래했다는 설이 있어요. 또는 白이 발음 기호 역할을 하는 형성문자라는 설도 있습니다.',
    visual_hint: '白(흰) 위에 一(1) — 흰 모자를 쓴 글자!',
    mnemonic: '"백(百)화점"의 백! 百円(햐쿠엔)=100엔 — 편의점에서 매일 보는 숫자!',
    related_words: [
      { word: '百円', reading: 'ひゃくえん', pronunciation: '햐쿠엔', meaning: '100엔' },
      { word: '百貨店', reading: 'ひゃっかてん', pronunciation: '햐카텐', meaning: '백화점' },
      { word: '数百', reading: 'すうひゃく', pronunciation: '스-햐쿠', meaning: '수백' },
    ],
  },
  {
    id: 'k-017',
    kanji: '千',
    reading_on: 'セン',
    reading_kun: 'ち',
    pronunciation_on: '센',
    pronunciation_kun: '치',
    meaning_kr: '천(1000)',
    stroke_count: 3,
    jlpt: 'N5',
    category: '숫자',
    origin_story: '사람(人)의 몸에 가로선 하나를 그어 "많다"를 표현한 지사문자입니다. 사람이 천 명이나 될 정도로 수가 많다는 의미에서 1000을 나타냅니다. 千歳(치토세)=치토세, 千葉(치바)처럼 지명에도 자주 나옵니다.',
    visual_hint: '十자 위에 한 획 — 사람이 팔을 벌리고 머리에 막대기를 얹은 모습!',
    mnemonic: '"천(千)원"의 천과 발음이 비슷! 千円(센엔)=1000엔, 千葉(치바)=치바현!',
    related_words: [
      { word: '千円', reading: 'せんえん', pronunciation: '센엔', meaning: '1000엔' },
      { word: '千葉', reading: 'ちば', pronunciation: '치바', meaning: '치바(지명)' },
      { word: '数千', reading: 'すうせん', pronunciation: '스-센', meaning: '수천' },
    ],
  },

  // ── 방향 ──────────────────────────────────────────────────────────────
  {
    id: 'k-018',
    kanji: '上',
    reading_on: 'ジョウ',
    reading_kun: 'うえ・あがる',
    pronunciation_on: '조-',
    pronunciation_kun: '우에·아가루',
    meaning_kr: '위, 올라가다',
    stroke_count: 3,
    jlpt: 'N5',
    category: '방향',
    origin_story: '기준선 위에 점이 있다는 것을 시각적으로 표현한 지사문자입니다. "이 선보다 위에 있다"는 개념을 그림으로 그렸어요. 上手(잘함)·目上(윗사람)처럼 수준이나 사회적 위치에도 씁니다.',
    visual_hint: '기준선(一) 위에 위쪽 화살표 ↑ — 위로 올라가는 느낌!',
    mnemonic: '"상(上)단"의 상! 上野(우에노)=우에노역, 上手(조-즈)=잘해요 — 칭찬 단어의 핵심!',
    related_words: [
      { word: '上手', reading: 'じょうず', pronunciation: '조-즈', meaning: '잘함, 능숙함' },
      { word: '上野', reading: 'うえの', pronunciation: '우에노', meaning: '우에노(지명)' },
      { word: '上がる', reading: 'あがる', pronunciation: '아가루', meaning: '올라가다' },
    ],
  },
  {
    id: 'k-019',
    kanji: '下',
    reading_on: 'カ・ゲ',
    reading_kun: 'した・さがる',
    pronunciation_on: '카·게',
    pronunciation_kun: '시타·사가루',
    meaning_kr: '아래, 내려가다',
    stroke_count: 3,
    jlpt: 'N5',
    category: '방향',
    origin_story: '기준선 아래에 점이 있다는 것을 표현한 지사문자입니다. 上(위)의 반대 개념. 下手(헤타, 못함)처럼 수준이 낮음을, 地下鉄(지하철)처럼 공간적 위치에도 씁니다.',
    visual_hint: '기준선(ㅡ)에서 아래쪽 화살표 ↓ — T자 아래로 내려가는 느낌!',
    mnemonic: '"하(下)단"의 하! 地下鉄(치카테쓰)=지하철 — 일본 대중교통에서 매일 보는 글자!',
    related_words: [
      { word: '地下鉄', reading: 'ちかてつ', pronunciation: '치카테쓰', meaning: '지하철' },
      { word: '下手', reading: 'へた', pronunciation: '헤타', meaning: '못함, 서툶' },
      { word: '下がる', reading: 'さがる', pronunciation: '사가루', meaning: '내려가다' },
    ],
  },
  {
    id: 'k-020',
    kanji: '中',
    reading_on: 'チュウ',
    reading_kun: 'なか',
    pronunciation_on: '추-',
    pronunciation_kun: '나카',
    meaning_kr: '가운데, 중간',
    stroke_count: 4,
    jlpt: 'N5',
    category: '방향',
    origin_story: '깃대가 정중앙에 꽂혀있는 모습입니다. 고대 중국에서 군영의 한가운데에 깃발을 세워 집결 장소를 표시했고, 그 "중심"이 中의 기원이에요. 중국의 이름 "中国"도 "세상의 중심 나라"라는 의미입니다.',
    visual_hint: '□(사각형) 한가운데를 | 선이 정확히 꿰뚫고 있는 모습!',
    mnemonic: '"중(中)간"의 중! 中学校(추-각코-)=중학교, 真ん中(만나카)=정중앙!',
    related_words: [
      { word: '中学校', reading: 'ちゅうがっこう', pronunciation: '추-각코-', meaning: '중학교' },
      { word: '真ん中', reading: 'まんなか', pronunciation: '만나카', meaning: '정중앙' },
      { word: '中国', reading: 'ちゅうごく', pronunciation: '추-고쿠', meaning: '중국' },
    ],
  },
  {
    id: 'k-021',
    kanji: '右',
    reading_on: 'ウ・ユウ',
    reading_kun: 'みぎ',
    pronunciation_on: '우·유-',
    pronunciation_kun: '미기',
    meaning_kr: '오른쪽',
    stroke_count: 5,
    jlpt: 'N5',
    category: '방향',
    origin_story: '손(又)으로 음식을 입(口)에 넣는 모습입니다. 식사할 때 오른손으로 음식을 집어 먹는 동작에서 "오른쪽"이라는 의미가 생겼어요. 대부분의 사람이 오른손잡이인 데서 비롯된 발상입니다.',
    visual_hint: '입(口) 위에 손(ナ) — 오른손으로 음식을 입에 넣는 모습!',
    mnemonic: '右折(우세쓰)=우회전 — 일본에서 길 찾을 때 바로 쓰는 글자! 左(왼)와 한 쌍!',
    related_words: [
      { word: '右折', reading: 'うせつ', pronunciation: '우세쓰', meaning: '우회전' },
      { word: '右側', reading: 'みぎがわ', pronunciation: '미기가와', meaning: '우측, 오른쪽' },
      { word: '左右', reading: 'さゆう', pronunciation: '사유-', meaning: '좌우' },
    ],
  },
  {
    id: 'k-022',
    kanji: '左',
    reading_on: 'サ',
    reading_kun: 'ひだり',
    pronunciation_on: '사',
    pronunciation_kun: '히다리',
    meaning_kr: '왼쪽',
    stroke_count: 5,
    jlpt: 'N5',
    category: '방향',
    origin_story: '왼손(ナ)으로 공구(工)를 잡는 모습입니다. 오른손과 다르게 왼손은 도구를 보조하는 역할을 한다는 인식에서 유래했어요. 右(오른쪽)와 세트로 기억하면 훨씬 쉽습니다.',
    visual_hint: '공구(工) 위에 왼손(ナ) — 왼손으로 도구를 들고 있는 모습!',
    mnemonic: '左折(사세쓰)=좌회전 — 右折(우세쓰)와 한 쌍으로 외우세요!',
    related_words: [
      { word: '左折', reading: 'させつ', pronunciation: '사세쓰', meaning: '좌회전' },
      { word: '左側', reading: 'ひだりがわ', pronunciation: '히다리가와', meaning: '좌측, 왼쪽' },
      { word: '左右', reading: 'さゆう', pronunciation: '사유-', meaning: '좌우' },
    ],
  },

  // ── 시간 ──────────────────────────────────────────────────────────────
  {
    id: 'k-023',
    kanji: '年',
    reading_on: 'ネン',
    reading_kun: 'とし',
    pronunciation_on: '넨',
    pronunciation_kun: '토시',
    meaning_kr: '해, 년(年)',
    stroke_count: 6,
    jlpt: 'N5',
    category: '시간',
    origin_story: '곡식(禾, 벼)이 익어 사람(人)이 수확하는 모습입니다. 벼가 한 번 자라고 수확되는 주기가 "1년"이 됩니다. 농경 문명에서 시간은 씨앗을 뿌리고 거두는 반복이었어요.',
    visual_hint: '벼(위)와 사람(아래)이 합쳐진 모습 — 매년 벼를 수확하는 농부!',
    mnemonic: '"연(年)도"의 연! 来年(라이넨)=내년, 今年(코토시)=올해 — 첫 번째로 배우는 시간 단어!',
    related_words: [
      { word: '今年', reading: 'ことし', pronunciation: '코토시', meaning: '올해' },
      { word: '来年', reading: 'らいねん', pronunciation: '라이넨', meaning: '내년' },
      { word: '毎年', reading: 'まいとし', pronunciation: '마이토시', meaning: '매년' },
    ],
  },
  {
    id: 'k-024',
    kanji: '今',
    reading_on: 'コン・キン',
    reading_kun: 'いま',
    pronunciation_on: '콘·킨',
    pronunciation_kun: '이마',
    meaning_kr: '지금, 현재',
    stroke_count: 4,
    jlpt: 'N5',
    category: '시간',
    origin_story: '지붕(△) 아래에 뚜껑(一)이 닫혀있는 모습입니다. "지금 이 순간"을 상자 안에 가두어 표현한 글자예요. 今日(오늘), 今月(이번 달), 今年(올해)처럼 현재를 나타내는 모든 시간 표현에 붙습니다.',
    visual_hint: '삿갓 모양(△) 아래에 세로선 — 지금 이 순간을 뚜껑으로 덮어 보관!',
    mnemonic: '今すぐ(이마스구)=지금 당장, 今日(쿄-)=오늘 — 일본 생활의 필수 단어!',
    related_words: [
      { word: '今日', reading: 'きょう', pronunciation: '쿄-', meaning: '오늘' },
      { word: '今週', reading: 'こんしゅう', pronunciation: '콘슈-', meaning: '이번 주' },
      { word: '今すぐ', reading: 'いますぐ', pronunciation: '이마스구', meaning: '지금 당장' },
    ],
  },
  {
    id: 'k-025',
    kanji: '時',
    reading_on: 'ジ',
    reading_kun: 'とき',
    pronunciation_on: '지',
    pronunciation_kun: '토키',
    meaning_kr: '때, 시간',
    stroke_count: 10,
    jlpt: 'N5',
    category: '시간',
    origin_story: '日(해) + 寺(절)로 이루어진 형성문자입니다. 고대 중국과 일본의 절에서 해시계와 종으로 시간을 알렸기 때문에 "때(時)"를 나타내게 됐어요. 태양(日)이 절(寺) 위를 지나가며 종소리로 시간을 알리는 장면을 상상하세요.',
    visual_hint: '日(해) + 寺(절) — 해가 절 위를 지나가며 시간을 알려주는 모습 ⏰!',
    mnemonic: '"시(時)간"의 시! 何時(난지)=몇 시예요? — 일본에서 가장 먼저 배워야 할 질문!',
    related_words: [
      { word: '何時', reading: 'なんじ', pronunciation: '난지', meaning: '몇 시' },
      { word: '時間', reading: 'じかん', pronunciation: '지칸', meaning: '시간' },
      { word: '時々', reading: 'ときどき', pronunciation: '토키도키', meaning: '때때로, 가끔' },
    ],
  },
  {
    id: 'k-026',
    kanji: '前',
    reading_on: 'ゼン',
    reading_kun: 'まえ',
    pronunciation_on: '젠',
    pronunciation_kun: '마에',
    meaning_kr: '앞, 이전',
    stroke_count: 9,
    jlpt: 'N5',
    category: '시간',
    origin_story: '배(月의 원형)가 칼(刂)로 물을 가르며 앞으로 나아가는 모습입니다. 앞을 향해 전진하는 배의 이미지에서 "앞(前)"이라는 의미가 생겼어요. 午前(오전), 駅前(역 앞), 名前(이름) 등 일상에서 아주 많이 씁니다.',
    visual_hint: '배(上部)가 칼(刂)로 물을 가르며 전진 — 앞으로 나아가는 모습!',
    mnemonic: '"전(前)날"의 전! 名前(나마에)=이름, 駅前(에키마에)=역 앞 — 자기소개에 바로 나오는 글자!',
    related_words: [
      { word: '名前', reading: 'なまえ', pronunciation: '나마에', meaning: '이름' },
      { word: '駅前', reading: 'えきまえ', pronunciation: '에키마에', meaning: '역 앞' },
      { word: '午前', reading: 'ごぜん', pronunciation: '고젠', meaning: '오전' },
    ],
  },

  // ── 일상 ──────────────────────────────────────────────────────────────
  {
    id: 'k-027',
    kanji: '食',
    reading_on: 'ショク',
    reading_kun: 'たべる',
    pronunciation_on: '쇼쿠',
    pronunciation_kun: '타베루',
    meaning_kr: '먹다, 음식',
    stroke_count: 9,
    jlpt: 'N5',
    category: '일상',
    origin_story: '고대 제사 그릇(亼, 삿갓 모양 뚜껑)에 음식(良)이 담긴 모습입니다. 제사상에 올리는 음식에서 "먹다(食)"의 의미가 나왔어요. 食堂(식당), 食事(식사)처럼 "먹다"와 관련된 모든 단어에 씁니다.',
    visual_hint: '삿갓 뚜껑(亼) 아래 밥그릇(良) — 뚜껑 열면 맛있는 음식 🍱!',
    mnemonic: '"식(食)사"의 식! 한국어와 완전히 같아요! 食堂(쇼쿠도-)=식당!',
    related_words: [
      { word: '食堂', reading: 'しょくどう', pronunciation: '쇼쿠도-', meaning: '식당, 구내식당' },
      { word: '食事', reading: 'しょくじ', pronunciation: '쇼쿠지', meaning: '식사' },
      { word: '食べ物', reading: 'たべもの', pronunciation: '타베모노', meaning: '음식, 먹을거리' },
    ],
  },
  {
    id: 'k-028',
    kanji: '店',
    reading_on: 'テン',
    reading_kun: 'みせ',
    pronunciation_on: '텐',
    pronunciation_kun: '미세',
    meaning_kr: '가게, 점포',
    stroke_count: 8,
    jlpt: 'N5',
    category: '일상',
    origin_story: '지붕(广) 아래에 점(占)을 치는 사람이 자리를 잡은 모습입니다. 고대 시장에서 점쟁이들이 자리를 잡고 앉아 장사를 시작한 것이 "가게(店)"의 유래예요.',
    visual_hint: '지붕(广) 아래 자리 잡은 가게 — 점쟁이에서 시작된 상점 🏪!',
    mnemonic: '"점(店)포"의 점! 한국어와 같아요! 店員(텐인)=점원, 百貨店(햐카텐)=백화점!',
    related_words: [
      { word: '本屋', reading: 'ほんや', pronunciation: '혼야', meaning: '서점' },
      { word: '飲食店', reading: 'いんしょくてん', pronunciation: '인쇼쿠텐', meaning: '음식점' },
      { word: '店員', reading: 'てんいん', pronunciation: '텐인', meaning: '점원, 직원' },
    ],
  },
  {
    id: 'k-029',
    kanji: '円',
    reading_on: 'エン',
    reading_kun: 'まる',
    pronunciation_on: '엔',
    pronunciation_kun: '마루',
    meaning_kr: '엔(¥), 원형',
    stroke_count: 4,
    jlpt: 'N5',
    category: '일상',
    origin_story: '"에워싸다"를 의미하는 圓의 간략화한 형태입니다. 원래 "둥근 모양"이라는 뜻이었는데, 명치시대(1871년)에 일본이 원형 동전을 새 화폐로 채택하며 통화 단위 이름이 됐어요.',
    visual_hint: '동그란 원 안에 내용이 담긴 모습 — 동그란 동전 🪙!',
    mnemonic: '税込(제이코미) 110円(히야쿠주-엔) — 일본 생활에서 가장 많이 보는 한자!',
    related_words: [
      { word: '百円', reading: 'ひゃくえん', pronunciation: '햐쿠엔', meaning: '100엔' },
      { word: '円安', reading: 'えんやす', pronunciation: '엔야스', meaning: '엔화 약세' },
      { word: '税込', reading: 'ぜいこみ', pronunciation: '제이코미', meaning: '세금 포함' },
    ],
  },
  {
    id: 'k-030',
    kanji: '駅',
    reading_on: 'エキ',
    reading_kun: '',
    pronunciation_on: '에키',
    pronunciation_kun: '',
    meaning_kr: '역, 정거장',
    stroke_count: 14,
    jlpt: 'N5',
    category: '일상',
    origin_story: '말(馬)이 쉬어 가는 역참(驛)을 뜻하는 글자의 간략화입니다. 고대에는 말을 타고 장거리를 이동할 때, 일정 거리마다 새 말로 바꾸는 역참이 있었어요. 현대에는 기차역·전철역을 뜻합니다.',
    visual_hint: '말(馬) + 尺(장소) — 말이 쉬어 가는 정거장 🚉!',
    mnemonic: '駅前(에키마에)=역 앞, 駅員(에키인)=역무원 — 일본에서 약속 장소를 말할 때 1순위 글자!',
    related_words: [
      { word: '駅前', reading: 'えきまえ', pronunciation: '에키마에', meaning: '역 앞' },
      { word: '駅員', reading: 'えきいん', pronunciation: '에키인', meaning: '역무원' },
      { word: '終点', reading: 'しゅうてん', pronunciation: '슈-텐', meaning: '종점' },
    ],
  },
  // ── 숫자 (4~10) ───────────────────────────────────────────────────────────
  {
    id: 'k-031',
    kanji: '四',
    reading_on: 'シ',
    reading_kun: 'よ・よん・よっつ',
    pronunciation_on: '시',
    pronunciation_kun: '요·욘·욧쓰',
    meaning_kr: '넷, 사(4)',
    stroke_count: 5,
    jlpt: 'N5',
    category: '숫자',
    origin_story: '코와 두 콧구멍의 숨결을 그린 글자에서 유래했다는 설이 있어요. 고대 중국에서 "넷"을 의미하는 발음에 맞게 글자가 정착됐습니다. 현재 모습은 사방(四方)을 가리키는 상징으로도 봅니다.',
    visual_hint: '큰 사각형 안에 두 획 — 창문이 四개(사방팔방)!',
    mnemonic: '"사(四)망"·"사각형"의 사! 주의: 죽음(死)과 발음이 같아 불길하게 여겨 엘리베이터에서 4층 버튼이 없는 경우도 있어요.',
    related_words: [
      { word: '四月', reading: 'しがつ', pronunciation: '시가쓰', meaning: '4월' },
      { word: '四角', reading: 'しかく', pronunciation: '시카쿠', meaning: '사각형' },
      { word: '四季', reading: 'しき', pronunciation: '시키', meaning: '사계절' },
    ],
  },
  {
    id: 'k-032',
    kanji: '五',
    reading_on: 'ゴ',
    reading_kun: 'いつ・いつつ',
    pronunciation_on: '고',
    pronunciation_kun: '이쓰·이쓰쓰',
    meaning_kr: '다섯, 오(5)',
    stroke_count: 4,
    jlpt: 'N5',
    category: '숫자',
    origin_story: '다섯 손가락을 교차한 모양에서 유래했다는 설이 있어요. X 형태가 변형되어 현재 모습이 됐습니다. 다섯은 한 손의 손가락 수이자 오감(五感)·오행(五行)처럼 완전함을 상징하는 숫자예요.',
    visual_hint: '가로선 두 개와 세로선, 그리고 아래 갈고리 — 五의 아래 갈고리가 "다섯 번째" 획!',
    mnemonic: '"오(五)감"의 오! お五(고)飯(한)=밥 다섯 공기? 아니고, 五月五日=5월 5일=어린이날(こどもの日)!',
    related_words: [
      { word: '五月', reading: 'ごがつ', pronunciation: '고가쓰', meaning: '5월' },
      { word: '五感', reading: 'ごかん', pronunciation: '고칸', meaning: '오감' },
      { word: '五十音', reading: 'ごじゅうおん', pronunciation: '고쥬-온', meaning: '오십음도' },
    ],
  },
  {
    id: 'k-033',
    kanji: '六',
    reading_on: 'ロク',
    reading_kun: 'む・むっつ・むい',
    pronunciation_on: '로쿠',
    pronunciation_kun: '무·뭇쓰·무이',
    meaning_kr: '여섯, 육(6)',
    stroke_count: 4,
    jlpt: 'N5',
    category: '숫자',
    origin_story: '오두막이나 집의 지붕 모양에서 유래했다는 설이 있어요. 여섯의 의미와 이 모양이 연결된 이유는 명확하지 않지만, 오래전부터 이 형태로 "여섯"을 나타냈습니다.',
    visual_hint: '지붕처럼 생긴 윗부분 아래 두 획 — 집 지붕 아래 여섯 사람?',
    mnemonic: '"육(六)개월"의 육! 六本木(롯폰기)=도쿄 유명 지역, 六月=6월, 일본 생활에서 자주 만나는 글자예요.',
    related_words: [
      { word: '六月', reading: 'ろくがつ', pronunciation: '로쿠가쓰', meaning: '6월' },
      { word: '六本木', reading: 'ろっぽんぎ', pronunciation: '롯폰기', meaning: '롯폰기(지명)' },
      { word: '六百', reading: 'ろっぴゃく', pronunciation: '롯퍄쿠', meaning: '600' },
    ],
  },
  {
    id: 'k-034',
    kanji: '七',
    reading_on: 'シチ',
    reading_kun: 'なな・ななつ',
    pronunciation_on: '시치',
    pronunciation_kun: '나나·나나쓰',
    meaning_kr: '일곱, 칠(7)',
    stroke_count: 2,
    jlpt: 'N5',
    category: '숫자',
    origin_story: '고대 중국어에서 "끊다"를 뜻하는 기호에서 유래했어요. 세로선을 가로선이 자르는 모양이 "7"이 됐고, 칠석(七夕)·칠복신(七福神) 등 일본 문화에서 특별한 숫자입니다.',
    visual_hint: '가로선 하나가 삐죽 나온 모양 — 마치 숫자 7 같은 획순!',
    mnemonic: '"칠(七)월"의 칠! 七月七日=7월 7일=칠석(たなばた), 七五三=시치고산(어린이 행사) — 7은 럭키 넘버!',
    related_words: [
      { word: '七月', reading: 'しちがつ', pronunciation: '시치가쓰', meaning: '7월' },
      { word: '七夕', reading: 'たなばた', pronunciation: '타나바타', meaning: '칠석' },
      { word: '七五三', reading: 'しちごさん', pronunciation: '시치고산', meaning: '시치고산(축제)' },
    ],
  },
  {
    id: 'k-035',
    kanji: '八',
    reading_on: 'ハチ',
    reading_kun: 'や・やっつ・よう',
    pronunciation_on: '하치',
    pronunciation_kun: '야·얏쓰·요-',
    meaning_kr: '여덟, 팔(8)',
    stroke_count: 2,
    jlpt: 'N5',
    category: '숫자',
    origin_story: '두 획이 좌우로 벌어지는 모양 — 원래 "나누다, 분리하다"를 뜻했어요. 양쪽으로 퍼지는 모습이 "八方"(사방팔방)처럼 퍼져나가는 이미지와 맞아요. 일본에서 八は縁起がいい数(팔은 길한 수)라고도 해요.',
    visual_hint: '두 획이 ハ 모양으로 아래로 벌어지는 형태 — 두 발이 벌어지는 모습!',
    mnemonic: '"팔(八)월"의 팔! 八百屋(야오야)=채소 가게, 渋谷(시부야)·秋葉原(아키하바라)의 谷·原에도 숨어 있어요.',
    related_words: [
      { word: '八月', reading: 'はちがつ', pronunciation: '하치가쓰', meaning: '8월' },
      { word: '八百屋', reading: 'やおや', pronunciation: '야오야', meaning: '채소 가게' },
      { word: '八方', reading: 'はっぽう', pronunciation: '핫포-', meaning: '사방팔방' },
    ],
  },
  {
    id: 'k-036',
    kanji: '九',
    reading_on: 'キュウ・ク',
    reading_kun: 'ここの・ここのつ',
    pronunciation_on: '큐-·쿠',
    pronunciation_kun: '코코노·코코노쓰',
    meaning_kr: '아홉, 구(9)',
    stroke_count: 2,
    jlpt: 'N5',
    category: '숫자',
    origin_story: '팔꿈치를 구부린 팔 모양에서 유래했다는 설이 있어요. 구부러진 모양이 "9"를 연상시킵니다. 일본에서 九(쿠)는 苦(쿠, 고통)와 발음이 같아 불길하게 여기기도 해요.',
    visual_hint: '갈고리처럼 굽은 모양 — 숫자 9처럼 꼬리가 말린 형태!',
    mnemonic: '"구(九)월"의 구! 주의: 九(쿠)=苦(쿠, 고통)와 동음이라 꺼리는 사람도 있어요. 九州(큐슈)는 예외!',
    related_words: [
      { word: '九月', reading: 'くがつ', pronunciation: '쿠가쓰', meaning: '9월' },
      { word: '九州', reading: 'きゅうしゅう', pronunciation: '큐-슈-', meaning: '규슈(지역)' },
      { word: '救急', reading: 'きゅうきゅう', pronunciation: '큐-큐-', meaning: '응급' },
    ],
  },
  {
    id: 'k-037',
    kanji: '十',
    reading_on: 'ジュウ',
    reading_kun: 'とお・と',
    pronunciation_on: '쥬-',
    pronunciation_kun: '토-·토',
    meaning_kr: '열, 십(10)',
    stroke_count: 2,
    jlpt: 'N5',
    category: '숫자',
    origin_story: '열을 나타내는 가장 단순한 기호입니다. 동서남북을 잇는 십자가 모양으로, "완전한 수"를 상징해요. 한 손가락씩 펴서 10까지 세면 양손이 가득 차는 것처럼, 十은 한 자리 수의 끝이자 완성입니다.',
    visual_hint: '십(十)자 모양 그 자체! 가로 + 세로 — 이보다 단순할 수 없는 "열"!',
    mnemonic: '"십(十)월"의 십! 二十歳(하타치)=20살·十字路(쥬-지로)=십자로 — 숫자 기초 중의 기초!',
    related_words: [
      { word: '十月', reading: 'じゅうがつ', pronunciation: '쥬-가쓰', meaning: '10월' },
      { word: '二十歳', reading: 'はたち', pronunciation: '하타치', meaning: '스무 살' },
      { word: '十分', reading: 'じゅっぷん', pronunciation: '쥬-푼', meaning: '10분' },
    ],
  },
  // ── 사람·가족 ───────────────────────────────────────────────────────────
  {
    id: 'k-038',
    kanji: '女',
    reading_on: 'ジョ・ニョ',
    reading_kun: 'おんな・め',
    pronunciation_on: '죠·뇨',
    pronunciation_kun: '온나·메',
    meaning_kr: '여자, 여성',
    stroke_count: 3,
    jlpt: 'N5',
    category: '사람',
    origin_story: '무릎을 꿇고 두 손을 앞에 모은 여성의 모습을 그린 상형문자입니다. 고대 사회에서 여성의 모습을 직접 그린 것으로, 女性·女子·彼女 등 여성 관련 단어에 쓰입니다.',
    visual_hint: '무릎을 꿇고 앉아 손을 모은 사람 — 절하는 여성의 자세!',
    mnemonic: '"여(女)성"의 여! 彼女(카노죠)=여자친구·女性(죠세이)=여성 — 인간관계 필수 글자!',
    related_words: [
      { word: '女性', reading: 'じょせい', pronunciation: '죠세이', meaning: '여성' },
      { word: '彼女', reading: 'かのじょ', pronunciation: '카노죠', meaning: '여자친구/그녀' },
      { word: '女子', reading: 'じょし', pronunciation: '죠시', meaning: '여자아이' },
    ],
  },
  {
    id: 'k-039',
    kanji: '男',
    reading_on: 'ダン・ナン',
    reading_kun: 'おとこ',
    pronunciation_on: '단·난',
    pronunciation_kun: '오토코',
    meaning_kr: '남자, 남성',
    stroke_count: 7,
    jlpt: 'N5',
    category: '사람',
    origin_story: '밭(田)에서 힘(力)을 쓰는 사람을 나타내요. 田(밭)과 力(힘)을 합쳐 "밭에서 힘쓰는 사람 = 남자"라는 의미가 됩니다. 농경 사회에서 남자의 역할을 직접 표현한 회의문자예요.',
    visual_hint: '위는 밭(田), 아래는 힘(力) — 밭에서 힘쓰는 남자!',
    mnemonic: '"남(男)성"의 남! 男性(단세이)=남성·彼(카레)=남자친구/그 — 田+力=男 조합을 기억하세요!',
    related_words: [
      { word: '男性', reading: 'だんせい', pronunciation: '단세이', meaning: '남성' },
      { word: '男子', reading: 'だんし', pronunciation: '단시', meaning: '남자아이' },
      { word: '長男', reading: 'ちょうなん', pronunciation: '초-난', meaning: '장남' },
    ],
  },
  {
    id: 'k-040',
    kanji: '子',
    reading_on: 'シ・ス',
    reading_kun: 'こ',
    pronunciation_on: '시·스',
    pronunciation_kun: '코',
    meaning_kr: '아이, 자식',
    stroke_count: 3,
    jlpt: 'N5',
    category: '사람',
    origin_story: '두 팔을 벌리고 있는 아기의 모습을 그린 상형문자입니다. 위는 머리, 아래로 갈수록 몸체와 다리가 좁아지는 아기의 전신을 표현했어요. 子供(코도모)=어린이, 親子(오야코)=부모와 자식처럼 가족·관계 단어에 많이 쓰입니다.',
    visual_hint: '두 팔을 뻗은 아기의 전신 — 귀엽게 팔 벌린 아기 모습!',
    mnemonic: '"자(子)식"의 자! 子供(코도모)=어린이·男の子(오토코노코)=남자아이·女の子(온나노코)=여자아이!',
    related_words: [
      { word: '子供', reading: 'こども', pronunciation: '코도모', meaning: '어린이' },
      { word: '男の子', reading: 'おとこのこ', pronunciation: '오토코노코', meaning: '남자아이' },
      { word: '親子', reading: 'おやこ', pronunciation: '오야코', meaning: '부모와 자식' },
    ],
  },
  // ── 학교·배움 ───────────────────────────────────────────────────────────
  {
    id: 'k-041',
    kanji: '学',
    reading_on: 'ガク',
    reading_kun: 'まな(ぶ)',
    pronunciation_on: '가쿠',
    pronunciation_kun: '마나(부)',
    meaning_kr: '배우다, 학문',
    stroke_count: 8,
    jlpt: 'N5',
    category: '일상',
    origin_story: '두 손이 책 위에 놓이고 아이(子)가 배우는 모습을 형상화한 글자입니다. 위쪽의 갈고리 모양들은 손을 나타내고, 아래의 子는 배우는 아이를 뜻해요. 학교(学校)·대학(大学) 등 교육 관련 단어의 핵심 글자입니다.',
    visual_hint: '위는 두 손, 아래는 아이(子) — 손으로 아이를 가르치는 모습!',
    mnemonic: '"학(学)교"의 학! 大学(다이가쿠)=대학·学生(각쿠세이)=학생·学校(각코-)=학교 — 이 글자 하나가 교육의 전부!',
    related_words: [
      { word: '学校', reading: 'がっこう', pronunciation: '각코-', meaning: '학교' },
      { word: '大学', reading: 'だいがく', pronunciation: '다이가쿠', meaning: '대학' },
      { word: '学生', reading: 'がくせい', pronunciation: '각세이', meaning: '학생' },
    ],
  },
  {
    id: 'k-042',
    kanji: '先',
    reading_on: 'セン',
    reading_kun: 'さき',
    pronunciation_on: '센',
    pronunciation_kun: '사키',
    meaning_kr: '먼저, 앞서다, 선생',
    stroke_count: 6,
    jlpt: 'N5',
    category: '일상',
    origin_story: '발(止)이 사람(人) 위로 나아가는 모습에서 "먼저 나아가다"의 의미가 됐어요. 先生(센세이)는 "먼저 태어난 사람=선생님"이라는 뜻으로, 경험이 앞선 사람을 높여 부릅니다.',
    visual_hint: '발이 사람보다 앞에 — 남보다 한 발 앞서 나아가는 모습!',
    mnemonic: '"선(先)생님"의 선! 先生(센세이)=선생님·先週(센슈-)=지난 주·お先に失礼します(먼저 실례합니다) — 일본 직장 문화의 핵심 표현!',
    related_words: [
      { word: '先生', reading: 'せんせい', pronunciation: '센세이', meaning: '선생님' },
      { word: '先週', reading: 'せんしゅう', pronunciation: '센슈-', meaning: '지난 주' },
      { word: '先輩', reading: 'せんぱい', pronunciation: '센파이', meaning: '선배' },
    ],
  },
  {
    id: 'k-043',
    kanji: '生',
    reading_on: 'セイ・ショウ',
    reading_kun: 'い(きる)・う(まれる)・なま',
    pronunciation_on: '세이·쇼-',
    pronunciation_kun: '이(키루)·우(마레루)·나마',
    meaning_kr: '살다, 태어나다, 생(生)',
    stroke_count: 5,
    jlpt: 'N5',
    category: '일상',
    origin_story: '땅 위로 새싹(草)이 솟아오르는 모습을 그린 상형문자입니다. 아래 가로선은 땅, 위로 올라오는 획들이 새싹을 나타내요. "살다, 태어나다"의 의미에서 人生·学生·先生 등 다양한 단어를 만들어냅니다.',
    visual_hint: '땅에서 새싹이 쑥 자라는 모습 🌱 — 생명이 솟아오른다!',
    mnemonic: '"생(生)명"의 생! 学生(각쿠세이)=학생·先生(센세이)=선생님·生ビール(나마비-루)=생맥주 — 활용도 최고!',
    related_words: [
      { word: '学生', reading: 'がくせい', pronunciation: '각쿠세이', meaning: '학생' },
      { word: '人生', reading: 'じんせい', pronunciation: '진세이', meaning: '인생' },
      { word: '生ビール', reading: 'なまびーる', pronunciation: '나마비-루', meaning: '생맥주' },
    ],
  },
  // ── 일상·생활 ───────────────────────────────────────────────────────────
  {
    id: 'k-044',
    kanji: '車',
    reading_on: 'シャ',
    reading_kun: 'くるま',
    pronunciation_on: '샤',
    pronunciation_kun: '쿠루마',
    meaning_kr: '수레, 자동차',
    stroke_count: 7,
    jlpt: 'N5',
    category: '일상',
    origin_story: '수레바퀴와 차축을 위에서 내려다본 모습입니다. 중앙의 바퀴통·양쪽의 바퀴살·테두리가 모두 표현돼 있어요. 고대 전쟁에서 필수였던 전차(戰車)에서 비롯해 오늘날 자동차·전철까지 모든 탈것을 포함합니다.',
    visual_hint: '바퀴를 위에서 내려다본 모습 🎡 — 중심축 + 바퀴살!',
    mnemonic: '"차(車)"! 電車(덴샤)=전철·自動車(지도-샤)=자동차·駐車場(츄-샤죠-)=주차장 — 이동 수단의 핵심!',
    related_words: [
      { word: '電車', reading: 'でんしゃ', pronunciation: '덴샤', meaning: '전철' },
      { word: '自動車', reading: 'じどうしゃ', pronunciation: '지도-샤', meaning: '자동차' },
      { word: '駐車場', reading: 'ちゅうしゃじょう', pronunciation: '츄-샤죠-', meaning: '주차장' },
    ],
  },
  {
    id: 'k-045',
    kanji: '電',
    reading_on: 'デン',
    reading_kun: '',
    pronunciation_on: '덴',
    pronunciation_kun: '',
    meaning_kr: '번개, 전기',
    stroke_count: 13,
    jlpt: 'N5',
    category: '일상',
    origin_story: '비(雨)구름 아래로 번개가 내리치는 모습을 형상화했어요. 위쪽의 雨(비)와 아래쪽의 번개 모양이 결합된 글자입니다. 전기가 발명된 근대 이후 電車·電話·電気처럼 에너지 관련 단어 앞에 붙어 활약합니다.',
    visual_hint: '비 구름(雨) 아래로 번개가 쾅! ⚡ — 비와 번개가 합쳐진 글자!',
    mnemonic: '"전(電)기"의 전! 電話(덴와)=전화·電車(덴샤)=전철·電気(덴키)=전기 — 현대 생활에서 없으면 안 되는 글자!',
    related_words: [
      { word: '電話', reading: 'でんわ', pronunciation: '덴와', meaning: '전화' },
      { word: '電車', reading: 'でんしゃ', pronunciation: '덴샤', meaning: '전철' },
      { word: '電気', reading: 'でんき', pronunciation: '덴키', meaning: '전기' },
    ],
  },
  {
    id: 'k-046',
    kanji: '語',
    reading_on: 'ゴ',
    reading_kun: 'かた(る)',
    pronunciation_on: '고',
    pronunciation_kun: '카타(루)',
    meaning_kr: '말, 언어',
    stroke_count: 14,
    jlpt: 'N5',
    category: '일상',
    origin_story: '言(말씀·언)과 吾(나)가 결합된 글자입니다. "내(吾)가 하는 말(言)"이 모여 "언어·이야기"가 됩니다. 日本語(일본어)·韓国語(한국어)처럼 언어 이름에 반드시 나오고, 語学(고가쿠)=어학처럼 배움 관련 단어에도 씁니다.',
    visual_hint: '왼쪽 言(말씀)+ 오른쪽 吾(나) — 내가 하는 말 = 언어!',
    mnemonic: '"어(語)학"의 어! 日本語(니혼고)=일본어·英語(에이고)=영어·韓国語(칸코쿠고)=한국어 — 어학 공부하는 우리에게 가장 친숙한 글자!',
    related_words: [
      { word: '日本語', reading: 'にほんご', pronunciation: '니혼고', meaning: '일본어' },
      { word: '英語', reading: 'えいご', pronunciation: '에이고', meaning: '영어' },
      { word: '語学', reading: 'ごがく', pronunciation: '고가쿠', meaning: '어학' },
    ],
  },
  {
    id: 'k-047',
    kanji: '何',
    reading_on: 'カ',
    reading_kun: 'なに・なん',
    pronunciation_on: '카',
    pronunciation_kun: '나니·난',
    meaning_kr: '무엇, 어느',
    stroke_count: 7,
    jlpt: 'N5',
    category: '일상',
    origin_story: '사람(人)이 무거운 짐을 등에 지고 있는 모습에서 유래했다는 설이 있어요. "무엇을 짊어지고 있는가?"에서 의문 대명사 "무엇"이 됐습니다. 何(なに/なん)는 의문문에서 가장 많이 쓰이는 글자 중 하나입니다.',
    visual_hint: '사람(亻)이 짐을 지고 있는 모습 — "저게 뭐야?"라고 물어보는 장면!',
    mnemonic: '"무엇"을 묻는 마법 글자! 何時(난지)=몇 시·何階(난카이)=몇 층·何人(난닌)=몇 명 — 숫자 앞에 붙어 "몇 ~?"을 만들어요.',
    related_words: [
      { word: '何時', reading: 'なんじ', pronunciation: '난지', meaning: '몇 시' },
      { word: '何階', reading: 'なんかい', pronunciation: '난카이', meaning: '몇 층' },
      { word: '何人', reading: 'なんにん', pronunciation: '난닌', meaning: '몇 명' },
    ],
  },
  {
    id: 'k-048',
    kanji: '入',
    reading_on: 'ニュウ',
    reading_kun: 'い(る)・は(いる)',
    pronunciation_on: '뉴-',
    pronunciation_kun: '이(루)·하(이루)',
    meaning_kr: '들어가다, 입(入)',
    stroke_count: 2,
    jlpt: 'N5',
    category: '일상',
    origin_story: '지붕이 있는 공간 안으로 들어가는 모습을 그린 상형문자입니다. 두 획이 위에서 아래로 모이는 형태가 "안으로 들어가는" 방향을 나타내요. 入口·入学·入社처럼 "~에 들어가다"는 의미로 폭넓게 쓰입니다.',
    visual_hint: '두 획이 위에서 아래로 좁아지는 모양 — 문 안으로 들어가는 느낌!',
    mnemonic: '"입(入)구"의 입! 入口(이리구치)=입구·入学(뉴-가쿠)=입학·入社(뉴-샤)=입사 — 出(나갈 출)의 반대!',
    related_words: [
      { word: '入口', reading: 'いりぐち', pronunciation: '이리구치', meaning: '입구' },
      { word: '入学', reading: 'にゅうがく', pronunciation: '뉴-가쿠', meaning: '입학' },
      { word: '入場', reading: 'にゅうじょう', pronunciation: '뉴-죠-', meaning: '입장' },
    ],
  },
  {
    id: 'k-049',
    kanji: '出',
    reading_on: 'シュツ・スイ',
    reading_kun: 'で(る)・だ(す)',
    pronunciation_on: '슈쓰·스이',
    pronunciation_kun: '데(루)·다(스)',
    meaning_kr: '나가다, 출(出)',
    stroke_count: 5,
    jlpt: 'N5',
    category: '일상',
    origin_story: '발(止)이 구덩이나 경계 밖으로 뻗어 나오는 모습을 나타냅니다. 위아래로 겹쳐진 두 개의 산 모양이 "튀어나옴"을 표현해요. 出口·出発·出張처럼 "나오다·출발하다"는 뜻으로 씁니다.',
    visual_hint: '두 개의 산 모양(凸凸)이 위아래로 — 뭔가가 쑥 튀어나오는 모습!',
    mnemonic: '"출(出)구"의 출! 出口(데구치)=출구·出発(슈파쓰)=출발·出張(슛초-)=출장 — 入(들어갈 입)의 반대!',
    related_words: [
      { word: '出口', reading: 'でぐち', pronunciation: '데구치', meaning: '출구' },
      { word: '出発', reading: 'しゅっぱつ', pronunciation: '슈파쓰', meaning: '출발' },
      { word: '出張', reading: 'しゅっちょう', pronunciation: '슛초-', meaning: '출장' },
    ],
  },
  {
    id: 'k-050',
    kanji: '本',
    reading_on: 'ホン',
    reading_kun: 'もと',
    pronunciation_on: '혼',
    pronunciation_kun: '모토',
    meaning_kr: '책, 근본, 일본',
    stroke_count: 5,
    jlpt: 'N5',
    category: '일상',
    origin_story: '나무(木) 아래쪽에 표시 획(一)을 그어 "뿌리·근본"을 나타낸 지사문자입니다. "뿌리 = 근본 = 원래"의 의미였는데, 이후 종이가 발명되며 책(冊)을 세는 단위로, 그리고 "책"을 뜻하게 됐어요. 日本은 "해(日)가 뜨는 근본(本)의 나라"!',
    visual_hint: '나무(木) 아래에 짧은 가로선 — 뿌리를 가리키는 손가락!',
    mnemonic: '"본(本)질"의 본! 日本(니혼)=일본·本(혼)=책·一本(잇폰)=1권·本当(혼토-)=정말 — 이 글자 없이는 일본 생활이 불가능!',
    related_words: [
      { word: '日本', reading: 'にほん', pronunciation: '니혼', meaning: '일본' },
      { word: '本当', reading: 'ほんとう', pronunciation: '혼토-', meaning: '정말로' },
      { word: '一本', reading: 'いっぽん', pronunciation: '잇폰', meaning: '1개(가늘고 긴 것)' },
    ],
  },
]
