export interface MapExpression {
  japanese: string
  reading: string
  pronunciation: string
  korean: string
}

export interface MapLocation {
  id: string
  name_jp: string
  name_kr: string
  emoji: string
  tag: string
  description_kr: string
  expressions: MapExpression[]
  card_count: number
  real_use_count: number
  episode_id?: string
  // position on map (% from top-left)
  top: number
  left: number
  color: string
}

export const MAP_LOCATIONS: MapLocation[] = [
  {
    id: 'supermarket',
    name_jp: 'スーパー',
    name_kr: '슈퍼마켓·쇼핑몰',
    emoji: '🛒',
    tag: '쇼핑',
    description_kr: '장을 볼 때 쓰는 일본어',
    card_count: 8,
    real_use_count: 5,
    expressions: [
      { japanese: 'いくらですか', reading: 'いくらですか', pronunciation: '이쿠라 데스카', korean: '얼마예요?' },
      { japanese: 'レジ袋はいりますか', reading: 'れじぶくろはいりますか', pronunciation: '레지부쿠로와 이리마스카', korean: '봉지 필요하세요?' },
      { japanese: 'ポイントカードはお持ちですか', reading: 'ぽいんとかーどはおもちですか', pronunciation: '포인토카-도와 오모치 데스카', korean: '포인트 카드 있으세요?' },
      { japanese: '試食できますか', reading: 'ししょくできますか', pronunciation: '시쇼쿠 데키마스카', korean: '시식할 수 있나요?' },
      { japanese: '賞味期限はいつですか', reading: 'しょうみきげんはいつですか', pronunciation: '쇼-미키겐와 이쓰 데스카', korean: '유통기한이 언제예요?' },
    ],
    top: 18,
    left: 10,
    color: '#e74c3c',
  },
  {
    id: 'nursery',
    name_jp: '保育園',
    name_kr: '육아·보육 표현',
    emoji: '🧒',
    tag: '육아',
    description_kr: '어린이집·유치원에서 쓰는 일본어',
    card_count: 6,
    real_use_count: 1,
    expressions: [
      { japanese: 'お迎えに来ました', reading: 'おむかえにきました', pronunciation: '오무카에니 키마시타', korean: '데리러 왔어요' },
      { japanese: '熱があります', reading: 'ねつがあります', pronunciation: '네쓰가 아리마스', korean: '열이 있어요' },
      { japanese: '今日はお休みします', reading: 'きょうはおやすみします', pronunciation: '쿄-와 오야스미시마스', korean: '오늘은 쉬겠습니다' },
      { japanese: '連絡帳に書きました', reading: 'れんらくちょうにかきました', pronunciation: '렌라쿠쵸-니 카키마시타', korean: '연락장에 썼어요' },
      { japanese: 'アレルギーがあります', reading: 'あれるぎーがあります', pronunciation: '아레루기-가 아리마스', korean: '알레르기가 있어요' },
    ],
    top: 14,
    left: 72,
    color: '#9b59b6',
  },
  {
    id: 'hospital',
    name_jp: '病院',
    name_kr: '진료·증상 표현',
    emoji: '🏥',
    tag: '의료',
    description_kr: '병원·약국에서 쓰는 일본어',
    card_count: 10,
    real_use_count: 2,
    expressions: [
      { japanese: 'お腹が痛いです', reading: 'おなかがいたいです', pronunciation: '오나카가 이타이데스', korean: '배가 아파요' },
      { japanese: '保険証はお持ちですか', reading: 'ほけんしょうはおもちですか', pronunciation: '호켄쇼-와 오모치 데스카', korean: '보험증 갖고 계세요?' },
      { japanese: '薬は一日三回飲んでください', reading: 'くすりはいちにちさんかいのんでください', pronunciation: '쿠스리와 이치니치 산카이 논데 쿠다사이', korean: '약은 하루 세 번 드세요' },
      { japanese: '初診ですか', reading: 'しょしんですか', pronunciation: '쇼신 데스카', korean: '처음 오셨나요?' },
      { japanese: 'いつから症状がありますか', reading: 'いつからしょうじょうがありますか', pronunciation: '이쓰카라 쇼-죠-가 아리마스카', korean: '언제부터 증상이 있었나요?' },
    ],
    top: 38,
    left: 8,
    color: '#27ae60',
  },
  {
    id: 'cityhall',
    name_jp: '市役所',
    name_kr: '구청',
    emoji: '🏛️',
    tag: '행정',
    description_kr: '주민등록·이사·재류 카드 관련 표현',
    card_count: 12,
    real_use_count: 2,
    episode_id: undefined,
    expressions: [
      { japanese: '転入届を出したいです', reading: 'てんにゅうとどけをだしたいです', pronunciation: '텐뉴-토도케오 다시타이데스', korean: '전입 신고를 하고 싶어요' },
      { japanese: '在留カードの更新をお願いします', reading: 'ざいりゅうかーどのこうしんをおねがいします', pronunciation: '자이류-카-도노 코-신오 오네가이시마스', korean: '재류 카드 갱신 부탁드립니다' },
      { japanese: '書類が必要ですか', reading: 'しょるいがひつようですか', pronunciation: '쇼루이가 히쓰요-데스카', korean: '서류가 필요한가요?' },
      { japanese: 'マイナンバーカードを申請したいです', reading: 'まいなんばーかーどをしんせいしたいです', pronunciation: '마이난바-카-도오 신세이 시타이데스', korean: '마이넘버 카드를 신청하고 싶어요' },
      { japanese: '何番の窓口に行けばいいですか', reading: 'なんばんのまどぐちにいけばいいですか', pronunciation: '난반노 마도구치니 이케바 이이데스카', korean: '몇 번 창구에 가면 되나요?' },
    ],
    top: 34,
    left: 40,
    color: '#2c3e50',
  },
  {
    id: 'postoffice',
    name_jp: '郵便局',
    name_kr: '우체국·택배',
    emoji: '📮',
    tag: '우편',
    description_kr: '편지·소포·택배에서 쓰는 일본어',
    card_count: 5,
    real_use_count: 0,
    expressions: [
      { japanese: 'この荷物を送りたいです', reading: 'このにもつをおくりたいです', pronunciation: '코노 니모쓰오 오쿠리타이데스', korean: '이 짐을 보내고 싶어요' },
      { japanese: '速達でお願いします', reading: 'そくたつでおねがいします', pronunciation: '소쿠타쓰데 오네가이시마스', korean: '빠른 우편으로 부탁드립니다' },
      { japanese: '不在票が入っていました', reading: 'ふざいひょうがはいっていました', pronunciation: '후자이효-가 하잇테이마시타', korean: '부재중 안내서가 들어 있었어요' },
      { japanese: '着払いでお願いします', reading: 'ちゃくばらいでおねがいします', pronunciation: '챠쿠바라이데 오네가이시마스', korean: '착불로 부탁드립니다' },
      { japanese: '追跡番号を教えてください', reading: 'ついせきばんごうをおしえてください', pronunciation: '쓰이세키반고-오 오시에테쿠다사이', korean: '운송장 번호 알려주세요' },
    ],
    top: 20,
    left: 82,
    color: '#e67e22',
  },
  {
    id: 'bank',
    name_jp: '銀行',
    name_kr: '은행 표현',
    emoji: '🏦',
    tag: '금융',
    description_kr: '통장 개설·송금·ATM 표현',
    card_count: 7,
    real_use_count: 0,
    expressions: [
      { japanese: '口座を作りたいです', reading: 'こうざをつくりたいです', pronunciation: '코-자오 쓰쿠리타이데스', korean: '계좌를 만들고 싶어요' },
      { japanese: '暗証番号を入力してください', reading: 'あんしょうばんごうをにゅうりょくしてください', pronunciation: '안쇼-반고-오 뉴-료쿠 시테쿠다사이', korean: '비밀번호를 입력해 주세요' },
      { japanese: '送金したいです', reading: 'そうきんしたいです', pronunciation: '소-킨 시타이데스', korean: '송금하고 싶어요' },
      { japanese: '通帳を作りたいです', reading: 'つうちょうをつくりたいです', pronunciation: '쓰-초-오 쓰쿠리타이데스', korean: '통장을 만들고 싶어요' },
      { japanese: '残高を確認したいです', reading: 'ざんだかをかくにんしたいです', pronunciation: '잔다카오 카쿠닌 시타이데스', korean: '잔액을 확인하고 싶어요' },
    ],
    top: 62,
    left: 5,
    color: '#f39c12',
  },
  {
    id: 'convenience',
    name_jp: 'コンビニ',
    name_kr: '편의점·정산',
    emoji: '🏪',
    tag: '편의점',
    description_kr: '편의점 일상 표현',
    card_count: 9,
    real_use_count: 3,
    expressions: [
      { japanese: 'Suicaで払います', reading: 'すいかではらいます', pronunciation: '스이카데 하라이마스', korean: 'Suica로 낼게요' },
      { japanese: 'あたためますか', reading: 'あたためますか', pronunciation: '아타타메마스카', korean: '데워드릴까요?' },
      { japanese: 'レシートはいりますか', reading: 'れしーとはいりますか', pronunciation: '레시-토와 이리마스카', korean: '영수증 필요하세요?' },
      { japanese: 'コピーをお願いします', reading: 'こぴーをおねがいします', pronunciation: '코피-오 오네가이시마스', korean: '복사 부탁드려요' },
      { japanese: '袋に入れてください', reading: 'ふくろにいれてください', pronunciation: '후쿠로니 이레테 쿠다사이', korean: '봉지에 넣어주세요' },
    ],
    top: 58,
    left: 48,
    color: '#16a085',
  },
  {
    id: 'police',
    name_jp: '警察署',
    name_kr: '경찰·신고 표현',
    emoji: '🚔',
    tag: '경찰',
    description_kr: '분실·신고·긴급 상황 표현',
    card_count: 4,
    real_use_count: 0,
    expressions: [
      { japanese: '財布を失くしました', reading: 'さいふをなくしました', pronunciation: '사이후오 나쿠시마시타', korean: '지갑을 잃어버렸어요' },
      { japanese: '110番に電話してください', reading: 'ひゃくとおばんにでんわしてください', pronunciation: '햐쿠토-반니 덴와 시테쿠다사이', korean: '110번에 전화해 주세요' },
      { japanese: '遺失物届を出したいです', reading: 'いしつぶつとどけをだしたいです', pronunciation: '이시쓰부쓰토도케오 다시타이데스', korean: '분실물 신고를 하고 싶어요' },
      { japanese: 'パスポートをなくしました', reading: 'ぱすぽーとをなくしました', pronunciation: '파스포-토오 나쿠시마시타', korean: '여권을 잃어버렸어요' },
      { japanese: '交通事故がありました', reading: 'こうつうじこがありました', pronunciation: '코-쓰-지코가 아리마시타', korean: '교통사고가 났어요' },
    ],
    top: 52,
    left: 80,
    color: '#2980b9',
  },
  {
    id: 'station',
    name_jp: '駅',
    name_kr: '전철역',
    emoji: '🚉',
    tag: '교통',
    description_kr: '전철·지하철 탑승·환승 표현',
    card_count: 8,
    real_use_count: 4,
    expressions: [
      { japanese: '〜行きはどこですか', reading: '〜いきはどこですか', pronunciation: '~유키와 도코 데스카', korean: '~행은 어디예요?' },
      { japanese: '乗り換えはどこですか', reading: 'のりかえはどこですか', pronunciation: '노리카에와 도코 데스카', korean: '환승은 어디서 해요?' },
      { japanese: '定期券を購入したいです', reading: 'ていきけんをこうにゅうしたいです', pronunciation: '테이키켄오 코-뉴- 시타이데스', korean: '정기권을 사고 싶어요' },
      { japanese: 'ICカードをチャージしたいです', reading: 'あいしーかーどをちゃーじしたいです', pronunciation: '아이시-카-도오 차-지 시타이데스', korean: 'IC카드 충전하고 싶어요' },
      { japanese: '終電は何時ですか', reading: 'しゅうでんはなんじですか', pronunciation: '슈-덴와 난지 데스카', korean: '막차가 몇 시예요?' },
      { japanese: 'この電車は急行ですか', reading: 'このでんしゃはきゅうこうですか', pronunciation: '코노 덴샤와 큐-코- 데스카', korean: '이 전차는 급행이에요?' },
    ],
    top: 50,
    left: 40,
    color: '#1565c0',
  },
  {
    id: 'bus-terminal',
    name_jp: 'バスターミナル',
    name_kr: '버스터미널',
    emoji: '🚌',
    tag: '교통',
    description_kr: '버스 탑승·노선 문의 표현',
    card_count: 5,
    real_use_count: 2,
    expressions: [
      { japanese: '〜行きのバスはどこですか', reading: '〜いきのばすはどこですか', pronunciation: '~유키노 바스와 도코 데스카', korean: '~행 버스는 어디 있나요?' },
      { japanese: '次のバスは何時ですか', reading: 'つぎのばすはなんじですか', pronunciation: '쓰기노 바스와 난지 데스카', korean: '다음 버스는 몇 시예요?' },
      { japanese: 'このバスは〜に止まりますか', reading: 'このばすは〜にとまりますか', pronunciation: '코노 바스와 ~니 토마리마스카', korean: '이 버스는 ~에 서나요?' },
      { japanese: '運賃はいくらですか', reading: 'うんちんはいくらですか', pronunciation: '운친와 이쿠라 데스카', korean: '요금이 얼마예요?' },
      { japanese: '終点まで乗ります', reading: 'しゅうてんまでのります', pronunciation: '슈-텐마데 노리마스', korean: '종점까지 탈게요' },
    ],
    top: 70,
    left: 58,
    color: '#00695c',
  },
  {
    id: 'airport',
    name_jp: '空港',
    name_kr: '공항',
    emoji: '✈️',
    tag: '교통',
    description_kr: '탑승 수속·출입국·면세 표현',
    card_count: 7,
    real_use_count: 1,
    expressions: [
      { japanese: '搭乗手続きはどこですか', reading: 'とうじょうてつづきはどこですか', pronunciation: '토-죠-테쓰즈키와 도코 데스카', korean: '탑승 수속은 어디서 해요?' },
      { japanese: '手荷物を預けたいです', reading: 'てにもつをあずけたいです', pronunciation: '테니모쓰오 아즈케타이데스', korean: '수하물을 맡기고 싶어요' },
      { japanese: '免税店はどこですか', reading: 'めんぜいてんはどこですか', pronunciation: '멘제이텐와 도코 데스카', korean: '면세점은 어디예요?' },
      { japanese: 'フライトが遅延しています', reading: 'ふらいとがちえんしています', pronunciation: '후라이토가 치엔 시테이마스', korean: '비행편이 지연되고 있어요' },
      { japanese: '出国審査はどこですか', reading: 'しゅっこくしんさはどこですか', pronunciation: '슛코쿠신사와 도코 데스카', korean: '출국 심사는 어디예요?' },
      { japanese: 'パスポートをご提示ください', reading: 'ぱすぽーとをごていじください', pronunciation: '파스포-토오 고테이지 쿠다사이', korean: '여권을 제시해 주세요' },
    ],
    top: 84,
    left: 28,
    color: '#4527a0',
  },
  {
    id: 'immigration',
    name_jp: '入管',
    name_kr: '입국관리청',
    emoji: '🛂',
    tag: '비자',
    description_kr: '비자 신청·갱신·재류 카드 수령 표현',
    card_count: 9,
    real_use_count: 1,
    expressions: [
      { japanese: 'ビザの更新をしたいです', reading: 'びざのこうしんをしたいです', pronunciation: '비자노 코-신오 시타이데스', korean: '비자 갱신을 하고 싶어요' },
      { japanese: '在留期間を延長したいです', reading: 'ざいりゅうきかんをえんちょうしたいです', pronunciation: '자이류-키칸오 엔초- 시타이데스', korean: '재류기간을 연장하고 싶어요' },
      { japanese: '在留カードを受け取りに来ました', reading: 'ざいりゅうかーどをうけとりにきました', pronunciation: '자이류-카-도오 우케토리니 키마시타', korean: '재류 카드를 받으러 왔어요' },
      { japanese: '申請には何が必要ですか', reading: 'しんせいにはなにがひつようですか', pronunciation: '신세이니와 나니가 히쓰요- 데스카', korean: '신청에는 무엇이 필요한가요?' },
      { japanese: '審査にどのくらいかかりますか', reading: 'しんさにどのくらいかかりますか', pronunciation: '신사니 도노쿠라이 카카리마스카', korean: '심사에 얼마나 걸리나요?' },
      { japanese: '在留資格変更申請をしたいです', reading: 'ざいりゅうしかくへんこうしんせいをしたいです', pronunciation: '자이류-시카쿠 헨코-신세이오 시타이데스', korean: '재류자격 변경 신청을 하고 싶어요' },
    ],
    top: 26,
    left: 58,
    color: '#c62828',
  },
  {
    id: 'restaurant',
    name_jp: 'レストラン',
    name_kr: '식당·레스토랑',
    emoji: '🍽️',
    tag: '식사',
    description_kr: '주문·자리 안내·계산 표현',
    card_count: 8,
    real_use_count: 6,
    expressions: [
      { japanese: '席はありますか', reading: 'せきはありますか', pronunciation: '세키와 아리마스카', korean: '자리 있나요?' },
      { japanese: 'ご注文はお決まりですか', reading: 'ごちゅうもんはおきまりですか', pronunciation: '고추-몬와 오키마리 데스카', korean: '주문은 정하셨나요?' },
      { japanese: 'おすすめは何ですか', reading: 'おすすめはなんですか', pronunciation: '오스스메와 난데스카', korean: '추천 메뉴가 뭐예요?' },
      { japanese: 'お会計をお願いします', reading: 'おかいけいをおねがいします', pronunciation: '오카이케이오 오네가이시마스', korean: '계산 부탁드립니다' },
      { japanese: '禁煙席をお願いします', reading: 'きんえんせきをおねがいします', pronunciation: '킨엔세키오 오네가이시마스', korean: '금연석 부탁드립니다' },
      { japanese: '辛さは調節できますか', reading: 'からさはちょうせつできますか', pronunciation: '카라사와 초-세쓰 데키마스카', korean: '매운 정도 조절 가능한가요?' },
    ],
    top: 44,
    left: 70,
    color: '#d84315',
  },
  {
    id: 'pharmacy',
    name_jp: '薬局',
    name_kr: '약국·드럭스토어',
    emoji: '💊',
    tag: '의료',
    description_kr: '처방전·상비약·증상 표현',
    card_count: 6,
    real_use_count: 2,
    expressions: [
      { japanese: '処方箋を持っています', reading: 'しょほうせんをもっています', pronunciation: '쇼호-센오 못테이마스', korean: '처방전을 갖고 있어요' },
      { japanese: '解熱剤はありますか', reading: 'げねつざいはありますか', pronunciation: '게네쓰자이와 아리마스카', korean: '해열제 있나요?' },
      { japanese: '風邪薬をください', reading: 'かぜぐすりをください', pronunciation: '카제구스리오 쿠다사이', korean: '감기약 주세요' },
      { japanese: 'この薬の飲み方を教えてください', reading: 'このくすりののみかたをおしえてください', pronunciation: '코노 쿠스리노 노미카타오 오시에테 쿠다사이', korean: '이 약 복용법을 알려주세요' },
      { japanese: '副作用はありますか', reading: 'ふくさようはありますか', pronunciation: '후쿠사요-와 아리마스카', korean: '부작용이 있나요?' },
    ],
    top: 28,
    left: 26,
    color: '#2e7d32',
  },
  {
    id: 'library',
    name_jp: '図書館',
    name_kr: '도서관',
    emoji: '📚',
    tag: '교육',
    description_kr: '대출·반납·일본어 공부 표현',
    card_count: 4,
    real_use_count: 1,
    expressions: [
      { japanese: '図書カードを作りたいです', reading: 'としょかーどをつくりたいです', pronunciation: '토쇼카-도오 쓰쿠리타이데스', korean: '도서 카드를 만들고 싶어요' },
      { japanese: '日本語の教材はどこですか', reading: 'にほんごのきょうざいはどこですか', pronunciation: '니혼고노 쿄-자이와 도코 데스카', korean: '일본어 교재는 어디 있나요?' },
      { japanese: 'この本を借りたいです', reading: 'このほんをかりたいです', pronunciation: '코노 혼오 카리타이데스', korean: '이 책을 빌리고 싶어요' },
      { japanese: '返却期限はいつですか', reading: 'へんきゃくきげんはいつですか', pronunciation: '헨캬쿠키겐와 이쓰 데스카', korean: '반납 기한이 언제예요?' },
      { japanese: 'コピー機を使いたいです', reading: 'こぴーきをつかいたいです', pronunciation: '코피-키오 쓰카이타이데스', korean: '복사기를 쓰고 싶어요' },
    ],
    top: 64,
    left: 22,
    color: '#6a1b9a',
  },
]

export type VisitStatus = 'done' | 'in-progress' | 'not-started'

export interface MonthlyVisit {
  location_id: string
  status: VisitStatus
  progress: number // 0-100
}

export const MONTHLY_VISITS: MonthlyVisit[] = [
  { location_id: 'supermarket', status: 'done', progress: 100 },
  { location_id: 'hospital', status: 'in-progress', progress: 55 },
  { location_id: 'station', status: 'in-progress', progress: 70 },
  { location_id: 'immigration', status: 'not-started', progress: 0 },
  { location_id: 'cityhall', status: 'not-started', progress: 0 },
  { location_id: 'bank', status: 'not-started', progress: 0 },
  { location_id: 'nursery', status: 'not-started', progress: 0 },
]
